### ISSUE TITLE
Memory leaks‎ with iframes

### ISSUE THREAD

**Issue by geoffreymcgill** [extnet/Ext.NET#10]
http://forums.ext.net/showthread.php?21063-OPEN-Memory-leaks

http://www.sencha.com/forum/showthread.php?242897

Edit by @Daniil:
http://www.sencha.com/forum/showthread.php?264618
http://www.sencha.com/forum/showthread.php?265047
http://www.sencha.com/forum/showthread.php?265051

Sencha opened bugs on the last three reports.

Duplicates:
http://forums.ext.net/showthread.php?25439
http://forums.ext.net/showthread.php?28140

Fake big JavaScript file:
http://forums.ext.net/showthread.php?21063&p=213872&viewfull=1#post213872

**Update:** Issue is allegedly unreproducible by the time ExtJS 6.0.1 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly unreproducible by the time ExtJS 6.0.2 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by geoffreymcgill** [comment]
We can no longer reproduce this memory leak issue as of Ext.NET 4.x. 

Please let us know if you run into this problem with Ext.NET 4.x (or higher) and we will reopen this Issue for investigation.
