### ISSUE TITLE
New on AbstractComponent - AriaAttributes Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1029]
http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.mixin.Accessible-cfg-ariaAttributes

**Comment by fabriciomurta** [comment]
C# type should be `JsonObject`.

**Comment by fabriciomurta** [comment]
[This sencha thread](https://www.sencha.com/forum/showthread.php?298612-Accessibility-Not-able-to-add-aria-tags-to-components) shows a good example on how should `AriaAttributes` be used. This indicates that an annonymous object could be enough to represent the entities usable here.

**Comment by DaniilVeriga** [comment]
Maybe, at some point in future we'll implement like an `AriaAttributes` class that would combine all the possible options if there is really a static list possible. But I think JsonObject is definitely good enough for now.
