### ISSUE TITLE
Modified on RowExpander - ExpandOnEnter Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1033]
http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.grid.plugin.RowExpander-cfg-expandOnEnter

ExpandOnEnter is no longer supported in ExtJS 6. By default, the row is expanded and collapsed on +/- keys. Though, we decided to keep the legacy behavior in Ext.NET. It is disabled by default. To get the legacy behavior please set `ExpandOnEnter="true"` for a RowExpander. `ExpandOnEnter="true"` also **turns off** the new ExtJS 6 behavior of expanding/collapsing on +/- keys.

**Breaking changes summary**:
 * ExpandOnEnter `bool` type has been changed to `bool?`
 * ExpandOnEnter default `true` value has been changed to `false`. I.e. rows are not expanded on Enter key by default.
 * By default, a row is expanded/collapsed on +/- keys.

**Comment by DaniilVeriga** [comment]
Don't remove this property for now. I need to review it in details.
