### ISSUE TITLE
New on Panel - DefaultButton Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1039]

**Comment by fabriciomurta** [comment]
It overrides DefaultButton defined on `AbstractContainer`.
Notice `DefaultButtonTarget` (a coupled configOp, #1040) does not overlap a same definition inside `AbstractContainer`.

**Comment by DaniilVeriga** [comment]
I think we should keep the existing Ext.NET functionality for DefaultButton. If the ExtJS behavior is requested ever, we can review. Marking as invalid.
