### ISSUE TITLE
Window constrain issue

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#105]
http://forums.ext.net/showthread.php?20483

http://www.sencha.com/forum/showthread.php?236881

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-7026.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-7026_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-7026_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-7026_.
