### ISSUE TITLE
Modified on TextField - EmptyText Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1091]
Details:
```
6.0.0
default value is null
6.0.1
default value is ’’
```

**Comment by fabriciomurta** [comment]
I believe this change requires no changes in source code. But as @DaniilVeriga has reopened a couple issues I closed thinking so, i'm forwarding him this issue so he can double-check.

**Comment by DaniilVeriga** [comment]
Agree, that is invalid.

**Comment by fabriciomurta** [comment]
As we raised afterwards:
- Set default value on attribute to `null`
- Change comment description from _Default: null_ to _Default: ''_.

**Comment by DaniilVeriga** [comment]
The commit caused #1232.

**Comment by DaniilVeriga** [comment]
Decided to revert the commit, because it can break the logic in many places.
