### ISSUE TITLE
Modified on RowNumbererColumn - Resizable Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1095]
Details:
```
6.0.0
default value is true
6.0.1
default value is false
```

**Comment by fabriciomurta** [comment]
This is not so simple to change. It has to be changed from `bool` to `bool?` but there's some viewstate/design logic involved that should be understood before fixing.

**Comment by DaniilVeriga** [comment]
That was always false by default. So, invalid.
But created #1183.
