### ISSUE TITLE
FiltersFeature automatic reconfiguring seems to be not impemented

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#110]
http://forums.ext.net/showthread.php?20915
http://www.sencha.com/forum/showthread.php?242183

**Update:** Sencha issue _EXTJS-7273_ allegedly fixed in ExtJS 5.0.0.970 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-7273_ allegedly fixed in ExtJS 5.0.0.970 release.
