### ISSUE TITLE
Modified on Panel - TitleRotation Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1104]
Details:
```
6.0.0
default value is ‘default’
6.0.1
default value is null
```

**Comment by fabriciomurta** [comment]
ExtJS now require a 'default' string value that _"use the default rotation, depending on the dock position of the header"_ thus the type of `public virtual int TitleRotation` in `Ext.Net.AbstractPanel` should be changed to "string".

On the other hand, when the values are provided as strings (rather than numeric), ExtJS does not recognize them and the title becomes empty.

This is a woking configItem setup:
```
            <ext:Panel runat="server" Title="#1004">
                <CustomConfig>
                    <ext:ConfigItem Name="titleRotation" Value='2' Mode="Raw" />
                </CustomConfig>
                <Items>
                    <ext:Label runat="server" Text="label for #1123" />
                </Items>
            </ext:Panel>
```

How to be able to emit both `2` and `'default'`?

**Comment by DaniilVeriga** [comment]
Agree that `default` should be available to set. Ideally, type is ‘default’/0/1/2 should be organized as Enum. Related to #1123.
