### ISSUE TITLE
Modified on PanelTitle - Rotation Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1123]
Details:
```
6.0.0
default value is 0
type is 0/1/2
6.0.1
default value is null
type is ‘default’/0/1/2
```

**Comment by DaniilVeriga** [comment]
There is no need to change the default value of server side since any explicit 0,1,2 values are going to be rendered to client. It is also not a breaking change.

**Comment by DaniilVeriga** [comment]
Ok, [this comment](https://github.com/extnet/Ext.NET/issues/1104#issuecomment-164836577) sort of convinced me that `default` should be available to set. Ideally, `type is ‘default’/0/1/2` should be organized as Enum. Related to #1104.
