### ISSUE TITLE
Chart Mask, zooming issues

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#114]
http://forums.ext.net/showthread.php?19384

http://www.sencha.com/forum/showthread.php?252868
http://www.sencha.com/forum/showthread.php?252869

DUP
http://forums.ext.net/showthread.php?23938

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
The approach to attain the behavior with charts has changed. The forum thread was updated with a test case following the new syntax, which involves using the `CrossZoomInteraction` in the chart.
