### ISSUE TITLE
Removed from PolarSeries, PieSeries, Pie3DSeries - Field Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1166]
It means both xField and yField options were removed from both.

Related to #994.

Compare documentations on [5.1.1](http://docs.sencha.com/extjs/5.1/5.1.1-apidocs/#!/api/Ext.chart.series.Polar) and [6.0.1](http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.chart.series.Polar).

**Comment by DaniilVeriga** [comment]
What is a substitution for them? I mean if we state in breaking changes that something has been removed, we should provide how to deal with that.

**Comment by DaniilVeriga** [comment]
http://docs.sencha.com/extjs/6.0/upgrades_migrations/extjs_upgrade_guide.html

> Polar series.
> Polar series ‘angleField’ and ‘radiusField’ configs have replaced ‘field’/‘xField’ and ‘lengthField’/‘yField’ configs, respectively.
