### ISSUE TITLE
TreeStore directory hierarchy does not match Sencha's Ext.data.TreeStore

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1168]
On Sencha the hierarchy is: `Ext > data > TreeStore`
On Ext.NET it is: `Ext > data > Tree > TreeStore`

**Comment by DaniilVeriga** [comment]
At some point we decided to encapsulate all Tree-related data classes in an individual folder. Well, there is no goal to match exactly the ExtJS directory hierarchy. Though, we usually do.
