### ISSUE TITLE
New on PolarSeries - AngleField Config

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1169]
http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.chart.series.Polar-cfg-angleField

**Comment by fabriciomurta** [comment]
Notice in Ext.NET both `PieSeries` and `Pie3DSeries` inherit from `PolarSeries` so, adding this option will also add it for those classes. [Ext.chart.series.Pie](http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.chart.series.Polar-cfg-angleField) just inherits this option but [Ext.chart.series.Pie3D](http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.chart.series.Pie3D-cfg-angleField) overrides it with a numeric limitation, according to docs.
