### ISSUE TITLE
iPad iframe scrolling doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#117]
http://forums.ext.net/showthread.php?21834

Duplicates:
http://forums.ext.net/showthread.php?47291
http://forums.ext.net/showthread.php?52392

Bug reports to Sencha:
http://www.sencha.com/forum/showthread.php?289082
http://www.sencha.com/forum/showthread.php?291344

Possible fix for iOS.
http://davidwalsh.name/scroll-iframes-ios

**Comment by geoffreymcgill** [comment]
Zynga scroller might be helpful too. 

http://zynga.github.io/scroller/

**Comment by DaniilVeriga** [comment]
It has been fixed in the revision 6321 (trunk). It goes to 3.1.0.

Applied [this CSS fix](http://davidwalsh.name/scroll-iframes-ios).

Please note that it is fixed only for a case when an iframe is being loaded using a Loader with Mode="Frame". If you use an iframe without a Loader, you are supposed to apply a CSS fix manually.

**Comment by geoffreymcgill** [comment]
Nice work @DaniilVeriga on implementing this fix.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-15042_ allegedly fixed in ExtJS 6.5.1 release.
