### ISSUE TITLE
Remove NuGet packages from the solution

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1196]
Currently, all NuGet packages that would be downloaded once the project is built using Visual Studio are pre-committed in the repository. This adds not only extra space for the storage, but also additional steps when NuGet packages are being updated in the projects.

Remove the NuGet packages so they are downloaded when the project is built, getting packages as they are really necessary.

**Comment by fabriciomurta** [comment]
Tested building all configutarions after removing local copy of packages, no problems found.

**Comment by DaniilVeriga** [comment]
Removal of the packages has been merged.

Please update the .gitignore file adding:
```# NuGet Packages Directory
packages/*
!packages/repositories.config
```

**Comment by fabriciomurta** [comment]
Done.
