### ISSUE TITLE
ComboBox and BoundList pageSize inconsistency

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#120]
http://forums.ext.net/showthread.php?22943
http://www.sencha.com/forum/showthread.php?253365

Duplicate:
http://forums.ext.net/showthread.php?35561&p=160621&viewfull=1#post160621

**Update:** This issue is allegedly fixed in ExtJS since 4.2.x.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8188_ allegedly fixed in ExtJS 4.2 release.
