### ISSUE TITLE
Adding custom items to a TagField incurs to JavaScript errors in updateIndexes()

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1206]
On examples explorer, if adding a custom value to the first tag field in the [TagField Example](http://examples3.ext.net/#/Form/Tag/TagField/), the a JavaScript error is raised.

It happens when adding a custom value, that a predefined value gets enlisted on a `this.all.elements` during the add process. Additionally, the expected and added value is also on `this.all.elements` vector, but when parsing the `records` vector, it contains only the truly added (the custom-typed entry).

In other words, when updating indexes in the tags list, it adds a rogue predefined tag when adding a custom one that forces the indexer to check for another added record where there aren't any.

This was pointed in this forum thread: [TagField control getValue() issue when adding custom values](http://forums.ext.net/showthread.php?60465)

**Update:** This is still actual in Ext.NET 4 with updated scripts, and not reproducible on ExtJS examples both for [5.1.x](http://dev.sencha.com/ext/5.1.0/examples/kitchensink/#form-tag) and [6.0.1](http://examples.sencha.com/extjs/6.0.1/examples/kitchensink/#form-tag).

**Comment by fabriciomurta** [comment]
It looks like [ExtJS has TagField since 5.1.1](http://docs.sencha.com/extjs/5.1/5.1.1-apidocs/#!/api/Ext.form.field.Tag) at least. It also looks like [Ext.NET is still using third-party/custom TagField](https://github.com/extnet/Premium/blob/a404487/Ext.Net/Ext/UX/Tag/TagField.cs#L44), which didn't make it from ExtJS 4.x to 5.x.

So probably the fix would be just switching to ExtJS' TagField.

**Comment by DaniilVeriga** [comment]
TagField appeared in Ext.NET before a similar component appeared in ExtJS. When it appeared in Ext.NET, we decided to keep using our own TagField, because it had some functionality that is not presented in ExtJS TagField. Maybe, ExtJS TagField already has or will have all the required functionality, then we could consider migrating to ExtJS TagField.

Meanwhile, I am investigating the issue.

**Comment by DaniilVeriga** [comment]
The issue is related to this one - #834.
