### ISSUE TITLE
ComboBox is broken on Ext.NET 4 (alpha)

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1211]
Attempt to display combo box's entries results in JavaScript error on current Ext.NET state.

The simplest form of a bare combo box definition breaks:
```xml
<ext:ComboBox runat="server" />
```

The error is triggered on `Ext.form.field.Picker.getPicker()`, where it tries to create a picker, and the creation returns 'undefined', thus the just created picker object will have no `ownerCmp` attribute to be bound value to and the error triggers.

**Comment by fabriciomurta** [comment]
The problem is on combobox override for createPicker which returns nothing.

**Comment by fabriciomurta** [comment]
Tracked down the commit to 7db83a8 (in Premium repo). Due to the size of the commit, it is difficult to comment and link the commit here.

Maybe the override that caused this bug is no longer necessary.

**Comment by DaniilVeriga** [comment]
> Most likely the override that caused this bug is no longer necessary.
