### ISSUE TITLE
RightButtons/LeftButtons on TextFields when ShowMode="Focus" makes it re-focused on focus leave

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1224]
Once you focus a textField with left/right buttons and ShowMode = Focus, the only way to focus out of it is repeatedly and quickly clicking out of it. Else it just keeps getting back focus to the TextField.

```xml
<ext:TextField FieldLabel="Focus Me" RightButtonsShowMode="Focus" runat="server">
    <RightButtons>
        <ext:Button runat="server" Icon="Add" />
    </RightButtons>
</ext:TextField>
<ext:TextField runat="server" FieldLabel="Lose focus here. :)" />
```

This was found while investigating this forum issue: [TextField is unfocused when right button is clicked](http://forums.ext.net/showthread.php?60510).

**Comment by DaniilVeriga** [comment]
Appears to be reproducible in IE only. I am investigating.

**Comment by DaniilVeriga** [comment]
Related to #884.
