### ISSUE TITLE
Panels with FormLayout ignore fields' LabelAlign property.

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1234]
This can be seen in this example: [FormLayout overview](http://examples3.ext.net/#/Layout/FormLayout/Overview/).
The affected sample entries are **Form 3** and **Form 5**.

There's also a sencha thread opened: [Panel with layout:form and fields with labelAlign: top not working](https://www.sencha.com/forum/showthread.php?308253)

This was originally reported on #1217.105.

This worked fine in Ext.NET 2.x and ExtJS up to 4.2.1.

**Comment by fabriciomurta** [comment]
It seems the `labelAlign` option is NOT meant to be used together with `FormLayout` after all (see the Sencha forum thread).

**Comment by DaniilVeriga** [comment]
Yes, FormLayout has been modified in ExtJS not to use label settings like `LabelAlign`. If label settings are required, then AnchorLayout should be used instead. So, the example has been updated properly.
