### ISSUE TITLE
Ext.DateColumn does not have a Width config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1236]
According to sencha, Ext.grid.column.Date has a width config. But in Ext.NET there's no such setting. Alternatively, `WidthSpec` works pretty much the same. But `Ext.Column` contains both `WidthSpec` and `Width` configs.

**Comment by DaniilVeriga** [comment]
@fabriciomurta, I see that the Ext.Net.DateColumn class has the Width setting inheriting it from the AbstractComponent class in the same way as the Ext.Net.Column class does. Please double check your conclusions. For now, I am marking the issue as invalid.
