### ISSUE TITLE
Badges are drawn behind panel titles

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1237]
This is happening due  to the css class `x-docked` having `z-index: 2`. Although badge's `z-indez` is set around 99999999...

One way to avoid this issue is to set the following css override:
```css
.x-docked {
    z-index: auto
}
```
In the page using badges. But this most likely would bring other issues that require `x-docked` CSS class to define `z-index: 2`.

**Comment by fabriciomurta** [comment]
Commit [fa04568](https://github.com/extnet/Premium/commit/fa04568) might be undone after this issue is implemented.

**Comment by DaniilVeriga** [comment]
> Although badge's z-indez is set around 99999999...
It is `z-index: 1` for me.

The difference between ExtJS 5 and 6 appears to be:
ExtJS 5 has `z-index: 1` for `.x-docked`, but ExtJS 6 has `z-index: 2`.
