### ISSUE TITLE
GridPanel Grouping collaseAll/ExpandAll throw a JavaScript error

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1238]
#1217.88
#1252.49
https://www.sencha.com/forum/showthread.php?306725

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
Couldn't reproduce this on #1217.88 during 4.1.0 tests (extnet/Ext.NET.Examples#5 item 19).
