### ISSUE TITLE
TreePanel in menu in IE9: clicking quickly expand/collapse hides menu

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#124]
http://forums.ext.net/showthread.php?22964
http://www.sencha.com/forum/showthread.php?253603

**Update:** Sencha issue _EXTJS-8243_ allegedly fixed in ExtJS 4.2.0.489 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8243_ allegedly fixed in ExtJS 4.2.0.489 release.
