### ISSUE TITLE
Ext.net.DropDownField: TriggerIcons are incompatible with Triton theme

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1241]
On example: [DropDownField Overview](http://examples3.ext.net/#/Form/DropDownField/Overview/)

Most icons available for use as `TrigerIcons` do not fit on the Triton theme. They show the default character of the drop down plus the icon repeated 2 or 4 times in place.

This issue was spotted while testing #1217.63 using Triton theme.

Some icons like `TriggerIcon="search"` work well. Most of them, like `TriggerIcon="SimpleArrowDown"`, don'.t

**Comment by fabriciomurta** [comment]
Update: one of the reason the problem happens is because Triton uses font Awesome's glyphs instead of picture icons.

**Comment by DaniilVeriga** [comment]
The issue has been fixed - the icons are displayed correctly now. Though, TriggerIcons are still needed to be reviewed for better consistency with all non-classic themes. Created #1279.
