### ISSUE TITLE
Triton Theme: FieldTrigger Icons and DropDown's TriggerIrcons display glitched

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1247]
These two examples illustrate the issue:
- [EditorGrid with TextField Editor and Dialog @examples4](http://examples4.ext.net/#/Form/Triggers/Trigger_with_Dialog_Editor/)
- [DropDownField Overview @examples4](http://examples4.ext.net/#/Form/DropDownField/Overview/)

Notice the second example might need to have a theme test on `Page_Load()` to be commented out before the issue can be reproduced.

While using Triton theme, most field's trigger button icons are broken, as the theme no longer uses actual image icons, but font glyphs. On the broken cases, usually the original icon is displayed replicated in 4 tiles on the button area, instead of a single, centered button.

**Comment by fabriciomurta** [comment]
![i1247_broken_btns](https://cloud.githubusercontent.com/assets/10730372/12602517/0dd55206-c491-11e5-94e7-a9604dbe8506.png)
For archiving purposes, this is how the DropDownField example currently looks. The same happens with the other example.

**Comment by fabriciomurta** [comment]
Another broken example, just in case: http://localhost:51299/Examples/Form/Triggers/Trigger_Icons/Default.aspx

**Comment by DaniilVeriga** [comment]
Probably, the same issue has been reported a little earlier.
https://github.com/extnet/Ext.NET/issues/1241

**Comment by DaniilVeriga** [comment]
The issue has been fixed - the icons are displayed correctly now. Though, TriggerIcons are still needed to be reviewed for better consistency with all non-classic themes. Created #1279.
