### ISSUE TITLE
HtmlEditor's glitch with toolbar's images in Crisp theme

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1249]
#1217.64
#1252.8.1
Reproducible with a [Sencha example](http://examples.sencha.com/extjs/6.0.1/examples/classic/desktop/index.html) (click Notepad).
![htmleditor](https://cloud.githubusercontent.com/assets/1510884/12637960/6cd4b278-c5aa-11e5-927c-6981dfc293fa.JPG)

Sencha issue: [Toolbar icons are not "correct" in HTML Editor in crisp there](https://www.sencha.com/forum/showthread.php?299240)
PR - extnet/Premium#81

**Comment by DaniilVeriga** [comment]
extnet/Premium#81

**Comment by fabriciomurta** [comment]
Still reproducible as of ExtJS 6.0.2 release. Found a related sencha thread and assigned to the first message above. The thread is still marked as open.

Interesting though, there's a thread claiming it was fixed, but someone else already voiced that it didn't fix. The sencha thread with the false fix report would be: [Icons bug in htmleditor](https://www.sencha.com/forum/showthread.php?293864)

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-17124.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-17124_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-17124_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-17124_.
