### ISSUE TITLE
Improve the MouseDistanceSensor UX plugin

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1257]
Currently, the MouseDistanceSensor plugin relies on `createBuffered()` to call the `onMouseMove()` event.

It just happens that, every call makes a javaScript `setTimeout()` assynchronous event that is fired 50ms later. But as the `mouseMove` events are too frequent, another event gets called within this time frame. `createBuffered()` then cancels the not called `setTimeout()` (to avoid a long calling queue), and creates another `setTimeout()` task. It ends up that, while the mouse is still moving, the opacity of the distance-sensitive panel is not updated in this approach.

The idea is to change the approach and limit the frequency of effective `onMouseMove` events to one at every 50ms, adjustable.

**Comment by vladsch** [comment]
createBuffered can be replaced by createThrottled

**Comment by DaniilVeriga** [comment]
extnet/Ext.NET#1217.115
extnet/Ext.NET#1218.37
extnet/Ext.NET#1252.71
extnet/Ext.NET#1253.29
