### ISSUE TITLE
Ext.net.Image does not properly handle ImageUrl= setting

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1269]
A
```xml
<ext:Image runat="server" ImageUrl="http://speed.ext.net/identity/extnet-logo-large-vertical.svg" />
```
Is turning into:
```xml
<img id="ext-element-4" style="border: currentColor; border-image: none; width: 1586px;" src="">
```
So, no image is displayed at all.

Reported on: [Image can not be displayed by Image field](http://forums.ext.net/showthread.php?60667).

**Comment by DaniilVeriga** [comment]
There is a related issue - #1230. Some new properties have been added to the Image class, but the underlying JavaScript was not revised properly. Please leave this issue for me.

**Comment by fabriciomurta** [comment]
Sorry, I only seen your reply after I pushed the changes!

**Comment by DaniilVeriga** [comment]
It is fine that you have got it fixed!
