### ISSUE TITLE
Synching Store via its OnBeforeChange handler triggers a JavaScript error if there are a few different operations (update, insert or delete)

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1273]
This issue has been both reported solution proposed on thread: [Error in StoreCustomLogic example](http://forums.ext.net/showthread.php?60557).

A race condition on `Ext.data.AbstractStore` can prevent tasks to be fulfilled when it can destroy components needed for further steps as detailed in the [user's report](http://forums.ext.net/showthread.php?60557&p=277418#post277418).

A possible override to the ExtJS class is proposed in the same forum thread and should be considered for fixing.

There's a Sencha Thread that suggests that it might be a bad usage of `Ext.data.AbstractStore.sync()` on our [Store Custom Logic example](): [Post #5 in Store.sync() destroys loaded records](https://www.sencha.com/forum/showthread.php?237518&p=873744#post873744). This should be taken into consideration too.

**Comment by DaniilVeriga** [comment]
I've removed the `sencha` label, because `.createTempProxy()` is the functionality of Ext.NET and I don't think it is a bug in ExtJS.

**Comment by DaniilVeriga** [comment]
Fixed after v3.3 and in v4.2.0.
