### ISSUE TITLE
New ColorField and ColorButton components

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1276]
http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.ux.colorpick.Field
http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.ux.colorpick.Button

**Comment by fabriciomurta** [comment]
There are two other issues tracking these functionalities: #959 and #961.
