### ISSUE TITLE
Horizontal scrolling issue with RTL GridPanel with RowEditor and Chrome

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1281]
Reported on this forum thread: [GridPanel with Row Editor Horizontal Scroll when RTL is true](http://forums.ext.net/showthread.php?60709).

Sencha issue: [Problem with grid roweditor in extjs 5.1.0 => RTL](https://www.sencha.com/forum/showthread.php?295991) - open since December 2014.

Tested on Ext.NET 3.3.0 and 4.0.0-beta using test case provided on Ext.NET forum thread above and issue happens on both.

IE11 is not affected by the issue.

**Comment by fabriciomurta** [comment]
IE11: works fine.
Chrome 48: scrolls in the opposite direction!
Firefox 44: does not scroll at all!
Safari 9.0.3 (11601.4): scrolls in the opposite direction! Same as Chrome 48 above.
Edge 25: works fine. Same as IE11.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
It seems this issue is no longer actual at least with ExtJS 6.0.2: http://jsfiddle.net/fabricio_object/bvezfspy/3/ (this information was added to the Sencha thread)

**Comment by DaniilVeriga** [comment]
There is a workaround for Ext.NET v3 suggested here:
http://forums.ext.net/showthread.php?60709&p=278536&viewfull=1#post278536

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.2.1 release.

**Comment by fabriciomurta** [comment]
Tested with Ext.NET 4.2.0, issue still reproducible.

**Comment by fabriciomurta** [comment]
The issue is fixed if the grid view has also RTL specified as true. In other words:
```xml
<ext:GridPanel runat="server" RTL="true">
    <ViewConfig runat="server" RTL="true" />
</ext:GridPanel>
```

Is required in order for RTL horizontal scrolling to work with the grid regardless of using the row editing plugin or not.

**Comment by fabriciomurta** [comment]
The issue persists with Firefox according to the report #1501.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-16225.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-16225_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-16225_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-16225_.
