### ISSUE TITLE
Missing BREAKING_CHANGES history in Ext.NET 3.

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1286]
From Ext.NET 2, there were a breaking changes link detailing incompatibility differences between all minor versions inside the 2.x series: [breaking changes link in EE 2](http://examples2.ext.net/#/Getting_Started/Release_Documents/BREAKING_CHANGES/)

The same information is not available on Ext.NET 3. At least a link to somewhere pointing to the new way to query breaking changes should be provided, specially as once that link existed for v3 EE.

This was reported as a recent post on this Ext.NET forum issue: [Upgrading from 2.4 to 3.0 - Post #3](http://forums.ext.net/showthread.php?48232&p=277622#post277622)

**Comment by geoffreymcgill** [comment]
The Breaking Changes items have been moved to the CHANGLOG.

http://examples3.ext.net/#/Getting_Started/Release_Documents/CHANGELOG/
