### ISSUE TITLE
Ext.net.Notification is shown behind windows

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1291]
Reported on this forum thread: [Notification doesn't show in front with two modal windows](http://forums.ext.net/showthread.php?60755).

Notifications are not displaying in front of windows when modals are applied in two levels (thus two levels of z-index stacking).

This problem is also reproduceable in the example [Client-side notification](http://examples3.ext.net/#/MessageBox/Notification/Client-Side_Notification/) when trying to display the notification _Custom Align_ -> _Show bottom right inside window_.

So, there's a problem with the z-index calculating of the notification. It should get highest z-index of active mask in window and use a value above this. Just setting the notification's `style` parameter to a higher value is not enough.

**Comment by DaniilVeriga** [comment]
Fixed after v3.3 and in v4.2.0.
