### ISSUE TITLE
GridPanel with GroupPaging does not correctly render on initial load

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1293]
This has been reported here: [Group Paging example is broken](http://forums.ext.net/showthread.php?60758).

The error is very similar to #1280. There's a chance more plugins to Grid Panel are affected by this issue.

**Comment by DaniilVeriga** [comment]
The issue has been fixed in the repo. As for the Group Paging example online, it will be updated with the 4.1.0 release.
