### ISSUE TITLE
Include MVC2 NuGet packages on Ext.NET v1

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1304]
Currently MVC2 reference is set thru system references. This is no longer valid in newer OS like Windows 10 with VS2015. So, the reference method for the MVC package must be turned into NuGet packages' referencing.

This was reported on this Ext.NET forum thread: [Assemblies missing in the repository?](http://forums.ext.net/showthread.php?60807)

**Comment by geoffreymcgill** [comment]
Development of Ext.NET has stopped.
