### ISSUE TITLE
Moving editor in GridPanel on Tab and Enter keys

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#131]
http://forums.ext.net/showthread.php?21924
http://forums.ext.net/showthread.php?23114
http://forums.ext.net/showthread.php?26026

http://www.sencha.com/forum/showthread.php?254342
http://www.sencha.com/forum/showthread.php?254344

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
The tab behavior works fine now, even with locking grid.
The enter behavior is currently set to apply (stop editing, accepting changes). If this behavior is still demanded, then make it a feature request.
