### ISSUE TITLE
Incorporate Pictos font icons package into Triton theme

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1310]
By default, the Pictos font icons package is not included into the Triton theme ([more details](http://docs.sencha.com/extjs/6.0/core_concepts/font_ext.html)).

The Pictos icons has been asked in this [forum thread](http://forums.ext.net/showthread.php?60806) and it has been decided to build it into Ext.NET Triton theme by default.

#### How to incorporate the Pictos package into the Triton theme

Note. It is written and tested with ExtJS 6.0.2 and Sencha CMD v6.1.2.15. With further versions some slight changes are possible

1. Install Sencha CMD. [Guide](intro: http://docs.sencha.com/cmd/6.x/intro_to_cmd.html). 
2. Open this file: `<ExtJS  #root>\classic\theme-triton\package.json`
3. Add `"font-pictos"` to the `"requires"` section. The section will look:

 ```
 "requires": [
    "font-awesome",
    "font-ext",
    "font-pictos"
]
 ```
4. Run a command console (cmd in Windows)
5. Set the current folder to the Theme Triton package: `cd <ExtJS root>\classic\theme-triton`
6. Run this command: `sencha package build`
7. Incorporate the Triton theme into Ext.NET in a regular way from this folder: `<ExtJS root>\build\classic\theme-triton\resources`.

@fabriciomurta, could you, please, incorporate this instruction into "Incorporating ExtJS upgrade to Ext.NET" guide?

**Comment by fabriciomurta** [comment]
Instructions merged into the Ext.NET upgrade document file!

**Comment by fabriciomurta** [comment]
Seems a bug with the themes setting made a missing file, and [EXTJS-17080 bug is in effect](https://www.sencha.com/forum/showthread.php?325710) -- workaround included.
