### ISSUE TITLE
Wrong numbers in RowNumberer in paged GridPanel with Grouping Feature 

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1317]
Found: 4.5.0 (when Ext.NET forum thread complaint was filed)
Sencha thread: [Wrong numbers in RowNumberer in paged Grid with Grouping Feature](https://www.sencha.com/forum/showthread.php?305781)
Ext.NET forum thread: [Spreadsheet row number not working correctly when groupSummary enabled](https://forums.ext.net/showthread.php?62205)

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.2.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-19526.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-19526_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-19526_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-19526_.
