### ISSUE TITLE
Ext.Net.HyperlinkButton tries to open unexisting link in the buttons with IE11

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1318]
This has been reported on the following Ext.NET forum thread: [HyperlinkButton fails on IE-11](http://forums.ext.net/showthread.php?61086).

On IE11, by clicking on a link, forces a rogue tab to be opened, pointing to no specific web address. When switching back to the original page link, we can see the expected dialog box shown on the apge.

On chrome at least, only the dialog box showing event happens.

**Comment by DaniilVeriga** [comment]
That is a side effect of #624 which is an ExtJS bug. Committed the fix for HyperlinkButton. Remove the fix when it is fixed in ExtJS.
