### ISSUE TITLE
实例GridFilters Remote有问题

### ISSUE THREAD

**Issue by zhoujianxiong** [extnet/Ext.NET#1319]
在实例GridPanel=>Plugins=>GridFilters Remote中使用Size的Filters会出现无限刷新的问题

**Comment by fabriciomurta** [comment]
Hello! Thanks for the report! Can you review your bug report in English please?

Google translate suggests this text:
_"Examples GridPanel => Plugins => GridFilters Remote use Size will appear in the Filters Unlimited refresh problem"_

Okay, I seem to be able to reproduce something here. Once a filter entry is chosen in the `Size` column, the grid gets stuck on a loop updating over and over.

**Comment by fabriciomurta** [comment]
We have just tested this on our upcoming 4.1.0 examples explorer and the issue is no longer reproducible once we merged Ext.NET with ExtJS 6.0.2.

**Comment by zhoujianxiong** [comment]
Thank you for your reply
