### ISSUE TITLE
Ext.form.field.ComboBox with ForceSelection and DisplayTpl deselects entry on tabbing out

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1339]
Reported here: [ComboBox with DisplayTpl cleared when losing focus in 4.1](http://forums.ext.net/showthread.php?61164)
Sencha issue: [ComboBox with forceSelection and displayTpl deselects selected item on tabbing out](https://www.sencha.com/forum/showthread.php?311598)

If you run the example in the thread above:
1. select something,
2. tab to the next field
3. tab back to the previous field, use no arrow keys (so no selection happens) 
4. tab forward again to the next field

The first field (combobox in question) will be set blank. The forum thread above suggests an override that works in this case, but further investigation whether it breaks in other situations should take place.

By setting `ForceSelection = false` the problem no longer becomes reproducible. But anyway, forceSelection shouldn't force selecting a value of empty/null.

Pending check: whether this is reroducible in pure Sencha.

**Comment by DaniilVeriga** [comment]
Reproduced with pure ExtJS and reported to Sencha:
https://www.sencha.com/forum/showthread.php?311598

**Comment by fabriciomurta** [comment]
Issue was no longer reproducible via the fiddle @DaniilVeriga provided if the version was switched to ExtJS 6.2.1. It was not reproducible in Ext.NET after ExtJS 6.2.1 merge as well.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue has not been reviewed by Sencha.
