### ISSUE TITLE
ComboBox syncing selection with value issue

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#134]
http://forums.ext.net/showthread.php?23180
http://www.sencha.com/forum/showthread.php?254712

**UPDATE**: still reproducible with ExtJS 5.1.0. These bug reports might be related to the original problem.
http://www.sencha.com/forum/showthread.php?296885
http://www.sencha.com/forum/showthread.php?296397

Needs to test with ExtJS 5.1.1 when it appears.

**UPDATE:** Still reproducible with ExtJS 5.1.1. and Ext.NET 3.2.0.

**Update:** This has been fixed exactly on ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16323_ allegedly fixed in ExtJS 5.1.1 release.
