### ISSUE TITLE
Ext.Net.RowExpander: rowExpand body is aligned and limited by the second column of the outer grid

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1341]
Reported here: [Issue with nested grid panel](http://forums.ext.net/showthread.php?61184).

It is possible to notice this behavior on this example: [GridPanel > Row Expander > Local Mode](http://examples4.ext.net/#/GridPanel/RowExpander/Local_Mode/)

When expanding the row, notice the contents inside are aligned outside the first grid column "Company". If you hide "Company" it will then align to the next column, skipping "Price" then.

**Comment by ohelmer** [comment]
There is still a problem here: http://examples.ext.net/#/GridPanel/RowExpander/Dynamic_GridPanels/
When expanding the nested data is not shown.

**Comment by DaniilVeriga** [comment]
The fix requires updating Ext.Net.dll in the Examples Explorers which means that it will only happen with the next public release which is 4.2.0.

To fix it in your code, you can use a workaround (well, which is actually a fix):
http://forums.ext.net/showthread.php?61184&p=278966&viewfull=1#post278966

Or, if you are a Premium Subscription owner, you can update from the sources.
