### ISSUE TITLE
MultiUpload don't work without flash

### ISSUE THREAD

**Issue by atallo** [extnet/Ext.NET#1348]
MultiUpload function use SwfUpload with Flash.

Can migrate to HTML5?

Thanks,

**Comment by fabriciomurta** [comment]
Hello Atallo!

You can use Ext.NET's [FileUploadField](http://examples4.ext.net/#/Form/FileUploadField/Basic/) if flash doesn't suit you.

**Comment by atallo** [comment]
Hello fabriciomurta !

Of course... but FileUploadField is less funtional...

**Comment by fabriciomurta** [comment]
Alright, updated the issue to reflect a feature request issue!

**Comment by fabriciomurta** [comment]
Reviewed the issue tags again. It says multiupload does not work in chrome 51, we couldn't reproduce this by our side. Of course, if you provide a test case reproducing the issue, we'd more than glad to review it!

**Comment by atallo** [comment]
I don't say "multiupload does not work", I said "current multipload implementation use SwfUpload and Flash". 

SwfUpload is deprecated: https://github.com/WordPress/secure-swfupload This link said: "We strongly suggest you do not use SWFUpload"
Flash is deplecated: http://www.cnet.com/news/google-to-block-flash-on-chrome-only-10-websites-exempt/

HTML5 have same funtionality... and It should be possible migrate multiupload to html5

This is only request feature.

**Comment by fabriciomurta** [comment]
Well, just a late follow up but, multiupload is basically a component using swfupload. Making it HTML5 or other technology-based will be another component. So we get what you suggested is a second alternative to multiupload, that may include deprecating multiupload for good. But I don't think a new component although it may have a similar approach to multiupload, will have the exact same functionalities and interface, as the flash infrastructure itself will be excluded.

So we'll put back the 'feature' tag here, but we currently have no details on when we will implement this feature, if ever. Actually it would depend a lot on the community feedback on the need of another multiupload alternative. I see several people can use the `FileUploadField` currently and seems whatever `Multiupload` can't do, the other simpler component can be extended to.

**Comment by atallo** [comment]
Url of [secure-swfupload](https://github.com/WordPress/secure-swfupload) show info about bugs of component included with ext.net, and show info about better alternative: [plupload](https://www.plupload.com)

**Comment by atallo** [comment]
I close. Too long no response. In current versions the possibility was eliminated.
