### ISSUE TITLE
Mark Component's AutoScroll as obsolete and add Scrollable setting instead

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1354]
AutoScroll has been deprecated in ExtJS a while ago. It is time to mark it as obsolete in Ext.NET and add the Scrollable setting to be used instead of the AutoScroll one.

The AutoScroll setting might be removed any time in further releases, but has been left for now not to introduce a breaking change.

**Comment by fabriciomurta** [comment]
Well, the commit is there, so I believe it is good to be closed. Ext.NET 5 should clear everything marked with obsolete then.
