### ISSUE TITLE
Ext.Menu is not showing by swipe gesture

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1363]
https://www.sencha.com/forum/showthread.php?281225

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID TOUCH-5328.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID TOUCH-5328.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _TOUCH-5328_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _TOUCH-5328_.
