### ISSUE TITLE
Grid's MultiSelection plugin cannot remove multiple records

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1364]
https://www.sencha.com/forum/showthread.php?303272

**Comment by fabriciomurta** [comment]
Related issue for override removal: #1435

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-18628.

**Comment by fabriciomurta** [comment]
The Sencha issue is still marked as open and the test case (fiddle) has some quirks (probably unrelated to this specific problem) when loaded with ExtJS 6.5.1.
