### ISSUE TITLE
Implement RenderMode.Config to render a Razor partial view as a config using PartialViewResult

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#1368]

**Comment by DaniilVeriga** [comment]
Implemented for Ext.NET Mobile. Port to Ext.NET as well.

**Comment by fabriciomurta** [comment]
Issue #1415 will handle implementing on classic Ext.NET.
This feature was reviewed on #1392 for a problem involving the partial view's resources that were not being appended/encapsulated to the code.
