### ISSUE TITLE
Grid column: set editable to true by default when an editor is defined to the column

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1371]
Reported on this Ext.NET forum thread: [Grid - Row editor is doesn't show the fields for editing](http://forums.ext.net/showthread.php?61358)
Found: 4.1.0-beta

This feature request just asks Ext.NET mobile to assume the same behavior of Ext.NET, where it does enable the editable setting of a column just by adding an editor component to it.

**Comment by DaniilVeriga** [comment]
Implemented.
