### ISSUE TITLE
ComboBox's EnableRegex ignores CaseSensitive setting

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1376]
Reported on this forum thread: [ComboBox TypeAhead Search In-Case Sensitive](http://forums.ext.net/showthread.php?61384)
Found: 3.3.0
Sencha thread: [ComboBox's enableRegEx is case sensitive](https://www.sencha.com/forum/showthread.php?268447)

If Ext.Net.ComboBox.EnableRegex is true, then its CaseSensitive setting is ignored -- rendering the type ahead functionality always case sensitive.

**Comment by DaniilVeriga** [comment]
This issue duplicates #320.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-10751.
