### ISSUE TITLE
The download file error.(Invalid or unexpected token)

### ISSUE THREAD

**Issue by mengshuaiyang** [extnet/Ext.NET#1388]
![image](https://cloud.githubusercontent.com/assets/11664228/19105794/8349405a-8b16-11e6-8462-fff7b6d870aa.png)
![360 16200720413688](https://cloud.githubusercontent.com/assets/11664228/19105718/0b186296-8b16-11e6-934f-1ca879d14535.png)
If need to download the file in a page, but no use to download the control  (ext:FileUploadField), will quote us the above error.

What is the cause of the above mistakes?

**Comment by fabriciomurta** [comment]
Hello @mengshuaiyang!

We will require you to provide a runnable and simplified test case for us to be able to reproduce the issue and provide you with advice about the issue.

The following two Ext.NET forum posts provide many excellent tips for posting test cases:

1. [More Information Required](http://forums.ext.net/showthread.php?10205)
2. [Forum Guidelines](http://forums.ext.net/showthread.php?3440)

**Comment by fabriciomurta** [comment]
No feedback for a long time, well, should mark this as closed.
