### ISSUE TITLE
Summary of Obsolete properties removed

### ISSUE THREAD

**Issue by geoffreymcgill** [extnet/Ext.NET#1407]
We are cleaning up old properties that should no longer be used, but were previously marked with an `[Obsolete]` attribute to provide temporary backwards compatibility. 

As of Ext.NET 5.0, we are removing those old properties from the project. This will create breaking changes if the `[Obsolete]` properties are still being used.

This is a summary of properties that have been removed in Ext.NET 5.0.

**Comment by geoffreymcgill** [comment]
We changed our mind. We will not remove `[Obsolete]` properties until the Ext.NET 5 release.

**Comment by fabriciomurta** [comment]
A summary of the changes by a single commit wiping all deprecated features. Details for each within the cited issue.

- Ext.Net.ColumnAlign.Left (enum), extnet/Ext.NET#1655
- Ext.Net.ColumnAlign.Right (enum), extnet/Ext.NET#1655
- Ext.Net.Application.EnableQuickTips (property), extnet/Ext.NET#1656
- Ext.Net.PanZoomInteraction.ZoomOnPanGesture (property),
  extnet/Ext.NET#1657
- Ext.Net.RotatePie3D (class), extnet/Ext.NET#1532
- Ext.Net.ComponentBase.AutoScroll and all its references:
  - Ext.Net.ComponentBase.SetAutoScroll() (method)
  - Ext.Net.ComponentBase.SetAutoScroll(bool) (method)
  - Ext.Net.Notification: AutoScroll renamed to Scrollable (property)
  - Ext.Net.Portal.AutoScroll (property)
  - extnet/Ext.NET#1658
- Ext.Net.AbstractStore.AddFiler(DataFilterCollection) (method)
  extnet/Ext.NET#1659
- Ext.Net.ModelField.IsComplex property
  extnet/Ext.NET#1660
- Ext.Net.DrawContainer.DefaultDownloadServerUrl (property)
  extnet/Ext.NET#1506
- Ext.Net.CompositeSprite.Add(AbstractSprite) (method),
  extnet/Ext.NET#1508
- Ext.Net.CompositeSprite.AddAll(IEnumerable<AbstractSprite>) (method),
  extnet/Ext.NET#1508
- Ext.Net.Field.FormatText (property), extnet/Ext.NET#1661
- Ext.Net.FieldSet.CheckboxName (property), extnet/Ext.NET#1662
- Ext.Net.ImageBase.SetAltText(string) (method), extnet/Ext.NET#1663
- Ext.Net.TextFieldBase.Size (property), extnet/Ext.NET#1664
- Ext.Net.BufferedRenderer (class), extnet/Ext.NET#1665
- Ext.Net.DatePicker.DayNames (property), extnet/Ext.NET#1666
- Ext.Net.DatePicker.MonthNames (property), extnet/Ext.NET#1666
- Ext.Net.DataViewDragSelector.RespectPointerEvents = false (property's
  default value), extnet/Ext.NET#1667

**Comment by fabriciomurta** [comment]
All known obsolete references (and a few more) were removed. Each with their own issue. The legacy references won't work in Ext.NET 5 anymore.
