### ISSUE TITLE
Text doesn't appear within Radar chart

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#141]
http://forums.ext.net/showthread.php?23288-Text-doesn-t-appear-within-Radar-chart

http://www.sencha.com/forum/showthread.php?255299-4.2.0.265-Radar-chart-doesn-t-work-correctly-with-remote-data

DUP
http://forums.ext.net/showthread.php?23556

**Update:** Sencha issue _EXTJS-8432_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8432_ allegedly fixed in ExtJS 4.2.3 release.
