### ISSUE TITLE
Drag&Drop (Portal, TabReorderer) causes IE9 hidding if IE9 has single tab

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#154]
http://forums.ext.net/showthread.php?23564
http://www.sencha.com/forum/showthread.php?256909

**Update:** Sencha issue _EXTJS-8763_ allegedly fixed in ExtJS 4.2.0.663 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8763_ allegedly fixed in ExtJS 4.2.0.663 release.
