### ISSUE TITLE
GridPanel + IE: scrollbar jumps to beginning on select in unlocked area

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#158]
http://forums.ext.net/showthread.php?23762
http://www.sencha.com/forum/showthread.php?257927

Duplicate or related:
http://forums.ext.net/showthread.php?46311

**Update:** Sencha issue _EXTJS-8975_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8975_ allegedly fixed in ExtJS 4.2.2.1144 release.
