### ISSUE TITLE
JS TypeError while enabling components

### ISSUE THREAD

**Issue by ggrote** [extnet/Ext.NET#1644]
Versions: Ext.NET 4.8.1, ExtJS 6.7.0, Firefox 67.0

setDisabled(false) throws Exception TypeError: child is null in Firefox when enabling components.
Stacktrace:
        activateFocusable
        onFocusableChildEnable
        enable
        setDisabled

`        activateFocusable: function(child) {
            child.setTabIndex(this.activeChildTabIndex);
        },`

child is null because onFocusableChildEnable gets active component which is null:
`                active = Ext.ComponentManager.getActiveComponent();
                me.clearFocusables();
                me.activateFocusable(active);`

Error only occurs in Firefox, Chrome is working fine.

**Comment by fabriciomurta** [comment]
What would be the scenario you reproduced this in? Any test case you can share?

**Comment by fabriciomurta** [comment]
It's been a long time we asked feedback on how to reproduce this issue and no response, so we're closing and marking this as invalid. Everybody is welcome to post here if there's a means to reproduce the issue available.
