### ISSUE TITLE
TabCloseMenu: onHideMenu override breaking intended behavior

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1681]
Found: 5.0.0, 4.8.3
Ext.NET Thread: [post #8 in TabCloseMenu plugin - issue with icons and events](https://forums.ext.net/showthread.php?62695&p=285017&viewfull=1#post285017)

In 5.0.0 and 4.8.3 release, some overrides to the `TabCloseMenu` component were restored (issue #1648). They were removed during Ext.NET 4.2.2 development (issue #1488).

It was not noticed in #1648 though, that the `onHideMenu()` override which has been in Ext.NET since early commits to SVN, introduced an issue to the very function of the plug in: the **close other tabs** closed all tabs, and the **close** one, closed none.

It was noted in issue #1648 that the `me.item` being unset was affecting the menu's highlighted item. The highlight effect was retained between calls, reportedly. This was not reproducible now, though, so it seems safe to be removed (the whole override for `Ext.ux.TabCloseMenu.onHideMenu()`).

**Comment by fabriciomurta** [comment]
Fixed for both 4.8.3 and 5.0.0 branches. With the override removed, the correct behavior of the plug in was re-established.

**Comment by ggrote** [comment]
The nuget Version 4.8.3 does not include the fix.
It is still on Github Issue #1648:

`// @source: tabClosemenu/TabCloseMenu-overrides.js

Ext.define('gh1648', {
    override: 'Ext.ux.TabCloseMenu',

.....

    onHideMenu: function() {
        var me = this;

        me.item = null;
        me.fireEvent('aftermenu', me.menu, me);
    },`
