### ISSUE TITLE
absent: ext-container's Defaults inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1695]
The `ext-container`'s `Defaults` inner property is not expanded by TagHelpers and no `defaults: ` client-side property gets emitted to the generated JavaScript.

Sample usage here: [buttons/basic/default_button/index.cshtml#L20-L22](https://github.com/objectdotnet/ext7-sandbox/blob/cbeb52a69005c73469f60753d1afa2729b9c5da7/ExtNetCore7-20200325/Pages/examples/buttons/basic/default_button/index.cshtml#L20-L22)

**Expected client-side output:**
```js
Ext.create("Ext.container.Container", {
    height: 900,
    id: "ctl01",
    renderTo: "App.ctl01_Container",
    items: [...],
    layout: "vbox"
});
```

**Actual client-side output:**
```js
Ext.create("Ext.container.Container", {
    height: 900,
    defaults: [
        margin: "0 0 24 0"
    ],
    id: "ctl01",
    renderTo: "App.ctl01_Container",
    items: [...],
    layout: "vbox"
});
```

**Comment by fabriciomurta** [comment]
Another sample at: [buttons/basic/segmentedbutton/index.cshtml#L91-L94](https://github.com/objectdotnet/ext7-sandbox/blob/05fe636e73b8fe86669de01cefbbca843069068d/ExtNetCore7-20200325/Pages/examples/buttons/basic/segmentedbutton/index.cshtml#L91-L94)

**Comment by fabriciomurta** [comment]
The implementation of `<defaults />` in **7.0.0-preview4-2020-07-13** does not allow a string like `"0 1 2 3"` (space-delimited numbers) in its `value` property.

This probably means it should always be (when wanted as a string) to be used as `valueAsString`. But this does not really make sense when there's the `mode="Auto|Raw|Value"`. In this case I'd say it should rather a `valueAsObject` instead.

This is how a direct conversion from WebForms would look like:

**original**
```xml
<Defaults>
    <ext:Parameter Name="margin" Value="0 0 24 0" Mode="Value" />
</Defaults>
```

**simple conversion**
```xml
<defaults>
    <key name="margin" value="0 0 24 0" mode="Value" />
</defaults>
```
(the above doesn't work)

**current workaround**
```
<defaults>
    <key name="margin" valueAsString="0 0 24 0" mode="Value" />
</defaults>
```

This suggests that `mode` may only have a meaning when `valueAsString` and not `value` is used. `value`, which is an object, probably should always be treated as `mode="Raw"`. So maybe in this case the string representation should be favored.

**Comment by geoffreymcgill** [comment]
The `<defaults>` property is working now. 

Both the following scenarios are emitting the correct config:

```cshtml
<ext-panel title="Defaults">
    <defaults>
        <ext-parameter name="margin" valueAsString="50 100 50 100" />
    </defaults> 
    <items>
        <ext-button text="Button 1" />
        <ext-button text="Button 2" />
        <ext-button text="Button 3" />
    </items>
</ext-panel>
```

```cshtml
<ext-panel title="Defaults">
    <defaults>
        <ext-parameter name="margin" value="50" />
    </defaults> 
    <items>
        <ext-button text="Button 1" />
        <ext-button text="Button 2" />
        <ext-button text="Button 3" />
    </items>
</ext-panel>
```
