### ISSUE TITLE
broken: ext-menuitem Icon property generates invalid link/URL

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1696]
Typing anything within `ext-menuitem`'s `Icon` property will lead to an invalid request to the icon name's address.

For instance, a page referencing the *Add* icon, running at *http://localhost/myPage* will attempt to fetch the icon from *http://localhost/myPage/Add*.

This can be seen here:
https://github.com/objectdotnet/ext7-sandbox/blob/c320c95e977645153920cf205331a84592c9442f/ExtNetCore7-20200325/Pages/examples/buttons/basic/hyperlinkbutton/index.cshtml#L36-L37

```xml
<ext-menuitem Text="Add" _Icon="Add" /> 
<ext-menuitem Text="Remove" _Icon="Delete" /> 
```

The references are left as `_Icon` to allow the page to run without errors.

Currently Ext.NET links all resources from CDN then, for a start here, maybe it could link to the respective CDN resource.

**Expected client-side output**
Ext.NET 5.1.0 output
```js
items: [{
    iconCls: "#Add",
    text: "Add"
}, {
    iconCls: "#Delete",
    text: "Remove"
}]
```

**Actual client-side output**
```js
items: [{
    xtype: "menuitem",
    icon: "Add",
    text: "Add"
}, {
    xtype: "menuitem",
    icon: "Delete",
    text: "Remove"
}]
```

Some points to consider:
- The currently pulled CSS resource should ensure the resolved CSS classes works.
- In Ext.NET the icon is chosen from an Enum, which ensures a valid CSS class should be used.
- There should also be a means to provide the Icon string, allowing a (relative) path to a gif/png/jpg to be used as icon.

**Comment by fabriciomurta** [comment]
This also happens with [`ext-button` component in the Buttons > Basic > Overview example](https://github.com/objectdotnet/ext7-sandbox/blob/04b9618e95e849678bde58b469bc4466aa450fbf/ExtNetCore7-20200325/Pages/examples/buttons/basic/overview/index.cshtml#L39).

**Comment by geoffreymcgill** [comment]
The recommended approach for setting an icon in Ext.NET Classic 7.0.0 is using the `IconCls` property and selecting one of the 1300+ [Material icons](https://material.io/resources/icons/?icon=compare_arrows&style=round).

The `IconCls` pattern to specify a Material icon is `x-md md-icon-<icon-name>` where `<icon-name` is the Material icon name with underscores (`_`) replaced with dashes (`-`).

For example, using the icon `check_circle` would be specified as `x-md md-icon-check-circle`.

#### Example

```cshtml
<ext-panel
    title="Defaults"
    width="360"
    height="180"
    iconCls="x-md md-icon-favorite">
</ext-panel>
```

**Comment by geoffreymcgill** [comment]
Currently, Ext.NET Classic will not be supporting the Legacy `Icon` property, although it may be included in the future.
