### ISSUE TITLE
absent: ext-button's OnClientClick property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1698]
The `ext-button` component's `OnClientClick` shorthand for the `Click` listener is missing. It is defined in Ext.NET 5.1.0's `Ext.Net.ButtonBase` class.

[objectdotnet/ext7-sandbox:buttons/basic/default_button/index.cshtml#L34](https://github.com/objectdotnet/ext7-sandbox/blob/cbeb52a69005c73469f60753d1afa2729b9c5da7/ExtNetCore7-20200325/Pages/examples/buttons/basic/default_button/index.cshtml#L34)
```xml
<ext-button Text="Button2" OnClientClick="Ext.Msg.alert('ENTER', 'ENTER is intercepted by Button2');" />
```

**Expected client-side output:**
```js
{
    id: "ctl13",
    handler: function(item, e) {
        Ext.Msg.alert('ENTER', 'ENTER is intercepted by Button2');
    },
    text: "Button2"
}
```

**Actual client-side output:**
```js
{
    xtype: "button",
    text: "Button2"
}
```

Notice due to the context (`Buttons` block within `FormPanel` the `xtype: "button"` is not necessary and not used in current Ext.NET implementation. But it is not necessarily an error, just an extra line that could have been suppressed.

**Comment by AndreyChechel** [comment]
Implemented in `7.0.0-preview4`
