### ISSUE TITLE
absent: ext-panel's BottomBar inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1706]
[buttons/basic/overview/index.cshtml#L87-L94](https://github.com/objectdotnet/ext7-sandbox/blob/04b9618e95e849678bde58b469bc4466aa450fbf/ExtNetCore7-20200325/Pages/examples/buttons/basic/overview/index.cshtml#L87-L94)

Notes:
- In the pointed example, fixing #1705 would be required in order to be able to reproduce the issue.

**Comment by geoffreymcgill** [comment]
Can you try with using `bbar` property. In Ext.NET Legacy, we expanded the terms to `BottomBar`, but for Ext.NET Classic we're going to stick with the native names, such as `bbar`, `tbar`, etc.

**Comment by geoffreymcgill** [comment]
Please use `bbar`
