### ISSUE TITLE
absent: ext-cyclebutton's Menu inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1710]
[buttons/basic/overview/index.cshtml#L103-L110](https://github.com/objectdotnet/ext7-sandbox/blob/04b9618e95e849678bde58b469bc4466aa450fbf/ExtNetCore7-20200325/Pages/examples/buttons/basic/overview/index.cshtml#L103-L110)

Notes
- Without this, the cycle button is pretty much useless, so can't further test the component before this is fixed.

**Comment by geoffreymcgill** [comment]
Inner `<menu>` is now working correctly as of the latest `-preview1` build.
