### ISSUE TITLE
absent: ext-segmentedbutton's Values property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1714]
[buttons/basic/segmentedbutton/index.cshtml#L35](https://github.com/objectdotnet/ext7-sandbox/blob/05fe636e73b8fe86669de01cefbbca843069068d/ExtNetCore7-20200325/Pages/examples/buttons/basic/segmentedbutton/index.cshtml#L35)

Notes:
- Accepted value in Ext.NET WebForms is a string of comma-delimited values, e.g. `"0, 1, 2"`. MVC probably requires an array of integers (`new int[] { 0, 1, 2 }`).

**Comment by AndreyChechel** [comment]
The suggestion is correct. Array of numbers should be provided for multiple selection. Also the property name was revised to `Value`.

## Actual

```cshtml
<ext-segmentedbutton AllowMultiple="true" Values="0,2">
```

## Revised

```cshtml
<ext-segmentedbutton AllowMultiple="true" Value="new double[] { 0, 2 }">
```
