### ISSUE TITLE
broken: ext-combobox's Triggers inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1716]
In an `ext-combobox`, a `<Triggers />` block won't include other `ext-` tag helpers as inner components. Currently Ext.NET 5 accepts only and only the `Ext.Net.FieldTrigger` component as items within its version of the combo box's `Triggers` block.

Attempted to be used at [form/combobox/triggerbuttons/index.cshtml#L25-L27](https://github.com/objectdotnet/ext7-sandbox/blob/cfe07292c29cbc3cf40fa70d60fe80374bfe56e6/ExtNetCore7-20200325/Pages/examples/form/combobox/triggerbuttons/index.cshtml#L25-L27).

Nothing is output in the client init script.

Following, how [the feature is used in Ext.NET 5](https://examples5.ext.net/Examples/Form/ComboBox/TriggerButtons/Default.aspx):

**from**
```xml
<Triggers>
    <ext:FieldTrigger Icon="Clear" Hidden="true" Weight="-1" />
</Triggers>
```

**being translated to this client init script code**
```js
triggers: {
    "_trigger1": {
        hidden: true,
        weight: -1,
        tag: "_trigger1",
        cls: Ext.form.trigger.Trigger.getIcon("Clear")
    }
}
```

**Comment by AndreyChechel** [comment]
Fixed in `7.2.0`
