### ISSUE TITLE
Remove all instance of "Layout" suffix from Examples Explorer samples

### ISSUE THREAD

**Issue by geoffreymcgill** [extnet/Ext.NET#1718]
The `Layout` suffix is not required when setting the `Layout` properties. For instance, `Layout="BorderLayout"` can be revised to `Layout="Border"`. There are other samples where the `*Layout` suffix is applied and can be removed. 

```
// Existing
Layout="BorderLayout"

// Revised
Layout="Border"
```

**Comment by fabriciomurta** [comment]
The changes are now live in EE both [examples.ext.net](https://examples.ext.net/) and [examples5.ext.net](https://examples5.ext.net/).

No `.cs` file affected by the change, so DLL re-publication was not necessary. No change needed in Ext.NET 5, so no version bumping was also necessary.
