### ISSUE TITLE
broken: ext-window component is hidden by default

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1719]
If an `ext-window` is defined and the `hidden` property not defined, it is not shown up in the rendered page.

This is reproduced here: [form/datefield/from-to_range/index.cshtml#L18](https://github.com/objectdotnet/ext7-sandbox/blob/4d9fb1ced6932314a16b911eeeb435c28908a967/ExtNetCore7-20200325/Pages/examples/form/datefield/from-to_range/index.cshtml#L18)

Ext.NET 5 handles windows (except if `hidden` is explicitly `false`) as:

```js
Ext.onReady(function(){new Ext.window.Window({ ... }).show();
```

In Ext.Net Core, specifying `hidden="true"` in markup (tag helpers) makes the window show up on load.

Maybe it would be best to have an override to make windows show up by default instead of having server-side code emit windows differently than other components -- or adopting the new behavior.

**Comment by geoffreymcgill** [comment]
For now, the decision is to stay with the default Ext JS functionality of _not_ showing the Window by default. Developers must explicitly call `.Show()` or set `Hidden = false`.
