### ISSUE TITLE
absent: ext-objectholder component

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1722]
The component is used at [form/combobox/overview/index.cshtml#L82](https://github.com/objectdotnet/ext7-sandbox/blob/3b7ed09f9961e362005bf88dbaca37aac50eeb7c/ExtNetCore7-20200325/Pages/examples/form/combobox/overview/index.cshtml#L82)

It is not clear the use it has to Ext.NET by the example alone, it does not make client-side init script code at all, and all that's been noted it does is output the following to the document's DOM:

```xml
<div id="App.DataHolder_Container"></div>
```

This component is likely a leftover from very old Ext.NET versions that is no longer used.

**Comment by geoffreymcgill** [comment]
We will not be porting this component to Ext.NET 7.x as the purpose is not clear. 

### See also

- #1782
