### ISSUE TITLE
absent: ext-combobox's TriggerClick listener / direct event

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1727]
This is an undocumented feature in Ext JS. Probably they forgot to add jsdoc comments.

The main reference can be found at `Ext.form.field.Text` which combo boxes extend, at [classic/src/Text.js:1505](https://docs.sencha.com/extjs/7.1.0/classic/src/Text.js.html#line1505), then other references to the event being wired up can be found elsewhere in the same javascript source.

This feature is explored at [form/combobox/triggerbuttons/index.cshtml#L35-L38](https://github.com/objectdotnet/ext7-sandbox/blob/3b7ed09f9961e362005bf88dbaca37aac50eeb7c/ExtNetCore7-20200325/Pages/examples/form/combobox/triggerbuttons/index.cshtml#L35-L38).

**Comment by AndreyChechel** [comment]
Implemented in `7.2.0`
