### ISSUE TITLE
absent: ext-combobox Editable boolean property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1728]
This is included in Ext JS 7.1.0 documentation: [Ext.form.field.Combobox.editable config option](https://docs.sencha.com/extjs/7.1.0/classic/Ext.form.field.ComboBox.html#cfg-editable)

Reproduced at: [form/combobox/ajax_linked_combos/index.cshtml#L17](https://github.com/objectdotnet/ext7-sandbox/blob/2bc082a1058b5c680434abd4eca7b9f9fce12a68/ExtNetCore7-20200325/Pages/examples/form/combobox/ajax_linked_combos/index.cshtml#L17)

**Comment by geoffreymcgill** [comment]
Thanks for this report. For some reason, the `Editable` property did not make it into the parent **PickerField** component. We are investigating.

**Comment by fabriciomurta** [comment]
It is _also_ defined in `Ext.form.field.Picker`'s parent [Ext.form.field.Text](https://docs.sencha.com/extjs/7.1.0/classic/Ext.form.field.Text.html#cfg-editable) class.

**Comment by geoffreymcgill** [comment]
This has been fixed in the latest build and will be available with the next NuGet package.
