### ISSUE TITLE
absent: ext-store's ID string property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1730]
Store IDs are used to reference standalone stores from different components. In Ext.NET, a store can be attached to one or more components via the component's StoreID property. It is output as `store: "Store1"` if the specified value is `StoreID="Store1"` in a panel, combobox, or chart; as long as it supports the `store` config option. This is also valid to MVC's `.StoreID("Store1")`.

Reproduced at: [form/combobox/ajax_linked_combos/index.cshtml#L67](https://github.com/objectdotnet/ext7-sandbox/blob/2bc082a1058b5c680434abd4eca7b9f9fce12a68/ExtNetCore7-20200325/Pages/examples/form/combobox/ajax_linked_combos/index.cshtml#L67)

#### WebForms
1. [Associations > HasMany > Simple](https://examples5.ext.net/#/Associations/HasMany/Simple/)
2. [Associations > HasOne > Simple](https://examples5.ext.net/#/Associations/HasOne/Simple/)
3. [Associations > HasOne > Simple_Lazy_Load](https://examples5.ext.net/#/Associations/HasOne/Simple_Lazy_Load/)
4. [Calendar > Overview > Basic](https://examples5.ext.net/#/Calendar/Overview/Basic/)
5. [Calendar > Overview > Remote_Data](https://examples5.ext.net/#/Calendar/Overview/Remote_Data/)
6. [Chart > Area > Basic](https://examples5.ext.net/#/Chart/Area/Basic/)
7. [Chart > Column > Stacked](https://examples5.ext.net/#/Chart/Column/Stacked/)
8. [Chart > Column > Stacked_100](https://examples5.ext.net/#/Chart/Column/Stacked_100/)
9. [Chart > Combination > Dashboard](https://examples5.ext.net/#/Chart/Combination/Dashboard/)
10. [Chart > Combination > Infographic](https://examples5.ext.net/#/Chart/Combination/Infographic/)
11. [Chart > Combination > Infographic](https://examples5.ext.net/#/Chart/Combination/Infographic/)
12. [Chart > Combination > Pareto](https://examples5.ext.net/#/Chart/Combination/Pareto/)
13. [Chart > Gauge > Basic_2](https://examples5.ext.net/#/Chart/Gauge/Basic_2/)
14. [Combination_Samples > Applications > Word_Wrench](https://examples5.ext.net/#/Combination_Samples/Applications/Word_Wrench/)
15. [DataView > Basic > Overview](https://examples5.ext.net/#/DataView/Basic/Overview/)
16. [DataView > Basic > With_Paging](https://examples5.ext.net/#/DataView/Basic/With_Paging/)
17. [DataView > ComponentView > Editor](https://examples5.ext.net/#/DataView/ComponentView/Editor/)
18. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
19. [Form > ComboBox > Linked_ComboBoxes](https://examples5.ext.net/#/Form/ComboBox/Linked_ComboBoxes/)
20. [Form > ComboBox > Linked_Combos_In_Grid](https://examples5.ext.net/#/Form/ComboBox/Linked_Combos_In_Grid/)
21. [Form > Miscellaneous > Checkout_Form](https://examples5.ext.net/#/Form/Miscellaneous/Checkout_Form/)
22. [Form > Miscellaneous > Custom_Form](https://examples5.ext.net/#/Form/Miscellaneous/Custom_Form/)
23. [Form > Miscellaneous > Edit_Form_View](https://examples5.ext.net/#/Form/Miscellaneous/Edit_Form_View/)
24. [Form > Miscellaneous > Form_View](https://examples5.ext.net/#/Form/Miscellaneous/Form_View/)
25. [Form > Triggers > Trigger_with_Dialog_Editor](https://examples5.ext.net/#/Form/Triggers/Trigger_with_Dialog_Editor/)
26. [GridPanel > Commands > Prepare_Commands](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Commands/)
27. [GridPanel > Commands > Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Row_Command/)
28. [GridPanel > Data_Presentation > Editor_Field_Mapping](https://examples5.ext.net/#/GridPanel/Data_Presentation/Editor_Field_Mapping/)
29. [GridPanel > Data_Presentation > MultiCombo_Map](https://examples5.ext.net/#/GridPanel/Data_Presentation/MultiCombo_Map/)
30. [GridPanel > FilterHeader > Mapped_Field_Filtering](https://examples5.ext.net/#/GridPanel/FilterHeader/Mapped_Field_Filtering/)
31. [GridPanel > Miscellaneous > Custom_Column](https://examples5.ext.net/#/GridPanel/Miscellaneous/Custom_Column/)
32. [GridPanel > Miscellaneous > Details_Window_Remote](https://examples5.ext.net/#/GridPanel/Miscellaneous/Details_Window_Remote/)
33. [GridPanel > Miscellaneous > Export_Data_Ajax](https://examples5.ext.net/#/GridPanel/Miscellaneous/Export_Data_Ajax/)
34. [GridPanel > Miscellaneous > Export_Data_PostBack](https://examples5.ext.net/#/GridPanel/Miscellaneous/Export_Data_PostBack/)
35. [GridPanel > Miscellaneous > Generic_List](https://examples5.ext.net/#/GridPanel/Miscellaneous/Generic_List/)
36. [GridPanel > Miscellaneous > Submit_Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Submit_Two_Grids/)
37. [GridPanel > Miscellaneous > Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Two_Grids/)
38. [GridPanel > Miscellaneous > Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Two_Grids/)
39. [GridPanel > Plugins > GroupingSummary](https://examples5.ext.net/#/GridPanel/Plugins/GroupingSummary/)
40. [GridPanel > Plugins > Selection_Memory](https://examples5.ext.net/#/GridPanel/Plugins/Selection_Memory/)
41. [GridPanel > Plugins > SlidingPager](https://examples5.ext.net/#/GridPanel/Plugins/SlidingPager/)
42. [GridPanel > Selection_Models > Cell_Selection](https://examples5.ext.net/#/GridPanel/Selection_Models/Cell_Selection/)
43. [GridPanel > Selection_Models > Row_Selection](https://examples5.ext.net/#/GridPanel/Selection_Models/Row_Selection/)
44. [GridPanel > Selection_Models > Submitting_Values](https://examples5.ext.net/#/GridPanel/Selection_Models/Submitting_Values/)
45. [GridPanel > Spreadsheet > Initial_Selection](https://examples5.ext.net/#/GridPanel/Spreadsheet/Initial_Selection/)
46. [GridPanel > System.Data > DataReader](https://examples5.ext.net/#/GridPanel/System.Data/DataReader/)
47. [GridPanel > System.Data > DataTable](https://examples5.ext.net/#/GridPanel/System.Data/DataTable/)
48. [GridPanel > Update > AutoSave](https://examples5.ext.net/#/GridPanel/Update/AutoSave/)
49. [GridPanel > Update > Batch](https://examples5.ext.net/#/GridPanel/Update/Batch/)
50. [GridPanel > Update > SqlDataSource](https://examples5.ext.net/#/GridPanel/Update/SqlDataSource/)
51. [Kitchen_Sink > TreePanels > Basic_TreePanel](https://examples5.ext.net/#/Kitchen_Sink/TreePanels/Basic_TreePanel/)
52. [Miscellaneous > Bin_HtmlBin > Overview](https://examples5.ext.net/#/Miscellaneous/Bin_HtmlBin/Overview/)

#### MVC
1. [Associations > HasMany > Simple](https://mvc5.ext.net/#/Associations_HasMany/Simple/)
2. [Associations > HasOne > Simple](https://mvc5.ext.net/#/Associations_HasOne/Simple/)
3. [Associations > HasOne > Simple_Lazy_Load](https://mvc5.ext.net/#/Associations_HasOne/Simple_Lazy_Load/)
4. [Calendar > Overview > Basic](https://mvc5.ext.net/#/Calendar_Overview/Basic/)
5. [Calendar > Overview > Remote_Data](https://mvc5.ext.net/#/Calendar_Overview/Remote_Data/)
6. [Chart > Area > Basic](https://mvc5.ext.net/#/Chart_Area/Basic/)
11. [DataView > Basic > Paging](https://mvc5.ext.net/#/DataView_Basic/Paging/)
12. [Desktop > Overview](https://mvc5.ext.net/#/Desktop/Overview/)
13. [Form > ComboBox > Linked_Combos_In_Grid](https://mvc5.ext.net/#/Form_ComboBox/Linked_Combos_In_Grid/)
14. [GridPanel > Commands > Row_Command](https://mvc5.ext.net/#/GridPanel_Commands/Row_Command/)
15. [GridPanel > Data_Presentation > Editor_Field_Mapping](https://mvc5.ext.net/#/GridPanel_Data_Presentation/Editor_Field_Mapping/)
16. [Kitchen > Sink_TreePanels > Basic](https://mvc5.ext.net/#/Kitchen_Sink_TreePanels/Basic/)
17. [Portal > Complex](https://mvc5.ext.net/#/Portal/Complex/)

**Comment by AndreyChechel** [comment]
Implemented in `7.0.0`
