### ISSUE TITLE
absent: ext-gridpanel's ColumnModel inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1733]
Very often Grid Panels (and tree grids) are built using this syntax. This can probably be dropped for simplicity, but there may be a reason this was required in Ext.NET down to 5.x.

Reproduced at [gridpanel/arraygrid/simple/index.cshtml#L82-L97](https://github.com/objectdotnet/ext7-sandbox/blob/93c311202563c66262e232cb07a256f5ed7b54a6/ExtNetCore7-20200325/Pages/examples/gridpanel/arraygrid/simple/index.cshtml#L82-L97).

#### WebForms (`<ColumnModel>`)

1. [Action > Basic > Grid](https://examples5.ext.net/#/Action/Basic/Grid/)
2. [Associations > HasMany > Lazy_Load](https://examples5.ext.net/#/Associations/HasMany/Lazy_Load/)
3. [Associations > HasMany > Lazy_Load](https://examples5.ext.net/#/Associations/HasMany/Lazy_Load/)
4. [Associations > HasMany > Lazy_Load](https://examples5.ext.net/#/Associations/HasMany/Lazy_Load/)
5. [Associations > HasMany > Simple](https://examples5.ext.net/#/Associations/HasMany/Simple/)
6. [Associations > HasOne > Simple](https://examples5.ext.net/#/Associations/HasOne/Simple/)
7. [Associations > HasOne > Simple_Lazy_Load](https://examples5.ext.net/#/Associations/HasOne/Simple_Lazy_Load/)
8. [Chart > Area > Basic](https://examples5.ext.net/#/Chart/Area/Basic/)
9. [Chart > Column > Stacked](https://examples5.ext.net/#/Chart/Column/Stacked/)
10. [Chart > Column > Stacked_100](https://examples5.ext.net/#/Chart/Column/Stacked_100/)
11. [Chart > Combination > Dashboard](https://examples5.ext.net/#/Chart/Combination/Dashboard/)
12. [Chart > Combination > Pareto](https://examples5.ext.net/#/Chart/Combination/Pareto/)
13. [Chart > Misc > ToolTips](https://examples5.ext.net/#/Chart/Misc/ToolTips/)
14. [ColorPicker > Advanced > GridPanel](https://examples5.ext.net/#/ColorPicker/Advanced/GridPanel/)
15. [Combination_Samples > Applications > Feed_Viewer](https://examples5.ext.net/#/Combination_Samples/Applications/Feed_Viewer/)
16. [Combination_Samples > Applications > Word_Wrench](https://examples5.ext.net/#/Combination_Samples/Applications/Word_Wrench/)
17. [Data_Binding > Basic > Associations](https://examples5.ext.net/#/Data_Binding/Basic/Associations/)
18. [Data_Binding > Basic > Chaining_Selection](https://examples5.ext.net/#/Data_Binding/Basic/Chaining_Selection/)
19. [Data_Binding > Basic > Chaining_Stores](https://examples5.ext.net/#/Data_Binding/Basic/Chaining_Stores/)
20. [Data_Binding > Basic > Isolated_Child_Sessions](https://examples5.ext.net/#/Data_Binding/Basic/Isolated_Child_Sessions/)
21. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
22. [DragDrop > Advanced > Example3](https://examples5.ext.net/#/DragDrop/Advanced/Example3/)
23. [DragDrop > Grid > Grid_to_FormPanel](https://examples5.ext.net/#/DragDrop/Grid/Grid_to_FormPanel/)
24. [DragDrop > Grid > Grid_to_Grid](https://examples5.ext.net/#/DragDrop/Grid/Grid_to_Grid/)
25. [DragDrop > Grid > Rows_Reordering](https://examples5.ext.net/#/DragDrop/Grid/Rows_Reordering/)
26. [Form > ComboBox > Linked_Combos_In_Grid](https://examples5.ext.net/#/Form/ComboBox/Linked_Combos_In_Grid/)
27. [GridPanel > ArrayGrid > ForceFit](https://examples5.ext.net/#/GridPanel/ArrayGrid/ForceFit/)
28. [GridPanel > ArrayGrid > Simple](https://examples5.ext.net/#/GridPanel/ArrayGrid/Simple/)
29. [GridPanel > ColumnModel > TagColumn](https://examples5.ext.net/#/GridPanel/ColumnModel/TagColumn/)
30. [GridPanel > Data_Presentation > Meta_config](https://examples5.ext.net/#/GridPanel/Data_Presentation/Meta_config/)
31. [GridPanel > Data_Presentation > Meta_config_with_handler](https://examples5.ext.net/#/GridPanel/Data_Presentation/Meta_config_with_handler/)
32. [GridPanel > Data_with_Details > Binding](https://examples5.ext.net/#/GridPanel/Data_with_Details/Binding/)
33. [GridPanel > Infinite_Scrolling > Tuner](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Tuner/)
34. [GridPanel > List_View > Overview](https://examples5.ext.net/#/GridPanel/List_View/Overview/)
35. [GridPanel > Locking_Grid > Cell_Editing](https://examples5.ext.net/#/GridPanel/Locking_Grid/Cell_Editing/)
36. [GridPanel > Locking_Grid > Simple](https://examples5.ext.net/#/GridPanel/Locking_Grid/Simple/)
37. [GridPanel > Miscellaneous > FilterQuery](https://examples5.ext.net/#/GridPanel/Miscellaneous/FilterQuery/)
38. [GridPanel > Miscellaneous > XML_File_Loading_Custom](https://examples5.ext.net/#/GridPanel/Miscellaneous/XML_File_Loading_Custom/)
39. [GridPanel > Plugins > LiveSearch](https://examples5.ext.net/#/GridPanel/Plugins/LiveSearch/)
40. [GridPanel > Plugins > RowEditor](https://examples5.ext.net/#/GridPanel/Plugins/RowEditor/)
41. [GridPanel > Plugins > RowEditor_Remote](https://examples5.ext.net/#/GridPanel/Plugins/RowEditor_Remote/)
42. [GridPanel > Restful > Overview](https://examples5.ext.net/#/GridPanel/Restful/Overview/)
43. [GridPanel > Spreadsheet > Clipboard](https://examples5.ext.net/#/GridPanel/Spreadsheet/Clipboard/)
44. [GridPanel > Spreadsheet > Initial_Selection](https://examples5.ext.net/#/GridPanel/Spreadsheet/Initial_Selection/)
45. [GridPanel > Spreadsheet > Locking](https://examples5.ext.net/#/GridPanel/Spreadsheet/Locking/)
46. [GridPanel > Spreadsheet > Overview](https://examples5.ext.net/#/GridPanel/Spreadsheet/Overview/)
47. [GridPanel > Spreadsheet > Select_Programmatically](https://examples5.ext.net/#/GridPanel/Spreadsheet/Select_Programmatically/)
48. [GridPanel > Spreadsheet > Submit](https://examples5.ext.net/#/GridPanel/Spreadsheet/Submit/)
49. [GridPanel > Update > AutoSave](https://examples5.ext.net/#/GridPanel/Update/AutoSave/)
50. [GridPanel > Update > Batch](https://examples5.ext.net/#/GridPanel/Update/Batch/)
51. [MessageBox > Callout > Delegation](https://examples5.ext.net/#/MessageBox/Callout/Delegation/)
52. [Miscellaneous > Store > ClientStore](https://examples5.ext.net/#/Miscellaneous/Store/ClientStore/)
53. [TreePanel > Advanced > Buffer_Rendered_TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/Buffer_Rendered_TreeGrid/)
54. [TreePanel > Advanced > Command_Column](https://examples5.ext.net/#/TreePanel/Advanced/Command_Column/)
55. [TreePanel > Advanced > Component_Column](https://examples5.ext.net/#/TreePanel/Advanced/Component_Column/)
56. [TreePanel > Advanced > Locking_Buffer_Rendered_TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/Locking_Buffer_Rendered_TreeGrid/)
57. [TreePanel > Advanced > Remote_Mode](https://examples5.ext.net/#/TreePanel/Advanced/Remote_Mode/)
58. [TreePanel > Advanced > TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/TreeGrid/)

#### MVC (`.ColumnModel()`)
1. [Actions > Grid](https://mvc5.ext.net/#/Actions/Grid/)
2. [Associations > HasMany > Simple](https://mvc5.ext.net/#/Associations_HasMany/Simple/)
3. [Associations > HasOne > Simple](https://mvc5.ext.net/#/Associations_HasOne/Simple/)
4. [Associations > HasOne > Simple_Lazy_Load](https://mvc5.ext.net/#/Associations_HasOne/Simple_Lazy_Load/)
5. [Chart > Area > Basic](https://mvc5.ext.net/#/Chart_Area/Basic/)
6. [Chart > Dashboard > Basic](https://mvc5.ext.net/#/Chart_Dashboard/Basic/)
7. [Data > Basic > ModelSerializer](https://mvc5.ext.net/#/Data_Basic/ModelSerializer/)
8. [Desktop > Overview](https://mvc5.ext.net/#/Desktop/Overview/)
9. [DragDrop > Advanced > Example3](https://mvc5.ext.net/#/DragDrop_Advanced/Example3/)
10. [DragDrop > Grid > Cell_to_Cell](https://mvc5.ext.net/#/DragDrop_Grid/Cell_to_Cell/)
11. [DragDrop > Grid > Field_to_Grid](https://mvc5.ext.net/#/DragDrop_Grid/Field_to_Grid/)
12. [DragDrop > Grid > Grid_to_FormPanel](https://mvc5.ext.net/#/DragDrop_Grid/Grid_to_FormPanel/)
13. [Form > ComboBox > Linked_Combos_In_Grid](https://mvc5.ext.net/#/Form_ComboBox/Linked_Combos_In_Grid/)
14. [Form > FormPanel > Basic](https://mvc5.ext.net/#/Form_FormPanel/Basic/)
15. [Getting > Started > Component_Overview](https://mvc5.ext.net/#/Getting_Started/Component_Overview/)
16. [GridPanel > ArrayGrid > ArrayWithPaging](https://mvc5.ext.net/#/GridPanel_ArrayGrid/ArrayWithPaging/)
17. [GridPanel > ArrayGrid > Remote_Load](https://mvc5.ext.net/#/GridPanel_ArrayGrid/Remote_Load/)
18. [GridPanel > ArrayGrid > Simple](https://mvc5.ext.net/#/GridPanel_ArrayGrid/Simple/)
19. [GridPanel > ColumnModel > Ajax_Configuration](https://mvc5.ext.net/#/GridPanel_ColumnModel/Ajax_Configuration/)
20. [GridPanel > ColumnModel > Column_Variations](https://mvc5.ext.net/#/GridPanel_ColumnModel/Column_Variations/)
21. [GridPanel > ColumnModel > HyperlinkColumn](https://mvc5.ext.net/#/GridPanel_ColumnModel/HyperlinkColumn/)
22. [GridPanel > ColumnModel > RatingColumn](https://mvc5.ext.net/#/GridPanel_ColumnModel/RatingColumn/)
23. [GridPanel > Commands > Cell_Command](https://mvc5.ext.net/#/GridPanel_Commands/Cell_Command/)
24. [GridPanel > Commands > Group_Command](https://mvc5.ext.net/#/GridPanel_Commands/Group_Command/)
25. [GridPanel > Commands > Image_Command](https://mvc5.ext.net/#/GridPanel_Commands/Image_Command/)
26. [GridPanel > Commands > Menu_Row_Command](https://mvc5.ext.net/#/GridPanel_Commands/Menu_Row_Command/)
27. [GridPanel > Commands > Over_Commands](https://mvc5.ext.net/#/GridPanel_Commands/Over_Commands/)
28. [GridPanel > Commands > Prepare_Commands](https://mvc5.ext.net/#/GridPanel_Commands/Prepare_Commands/)
29. [GridPanel > Commands > Prepare_Toolbar](https://mvc5.ext.net/#/GridPanel_Commands/Prepare_Toolbar/)
30. [GridPanel > Commands > Row_Command](https://mvc5.ext.net/#/GridPanel_Commands/Row_Command/)
31. [GridPanel > ComponentColumn > Editor](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Editor/)
32. [GridPanel > ComponentColumn > Overview](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Overview/)
33. [GridPanel > ComponentColumn > Over_Editor](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Over_Editor/)
34. [GridPanel > ComponentColumn > Pin_Editor](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Pin_Editor/)
35. [GridPanel > Data_Presentation > Data_Prepare](https://mvc5.ext.net/#/GridPanel_Data_Presentation/Data_Prepare/)
36. [GridPanel > Data_Presentation > Editor_Field_Mapping](https://mvc5.ext.net/#/GridPanel_Data_Presentation/Editor_Field_Mapping/)
37. [GridPanel > Data_Presentation > Field_Converter](https://mvc5.ext.net/#/GridPanel_Data_Presentation/Field_Converter/)
38. [GridPanel > Data_Presentation > Field_Mapping](https://mvc5.ext.net/#/GridPanel_Data_Presentation/Field_Mapping/)
39. [GridPanel > Data_Presentation > Server_Mapping](https://mvc5.ext.net/#/GridPanel_Data_Presentation/Server_Mapping/)
40. [GridPanel > Data_with_Details > Binding](https://mvc5.ext.net/#/GridPanel_Data_with_Details/Binding/)
41. [GridPanel > Editable > Editor_with_DirectMethod](https://mvc5.ext.net/#/GridPanel_Editable/Editor_with_DirectMethod/)
42. [GridPanel > FilterHeader > Overview](https://mvc5.ext.net/#/GridPanel_FilterHeader/Overview/)
43. [GridPanel > Infinite_Scrolling > Buffered_Scrolling](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/)
44. [GridPanel > Infinite_Scrolling > Forum_topics](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Forum_topics/)
45. [GridPanel > Infinite_Scrolling > Overview](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Overview/)
46. [GridPanel > Infinite_Scrolling > Remote_Filter](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Remote_Filter/)
47. [GridPanel > Miscellaneous > FilterQuery](https://mvc5.ext.net/#/GridPanel_Miscellaneous/FilterQuery/)
48. [GridPanel > Miscellaneous > Marking_Records](https://mvc5.ext.net/#/GridPanel_Miscellaneous/Marking_Records/)
49. [GridPanel > MultiHeader > Filter](https://mvc5.ext.net/#/GridPanel_MultiHeader/Filter/)
50. [GridPanel > Paging_and_Sorting > Local](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Local/)
51. [GridPanel > Paging_and_Sorting > Local_Paging_with_Remote_Data](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Local_Paging_with_Remote_Data/)
52. [GridPanel > Paging_and_Sorting > Multiple_Sorting_Local](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Multiple_Sorting_Local/)
53. [GridPanel > Paging_and_Sorting > Remote](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Remote/)
54. [GridPanel > Plugins > CellEditing](https://mvc5.ext.net/#/GridPanel_Plugins/CellEditing/)
55. [GridPanel > Plugins > GridFilters_Local](https://mvc5.ext.net/#/GridPanel_Plugins/GridFilters_Local/)
56. [GridPanel > Plugins > GridFilters_Remote](https://mvc5.ext.net/#/GridPanel_Plugins/GridFilters_Remote/)
57. [GridPanel > Plugins > GroupingSummary](https://mvc5.ext.net/#/GridPanel_Plugins/GroupingSummary/)
58. [GridPanel > RowExpander > Component](https://mvc5.ext.net/#/GridPanel_RowExpander/Component/)
59. [GridPanel > RowExpander > Dynamic_GridPanels](https://mvc5.ext.net/#/GridPanel_RowExpander/Dynamic_GridPanels/)
60. [GridPanel > RowExpander > Dynamic_View](https://mvc5.ext.net/#/GridPanel_RowExpander/Dynamic_View/)
61. [GridPanel > RowExpander > Dynamic_View](https://mvc5.ext.net/#/GridPanel_RowExpander/Dynamic_View/)
62. [GridPanel > RowExpander > Local_Mode](https://mvc5.ext.net/#/GridPanel_RowExpander/Local_Mode/)
63. [GridPanel > RowExpander > Remote_Mode](https://mvc5.ext.net/#/GridPanel_RowExpander/Remote_Mode/)
64. [GridPanel > Selection_Models > Checkbox_Selection](https://mvc5.ext.net/#/GridPanel_Selection_Models/Checkbox_Selection/)
65. [GridPanel > Spreadsheet > Overview](https://mvc5.ext.net/#/GridPanel_Spreadsheet/Overview/)
66. [GridPanel > Spreadsheet > Submit](https://mvc5.ext.net/#/GridPanel_Spreadsheet/Submit/)
67. [GridPanel > Update > AutoSave](https://mvc5.ext.net/#/GridPanel_Update/AutoSave/)
68. [GridPanel > Update > Batch](https://mvc5.ext.net/#/GridPanel_Update/Batch/)
69. [GridPanel > Update > Restful](https://mvc5.ext.net/#/GridPanel_Update/Restful/)
70. [Kitchen > Sink_GridPanels > Basic](https://mvc5.ext.net/#/Kitchen_Sink_GridPanels/Basic/)
71. [Kitchen > Sink_GridPanels > Grouped](https://mvc5.ext.net/#/Kitchen_Sink_GridPanels/Grouped/)
72. [Kitchen > Sink_GridPanels > Grouped_Header](https://mvc5.ext.net/#/Kitchen_Sink_GridPanels/Grouped_Header/)
73. [Kitchen > Sink_GridPanels > Locked](https://mvc5.ext.net/#/Kitchen_Sink_GridPanels/Locked/)
74. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://mvc5.ext.net/#/Miscellaneous_Mouse_Distance_Sensor/Basic/)
75. [Miscellaneous > Store > ClientStore](https://mvc5.ext.net/#/Miscellaneous_Store/ClientStore/)
76. [Models > StoreFor](https://mvc5.ext.net/#/Models/StoreFor/)
77. [Portal > Complex](https://mvc5.ext.net/#/Portal/Complex/)
78. [TreePanel > Advanced > Remote_Mode](https://mvc5.ext.net/#/TreePanel_Advanced/Remote_Mode/)
79. [TreePanel > Advanced > TreeGrid](https://mvc5.ext.net/#/TreePanel_Advanced/TreeGrid/)

**Comment by geoffreymcgill** [comment]
The previous `<ColumnModel>` with nested `<Columns>` is now just `<columns>` inside the Component.

Here's a simple GridPanel sample to demonstrate use of `<columns>` inner configuration:

```csharp
<ext-gridpanel title="Array Grid" width="700" height="350">
    <store>
        <ext-store data="Model.GridData">
            <fields>
                <ext-datafield name="company" />
                <ext-numberdatafield name="price" />
                <ext-numberdatafield name="change" />
                <ext-numberdatafield name="pctChange" />
                <ext-datedatafield name="lastChange" dateFormat="M/d hh:mmtt" />
            </fields>
        </ext-store>
    </store>
    <columns>
        <ext-column text="Company" dataIndex="company" flex="1" />
        <ext-column text="Price" dataIndex="price" renderer="Ext.util.Format.usMoney" />
        <ext-column text="Change" dataIndex="change" renderer="change" />
        <ext-column text="Change" dataIndex="pctChange" renderer="pctChange" />
        <ext-column text="Last Updated" dataIndex="lastChange" width="120" />
    </columns>
</ext-gridpanel>
```
