### ISSUE TITLE
absent: ext-rowselectionmodel component

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1734]
Should be allowed and supported within an `ext-gridpanel`'s `SelectionModel` inner property (#1735).

Reproduced at [gridpanel/arraygrid/simple/index.cshtml#L98](https://github.com/objectdotnet/ext7-sandbox/blob/93c311202563c66262e232cb07a256f5ed7b54a6/ExtNetCore7-20200325/Pages/examples/gridpanel/arraygrid/simple/index.cshtml#L98)

#### WebForms (`<ext:RowSelectionModel runat="server"`)
1. [Action > Basic > Grid](https://examples5.ext.net/#/Action/Basic/Grid/)
2. [ColorPicker > Advanced > GridPanel](https://examples5.ext.net/#/ColorPicker/Advanced/GridPanel/)
3. [DragDrop > Grid > Grid_to_FormPanel](https://examples5.ext.net/#/DragDrop/Grid/Grid_to_FormPanel/)
4. [Form > DropDownField > Overview](https://examples5.ext.net/#/Form/DropDownField/Overview/)
5. [Getting_Started > Introduction > Component_Overview](https://examples5.ext.net/#/Getting_Started/Introduction/Component_Overview/)
6. [GridPanel > ArrayGrid > ArrayWithPaging](https://examples5.ext.net/#/GridPanel/ArrayGrid/ArrayWithPaging/)
7. [GridPanel > ArrayGrid > ForceFit](https://examples5.ext.net/#/GridPanel/ArrayGrid/ForceFit/)
8. [GridPanel > ArrayGrid > Keep_Page_on_Refresh](https://examples5.ext.net/#/GridPanel/ArrayGrid/Keep_Page_on_Refresh/)
9. [GridPanel > ArrayGrid > Remote_Load](https://examples5.ext.net/#/GridPanel/ArrayGrid/Remote_Load/)
10. [GridPanel > ArrayGrid > Simple](https://examples5.ext.net/#/GridPanel/ArrayGrid/Simple/)
11. [GridPanel > ColumnModel > Reconfigure](https://examples5.ext.net/#/GridPanel/ColumnModel/Reconfigure/)
12. [GridPanel > Commands > Cell_Command](https://examples5.ext.net/#/GridPanel/Commands/Cell_Command/)
13. [GridPanel > Commands > Image_Command](https://examples5.ext.net/#/GridPanel/Commands/Image_Command/)
14. [GridPanel > Commands > Menu_Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Menu_Row_Command/)
15. [GridPanel > Commands > Over_Commands](https://examples5.ext.net/#/GridPanel/Commands/Over_Commands/)
16. [GridPanel > Commands > Prepare_Commands](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Commands/)
17. [GridPanel > Commands > Prepare_Toolbar](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Toolbar/)
18. [GridPanel > Commands > Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Row_Command/)
19. [GridPanel > DataSource_Controls > LinqDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/LinqDataSource/)
20. [GridPanel > DataSource_Controls > ObjectDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/ObjectDataSource/)
21. [GridPanel > DataSource_Controls > SqlDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/SqlDataSource/)
22. [GridPanel > Data_Presentation > Grid_and_Store_Reconfigure](https://examples5.ext.net/#/GridPanel/Data_Presentation/Grid_and_Store_Reconfigure/)
23. [GridPanel > Data_with_Details > Form_Details](https://examples5.ext.net/#/GridPanel/Data_with_Details/Form_Details/)
24. [GridPanel > Data_with_Details > One-to-Many](https://examples5.ext.net/#/GridPanel/Data_with_Details/One-to-Many/)
25. [GridPanel > Infinite_Scrolling > Buffered_Scrolling](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Buffered_Scrolling/)
26. [GridPanel > Infinite_Scrolling > Forum_topics](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Forum_topics/)
27. [GridPanel > Infinite_Scrolling > Remote_Filter](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Remote_Filter/)
28. [GridPanel > Infinite_Scrolling > Tuner](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Tuner/)
29. [GridPanel > Locking_Grid > Infinite_Scrolling](https://examples5.ext.net/#/GridPanel/Locking_Grid/Infinite_Scrolling/)
30. [GridPanel > Miscellaneous > Custom_UI](https://examples5.ext.net/#/GridPanel/Miscellaneous/Custom_UI/)
31. [GridPanel > Miscellaneous > Export_Data_PostBack](https://examples5.ext.net/#/GridPanel/Miscellaneous/Export_Data_PostBack/)
32. [GridPanel > Miscellaneous > FilterQuery](https://examples5.ext.net/#/GridPanel/Miscellaneous/FilterQuery/)
33. [GridPanel > Miscellaneous > Submit_to_Handler](https://examples5.ext.net/#/GridPanel/Miscellaneous/Submit_to_Handler/)
34. [GridPanel > Miscellaneous > Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Two_Grids/)
35. [GridPanel > Miscellaneous > Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Two_Grids/)
36. [GridPanel > Paging_and_Sorting > DirectMethod](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/DirectMethod/)
37. [GridPanel > Paging_and_Sorting > Handler](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Handler/)
38. [GridPanel > Paging_and_Sorting > Local_Data_Paging](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Local_Data_Paging/)
39. [GridPanel > Paging_and_Sorting > Page](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Page/)
40. [GridPanel > Plugins > LiveSearch](https://examples5.ext.net/#/GridPanel/Plugins/LiveSearch/)
41. [GridPanel > Plugins > SlidingPager](https://examples5.ext.net/#/GridPanel/Plugins/SlidingPager/)
42. [GridPanel > RowExpander > Local_Mode](https://examples5.ext.net/#/GridPanel/RowExpander/Local_Mode/)
43. [GridPanel > Saving_Variations > HttpHandler](https://examples5.ext.net/#/GridPanel/Saving_Variations/HttpHandler/)
44. [GridPanel > Saving_Variations > StoreCustomLogic](https://examples5.ext.net/#/GridPanel/Saving_Variations/StoreCustomLogic/)
45. [GridPanel > Saving_Variations > StoreEvents](https://examples5.ext.net/#/GridPanel/Saving_Variations/StoreEvents/)
46. [GridPanel > Saving_Variations > WebService](https://examples5.ext.net/#/GridPanel/Saving_Variations/WebService/)
47. [GridPanel > Selection_Models > Row_Selection](https://examples5.ext.net/#/GridPanel/Selection_Models/Row_Selection/)
48. [GridPanel > Selection_Models > Submitting_Values](https://examples5.ext.net/#/GridPanel/Selection_Models/Submitting_Values/)
49. [GridPanel > System.Data > DataReader](https://examples5.ext.net/#/GridPanel/System.Data/DataReader/)
50. [GridPanel > System.Data > DataTable](https://examples5.ext.net/#/GridPanel/System.Data/DataTable/)
51. [GridPanel > Update > AutoSave](https://examples5.ext.net/#/GridPanel/Update/AutoSave/)
52. [GridPanel > Update > Batch](https://examples5.ext.net/#/GridPanel/Update/Batch/)
53. [GridPanel > Update > SqlDataSource](https://examples5.ext.net/#/GridPanel/Update/SqlDataSource/)
54. [Keys > Panel_Keys > Grid_Rows_Delete](https://examples5.ext.net/#/Keys/Panel_Keys/Grid_Rows_Delete/)
55. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://examples5.ext.net/#/Miscellaneous/Mouse_Distance_Sensor/Basic/)
56. [Miscellaneous > Store > ClientStore](https://examples5.ext.net/#/Miscellaneous/Store/ClientStore/)
57. [Miscellaneous > ToolTips > GridPanel_Cell_Tooltip](https://examples5.ext.net/#/Miscellaneous/ToolTips/GridPanel_Cell_Tooltip/)
58. [Miscellaneous > ToolTips > GridPanel_Row_Tooltip](https://examples5.ext.net/#/Miscellaneous/ToolTips/GridPanel_Row_Tooltip/)

#### MVC (`.RowSelectionModel()`)
1. [Actions > Grid](https://mvc5.ext.net/#/Actions/Grid/)
2. [DragDrop > Grid > Grid_to_FormPanel](https://mvc5.ext.net/#/DragDrop_Grid/Grid_to_FormPanel/)
3. [Getting > Started > Component_Overview](https://mvc5.ext.net/#/Getting_Started/Component_Overview/)
4. [GridPanel > ArrayGrid > ArrayWithPaging](https://mvc5.ext.net/#/GridPanel_ArrayGrid/ArrayWithPaging/)
5. [GridPanel > Commands > Cell_Command](https://mvc5.ext.net/#/GridPanel_Commands/Cell_Command/)
6. [GridPanel > Commands > Image_Command](https://mvc5.ext.net/#/GridPanel_Commands/Image_Command/)
7. [GridPanel > Infinite_Scrolling > Buffered_Scrolling](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/)
8. [GridPanel > Infinite_Scrolling > Forum_topics](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Forum_topics/)
9. [GridPanel > Infinite_Scrolling > Remote_Filter](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Remote_Filter/)
10. [GridPanel > Miscellaneous > FilterQuery](https://mvc5.ext.net/#/GridPanel_Miscellaneous/FilterQuery/)
11. [GridPanel > Paging_and_Sorting > Local](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Local/)
12. [GridPanel > Update > AutoSave](https://mvc5.ext.net/#/GridPanel_Update/AutoSave/)
13. [GridPanel > Update > Batch](https://mvc5.ext.net/#/GridPanel_Update/Batch/)
14. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://mvc5.ext.net/#/Miscellaneous_Mouse_Distance_Sensor/Basic/)

**Comment by AndreyChechel** [comment]
Implemented in `7.0.0-preview4`, see https://github.com/extnet/Ext.NET/issues/1735#issuecomment-660328118
