### ISSUE TITLE
absent: ext-gridpanel's SelectionModel inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1735]
The `ext-gridpanel` component does not allow an inner `SelectionModel` block, thus the grid's selection model cannot be specified.

[arraygrid/simple/index.cshtml#L97-L99](https://github.com/objectdotnet/ext7-sandbox/blob/93c311202563c66262e232cb07a256f5ed7b54a6/ExtNetCore7-20200325/Pages/examples/gridpanel/arraygrid/simple/index.cshtml#L97-L99)

#### WebForms (`<SelectionModel>`)
1. [Action > Basic > Grid](https://examples5.ext.net/#/Action/Basic/Grid/)
2. [ColorPicker > Advanced > GridPanel](https://examples5.ext.net/#/ColorPicker/Advanced/GridPanel/)
3. [DragDrop > Grid > Grid_to_FormPanel](https://examples5.ext.net/#/DragDrop/Grid/Grid_to_FormPanel/)
4. [Form > DropDownField > Overview](https://examples5.ext.net/#/Form/DropDownField/Overview/)
5. [Form > DropDownField > ValueText_Mode](https://examples5.ext.net/#/Form/DropDownField/ValueText_Mode/)
6. [Getting_Started > Introduction > Component_Overview](https://examples5.ext.net/#/Getting_Started/Introduction/Component_Overview/)
7. [GridPanel > ArrayGrid > ArrayWithPaging](https://examples5.ext.net/#/GridPanel/ArrayGrid/ArrayWithPaging/)
8. [GridPanel > ArrayGrid > ForceFit](https://examples5.ext.net/#/GridPanel/ArrayGrid/ForceFit/)
9. [GridPanel > ArrayGrid > Keep_Page_on_Refresh](https://examples5.ext.net/#/GridPanel/ArrayGrid/Keep_Page_on_Refresh/)
10. [GridPanel > ArrayGrid > Remote_Load](https://examples5.ext.net/#/GridPanel/ArrayGrid/Remote_Load/)
11. [GridPanel > ArrayGrid > Simple](https://examples5.ext.net/#/GridPanel/ArrayGrid/Simple/)
12. [GridPanel > ColumnModel > Reconfigure](https://examples5.ext.net/#/GridPanel/ColumnModel/Reconfigure/)
13. [GridPanel > Commands > Cell_Command](https://examples5.ext.net/#/GridPanel/Commands/Cell_Command/)
14. [GridPanel > Commands > Group_Command](https://examples5.ext.net/#/GridPanel/Commands/Group_Command/)
15. [GridPanel > Commands > Image_Command](https://examples5.ext.net/#/GridPanel/Commands/Image_Command/)
16. [GridPanel > Commands > Menu_Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Menu_Row_Command/)
17. [GridPanel > Commands > Over_Commands](https://examples5.ext.net/#/GridPanel/Commands/Over_Commands/)
18. [GridPanel > Commands > Prepare_Commands](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Commands/)
19. [GridPanel > Commands > Prepare_Toolbar](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Toolbar/)
20. [GridPanel > Commands > Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Row_Command/)
21. [GridPanel > DataSource_Controls > LinqDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/LinqDataSource/)
22. [GridPanel > DataSource_Controls > ObjectDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/ObjectDataSource/)
23. [GridPanel > DataSource_Controls > SqlDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/SqlDataSource/)
24. [GridPanel > Data_Presentation > Grid_and_Store_Reconfigure](https://examples5.ext.net/#/GridPanel/Data_Presentation/Grid_and_Store_Reconfigure/)
25. [GridPanel > Data_with_Details > Form_Details](https://examples5.ext.net/#/GridPanel/Data_with_Details/Form_Details/)
26. [GridPanel > Data_with_Details > One-to-Many](https://examples5.ext.net/#/GridPanel/Data_with_Details/One-to-Many/)
27. [GridPanel > Editable > Editor_with_DirectMethod](https://examples5.ext.net/#/GridPanel/Editable/Editor_with_DirectMethod/)
28. [GridPanel > Infinite_Scrolling > Buffered_Scrolling](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Buffered_Scrolling/)
29. [GridPanel > Infinite_Scrolling > Forum_topics](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Forum_topics/)
30. [GridPanel > Infinite_Scrolling > Remote_Filter](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Remote_Filter/)
31. [GridPanel > Infinite_Scrolling > Tuner](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Tuner/)
32. [GridPanel > List_View > Overview](https://examples5.ext.net/#/GridPanel/List_View/Overview/)
33. [GridPanel > Locking_Grid > Cell_Editing](https://examples5.ext.net/#/GridPanel/Locking_Grid/Cell_Editing/)
34. [GridPanel > Locking_Grid > GroupingSummary](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary/)
35. [GridPanel > Locking_Grid > Infinite_Scrolling](https://examples5.ext.net/#/GridPanel/Locking_Grid/Infinite_Scrolling/)
36. [GridPanel > Miscellaneous > Custom_UI](https://examples5.ext.net/#/GridPanel/Miscellaneous/Custom_UI/)
37. [GridPanel > Miscellaneous > Export_Data_PostBack](https://examples5.ext.net/#/GridPanel/Miscellaneous/Export_Data_PostBack/)
38. [GridPanel > Miscellaneous > FilterQuery](https://examples5.ext.net/#/GridPanel/Miscellaneous/FilterQuery/)
39. [GridPanel > Miscellaneous > Submit_to_Handler](https://examples5.ext.net/#/GridPanel/Miscellaneous/Submit_to_Handler/)
40. [GridPanel > Miscellaneous > Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Two_Grids/)
41. [GridPanel > Miscellaneous > Two_Grids](https://examples5.ext.net/#/GridPanel/Miscellaneous/Two_Grids/)
42. [GridPanel > Paging_and_Sorting > DirectMethod](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/DirectMethod/)
43. [GridPanel > Paging_and_Sorting > Handler](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Handler/)
44. [GridPanel > Paging_and_Sorting > Local_Data_Paging](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Local_Data_Paging/)
45. [GridPanel > Paging_and_Sorting > Page](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Page/)
46. [GridPanel > Plugins > CellEditing](https://examples5.ext.net/#/GridPanel/Plugins/CellEditing/)
47. [GridPanel > Plugins > LiveSearch](https://examples5.ext.net/#/GridPanel/Plugins/LiveSearch/)
48. [GridPanel > Plugins > Selection_Memory](https://examples5.ext.net/#/GridPanel/Plugins/Selection_Memory/)
49. [GridPanel > Plugins > SlidingPager](https://examples5.ext.net/#/GridPanel/Plugins/SlidingPager/)
50. [GridPanel > RowExpander > Local_Mode](https://examples5.ext.net/#/GridPanel/RowExpander/Local_Mode/)
51. [GridPanel > Saving_Variations > HttpHandler](https://examples5.ext.net/#/GridPanel/Saving_Variations/HttpHandler/)
52. [GridPanel > Saving_Variations > StoreCustomLogic](https://examples5.ext.net/#/GridPanel/Saving_Variations/StoreCustomLogic/)
53. [GridPanel > Saving_Variations > StoreEvents](https://examples5.ext.net/#/GridPanel/Saving_Variations/StoreEvents/)
54. [GridPanel > Saving_Variations > WebService](https://examples5.ext.net/#/GridPanel/Saving_Variations/WebService/)
55. [GridPanel > Selection_Models > Cell_Selection](https://examples5.ext.net/#/GridPanel/Selection_Models/Cell_Selection/)
56. [GridPanel > Selection_Models > Checkbox_Selection](https://examples5.ext.net/#/GridPanel/Selection_Models/Checkbox_Selection/)
57. [GridPanel > Selection_Models > Row_Selection](https://examples5.ext.net/#/GridPanel/Selection_Models/Row_Selection/)
58. [GridPanel > Selection_Models > Submitting_Values](https://examples5.ext.net/#/GridPanel/Selection_Models/Submitting_Values/)
59. [GridPanel > Spreadsheet > Clipboard](https://examples5.ext.net/#/GridPanel/Spreadsheet/Clipboard/)
60. [GridPanel > Spreadsheet > Initial_Selection](https://examples5.ext.net/#/GridPanel/Spreadsheet/Initial_Selection/)
61. [GridPanel > Spreadsheet > Locking](https://examples5.ext.net/#/GridPanel/Spreadsheet/Locking/)
62. [GridPanel > Spreadsheet > Overview](https://examples5.ext.net/#/GridPanel/Spreadsheet/Overview/)
63. [GridPanel > Spreadsheet > Select_Programmatically](https://examples5.ext.net/#/GridPanel/Spreadsheet/Select_Programmatically/)
64. [GridPanel > Spreadsheet > Submit](https://examples5.ext.net/#/GridPanel/Spreadsheet/Submit/)
65. [GridPanel > System.Data > DataReader](https://examples5.ext.net/#/GridPanel/System.Data/DataReader/)
66. [GridPanel > System.Data > DataTable](https://examples5.ext.net/#/GridPanel/System.Data/DataTable/)
67. [GridPanel > Update > AutoSave](https://examples5.ext.net/#/GridPanel/Update/AutoSave/)
68. [GridPanel > Update > Batch](https://examples5.ext.net/#/GridPanel/Update/Batch/)
69. [GridPanel > Update > SqlDataSource](https://examples5.ext.net/#/GridPanel/Update/SqlDataSource/)
70. [Keys > Panel_Keys > Grid_Rows_Delete](https://examples5.ext.net/#/Keys/Panel_Keys/Grid_Rows_Delete/)
71. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://examples5.ext.net/#/Miscellaneous/Mouse_Distance_Sensor/Basic/)
72. [Miscellaneous > Store > ClientStore](https://examples5.ext.net/#/Miscellaneous/Store/ClientStore/)
73. [Miscellaneous > ToolTips > GridPanel_Cell_Tooltip](https://examples5.ext.net/#/Miscellaneous/ToolTips/GridPanel_Cell_Tooltip/)
74. [Miscellaneous > ToolTips > GridPanel_Row_Tooltip](https://examples5.ext.net/#/Miscellaneous/ToolTips/GridPanel_Row_Tooltip/)

#### MVC (`.SelectionModel()`)
1. [Actions > Grid](https://mvc5.ext.net/#/Actions/Grid/)
2. [DragDrop > Grid > Grid_to_FormPanel](https://mvc5.ext.net/#/DragDrop_Grid/Grid_to_FormPanel/)
3. [Getting > Started > Component_Overview](https://mvc5.ext.net/#/Getting_Started/Component_Overview/)
4. [GridPanel > ArrayGrid > ArrayWithPaging](https://mvc5.ext.net/#/GridPanel_ArrayGrid/ArrayWithPaging/)
5. [GridPanel > Commands > Cell_Command](https://mvc5.ext.net/#/GridPanel_Commands/Cell_Command/)
6. [GridPanel > Commands > Group_Command](https://mvc5.ext.net/#/GridPanel_Commands/Group_Command/)
7. [GridPanel > Commands > Image_Command](https://mvc5.ext.net/#/GridPanel_Commands/Image_Command/)
8. [GridPanel > Editable > Editor_with_DirectMethod](https://mvc5.ext.net/#/GridPanel_Editable/Editor_with_DirectMethod/)
9. [GridPanel > Infinite_Scrolling > Buffered_Scrolling](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/)
10. [GridPanel > Infinite_Scrolling > Forum_topics](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Forum_topics/)
11. [GridPanel > Infinite_Scrolling > Remote_Filter](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Remote_Filter/)
12. [GridPanel > Miscellaneous > FilterQuery](https://mvc5.ext.net/#/GridPanel_Miscellaneous/FilterQuery/)
13. [GridPanel > Paging_and_Sorting > Local](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Local/)
14. [GridPanel > Plugins > CellEditing](https://mvc5.ext.net/#/GridPanel_Plugins/CellEditing/)
15. [GridPanel > Selection_Models > Checkbox_Selection](https://mvc5.ext.net/#/GridPanel_Selection_Models/Checkbox_Selection/)
16. [GridPanel > Spreadsheet > Overview](https://mvc5.ext.net/#/GridPanel_Spreadsheet/Overview/)
17. [GridPanel > Spreadsheet > Submit](https://mvc5.ext.net/#/GridPanel_Spreadsheet/Submit/)
18. [GridPanel > Update > AutoSave](https://mvc5.ext.net/#/GridPanel_Update/AutoSave/)
19. [GridPanel > Update > Batch](https://mvc5.ext.net/#/GridPanel_Update/Batch/)
20. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://mvc5.ext.net/#/Miscellaneous_Mouse_Distance_Sensor/Basic/)

**Comment by AndreyChechel** [comment]
Fixed in `7.0.0-preview4`. Please pay attention that the property name is different now (`selModel` instead of `SelectionModel`):
```cshtml
<selModel>
    <ext-rowSelectionModel />
</selModel>
```
