### ISSUE TITLE
broken: ext-button's Handler results in client-side parse error

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1736]
The `ext-button`'s `Handler=` is binding a straight inline code that is resolved at render time, thus breaking the event in most situations, as well as creating unparseable init script.

Issue explored at [gridpanel/arraygrid/simple/index.cshtml#L103](https://github.com/objectdotnet/ext7-sandbox/blob/93c311202563c66262e232cb07a256f5ed7b54a6/ExtNetCore7-20200325/Pages/examples/gridpanel/arraygrid/simple/index.cshtml#L103)

#### Additional information:

This:
```xml
<ext-button Text="Print" Icon="Printer" _Handler="this.up('grid').print();" />
```

Results in:
```js
{
    xtype: "button",
    handler: this.up('grid').print();, /* this.up('grid') is undefined before all is rendered */
    icon: "Printer",
    text: "Print"
}
```

Where it should result in:
```js
{
    xtype: "button",
    handler: function() {
        this.up('grid').print(); /* From Ext.NET 5 */
    },
    icon: "Printer",
    text: "Print"
}
```

#### WebForms examples using this:

1. [Buttons > Basic > Overview](https://examples5.ext.net/#/Buttons/Basic/Overview/)
2. [Chart > Bar > 3D](https://examples5.ext.net/#/Chart/Bar/3D/)
3. [Chart > Financial > Candlestick](https://examples5.ext.net/#/Chart/Financial/Candlestick/)
4. [Chart > Financial > OHLC](https://examples5.ext.net/#/Chart/Financial/OHLC/)
5. [Chart > Gauge > Basic_2](https://examples5.ext.net/#/Chart/Gauge/Basic_2/)
6. [Chart > Pie > 3D](https://examples5.ext.net/#/Chart/Pie/3D/)
7. [Chart > Radar > Basic](https://examples5.ext.net/#/Chart/Radar/Basic/)
8. [Chart > Radar > Marked](https://examples5.ext.net/#/Chart/Radar/Marked/)
9. [Chart > Radar > MultiAxis](https://examples5.ext.net/#/Chart/Radar/MultiAxis/)
10. [Chart > Scatter > Basic](https://examples5.ext.net/#/Chart/Scatter/Basic/)
11. [Chart > Scatter > Bubble](https://examples5.ext.net/#/Chart/Scatter/Bubble/)
12. [Chart > Scatter > Custom_Icons](https://examples5.ext.net/#/Chart/Scatter/Custom_Icons/)
13. [Chart > Scatter > Renderer](https://examples5.ext.net/#/Chart/Scatter/Renderer/)
14. [DataView > Advanced > Editing](https://examples5.ext.net/#/DataView/Advanced/Editing/)
15. [DataView > ComponentView > Editor](https://examples5.ext.net/#/DataView/ComponentView/Editor/)
16. [DataView > ComponentView > Overview](https://examples5.ext.net/#/DataView/ComponentView/Overview/)
17. [Data_Binding > Basic > Dynamic](https://examples5.ext.net/#/Data_Binding/Basic/Dynamic/)
18. [Data_Binding > Basic > Isolated_Child_Sessions](https://examples5.ext.net/#/Data_Binding/Basic/Isolated_Child_Sessions/)
19. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
20. [Form > Groups > Basic](https://examples5.ext.net/#/Form/Groups/Basic/)
21. [Form > MultiSelect > ItemSelector](https://examples5.ext.net/#/Form/MultiSelect/ItemSelector/)
22. [Form > Tag > TagField](https://examples5.ext.net/#/Form/Tag/TagField/)
23. [Form > Tag > TagLabel](https://examples5.ext.net/#/Form/Tag/TagLabel/)
24. [Form > TextField > InputMask_Native](https://examples5.ext.net/#/Form/TextField/InputMask_Native/)
25. [GridPanel > ArrayGrid > ArrayWithPaging](https://examples5.ext.net/#/GridPanel/ArrayGrid/ArrayWithPaging/)
26. [GridPanel > ArrayGrid > Keep_Page_on_Refresh](https://examples5.ext.net/#/GridPanel/ArrayGrid/Keep_Page_on_Refresh/)
27. [GridPanel > ArrayGrid > Simple](https://examples5.ext.net/#/GridPanel/ArrayGrid/Simple/)
28. [GridPanel > Data_Presentation > Meta_config_with_handler](https://examples5.ext.net/#/GridPanel/Data_Presentation/Meta_config_with_handler/)
29. [GridPanel > FilterHeader > Custom_Behaviour](https://examples5.ext.net/#/GridPanel/FilterHeader/Custom_Behaviour/)
30. [GridPanel > Miscellaneous > FilterQuery](https://examples5.ext.net/#/GridPanel/Miscellaneous/FilterQuery/)
31. [GridPanel > Miscellaneous > Grouping](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping/)
32. [GridPanel > Paging_and_Sorting > DirectMethod](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/DirectMethod/)
33. [GridPanel > Plugins > CellEditing](https://examples5.ext.net/#/GridPanel/Plugins/CellEditing/)
34. [GridPanel > Plugins > GridFilters_Local](https://examples5.ext.net/#/GridPanel/Plugins/GridFilters_Local/)
35. [GridPanel > Plugins > LiveSearch](https://examples5.ext.net/#/GridPanel/Plugins/LiveSearch/)
36. [GridPanel > Spreadsheet > Clipboard](https://examples5.ext.net/#/GridPanel/Spreadsheet/Clipboard/)
37. [Layout > FormLayout > Overview](https://examples5.ext.net/#/Layout/FormLayout/Overview/)
38. [MessageBox > Badge > Overview](https://examples5.ext.net/#/MessageBox/Badge/Overview/)
39. [MessageBox > Callout > Overview](https://examples5.ext.net/#/MessageBox/Callout/Overview/)
40. [MessageBox > InfoPanel > Items](https://examples5.ext.net/#/MessageBox/InfoPanel/Items/)
41. [Miscellaneous > Factory > Basic](https://examples5.ext.net/#/Miscellaneous/Factory/Basic/)
42. [Miscellaneous > Template_Widget > Overview](https://examples5.ext.net/#/Miscellaneous/Template_Widget/Overview/)
43. [TabPanel > Basic > Reorderable_Tabs](https://examples5.ext.net/#/TabPanel/Basic/Reorderable_Tabs/)
44. [Toolbar > Menu > Toolbar_with_Menus](https://examples5.ext.net/#/Toolbar/Menu/Toolbar_with_Menus/)
45. [Window > Toast > Overview](https://examples5.ext.net/#/Window/Toast/Overview/)

**Comment by geoffreymcgill** [comment]
The decision, at least for now, is that we will not automatically wrap the `Hander` value in a `function() { ... }` template.

To get the samples above working, the value of the `Hander` would need to be added inside a basic function template.
