### ISSUE TITLE
broken: ext-datedatafield model field

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1737]
Dates are printed in the grid as an assortment of `NaN` according to the format specified.

In this example, the essential specification is kept: a string field with something like `"9/1 12:00am"` subject to `DateFormat="M/d hh:mmtt"`.

[gridpanel/arraygrid/simple/index.cshtml#L73](https://github.com/objectdotnet/ext7-sandbox/blob/63f636a3851d0c87ed7bf91aef3e89cf0a09b147/ExtNetCore7-20200325/Pages/examples/gridpanel/arraygrid/simple/index.cshtml#L73)

#### WebForms examples matching `<ext:ModelField .*Type="Date"`

1. [Action > Basic > Grid](https://examples5.ext.net/#/Action/Basic/Grid/)
2. [Associations > HasMany > Lazy_Load](https://examples5.ext.net/#/Associations/HasMany/Lazy_Load/)
3. [Calendar > Overview > Remote_Data](https://examples5.ext.net/#/Calendar/Overview/Remote_Data/)
4. [Calendar > Overview > Shared](https://examples5.ext.net/#/Calendar/Overview/Shared/)
5. [Chart > Area > Stacked](https://examples5.ext.net/#/Chart/Area/Stacked/)
6. [Chart > Area > Stacked_100](https://examples5.ext.net/#/Chart/Area/Stacked_100/)
7. [Chart > Financial > Candlestick](https://examples5.ext.net/#/Chart/Financial/Candlestick/)
8. [Chart > Financial > OHLC](https://examples5.ext.net/#/Chart/Financial/OHLC/)
9. [Chart > Line > CrossZoom](https://examples5.ext.net/#/Chart/Line/CrossZoom/)
10. [Chart > Line > Multiple_Axes](https://examples5.ext.net/#/Chart/Line/Multiple_Axes/)
11. [Chart > Live > Animated](https://examples5.ext.net/#/Chart/Live/Animated/)
12. [Chart > Live > Updates](https://examples5.ext.net/#/Chart/Live/Updates/)
13. [Chart > Misc > VerticalMarker](https://examples5.ext.net/#/Chart/Misc/VerticalMarker/)
14. [ColorPicker > Advanced > GridPanel](https://examples5.ext.net/#/ColorPicker/Advanced/GridPanel/)
15. [DataView > Basic > Overview](https://examples5.ext.net/#/DataView/Basic/Overview/)
16. [DataView > Basic > With_Paging](https://examples5.ext.net/#/DataView/Basic/With_Paging/)
17. [DataView > ComponentView > Editor](https://examples5.ext.net/#/DataView/ComponentView/Editor/)
18. [Data_Binding > Basic > Associations](https://examples5.ext.net/#/Data_Binding/Basic/Associations/)
19. [Data_Binding > Basic > Isolated_Child_Sessions](https://examples5.ext.net/#/Data_Binding/Basic/Isolated_Child_Sessions/)
20. [DragDrop > Grid > Cell_to_Cell](https://examples5.ext.net/#/DragDrop/Grid/Cell_to_Cell/)
21. [DragDrop > Grid > Field_to_Grid](https://examples5.ext.net/#/DragDrop/Grid/Field_to_Grid/)
22. [DragDrop > Grid > Grid_to_Tree](https://examples5.ext.net/#/DragDrop/Grid/Grid_to_Tree/)
23. [Form > DisplayTime > DataView](https://examples5.ext.net/#/Form/DisplayTime/DataView/)
24. [Form > FormPanel > Basic](https://examples5.ext.net/#/Form/FormPanel/Basic/)
25. [Form > Miscellaneous > Custom_Form](https://examples5.ext.net/#/Form/Miscellaneous/Custom_Form/)
26. [Form > Miscellaneous > Data_Binding](https://examples5.ext.net/#/Form/Miscellaneous/Data_Binding/)
27. [Form > Miscellaneous > Edit_Form_View](https://examples5.ext.net/#/Form/Miscellaneous/Edit_Form_View/)
28. [Form > Miscellaneous > Form_View](https://examples5.ext.net/#/Form/Miscellaneous/Form_View/)
29. [Form > Miscellaneous > XML_Form](https://examples5.ext.net/#/Form/Miscellaneous/XML_Form/)
30. [Getting_Started > Introduction > Component_Overview](https://examples5.ext.net/#/Getting_Started/Introduction/Component_Overview/)
31. [GridPanel > ArrayGrid > ArrayWithPaging](https://examples5.ext.net/#/GridPanel/ArrayGrid/ArrayWithPaging/)
32. [GridPanel > ArrayGrid > ForceFit](https://examples5.ext.net/#/GridPanel/ArrayGrid/ForceFit/)
33. [GridPanel > ArrayGrid > Keep_Page_on_Refresh](https://examples5.ext.net/#/GridPanel/ArrayGrid/Keep_Page_on_Refresh/)
34. [GridPanel > ArrayGrid > PageProxy_with_DirectMethod](https://examples5.ext.net/#/GridPanel/ArrayGrid/PageProxy_with_DirectMethod/)
35. [GridPanel > ArrayGrid > Remote_Load](https://examples5.ext.net/#/GridPanel/ArrayGrid/Remote_Load/)
36. [GridPanel > ArrayGrid > Simple](https://examples5.ext.net/#/GridPanel/ArrayGrid/Simple/)
37. [GridPanel > ColumnModel > Ajax_Configuration](https://examples5.ext.net/#/GridPanel/ColumnModel/Ajax_Configuration/)
38. [GridPanel > ColumnModel > Change_Models](https://examples5.ext.net/#/GridPanel/ColumnModel/Change_Models/)
39. [GridPanel > ColumnModel > Column_Variations](https://examples5.ext.net/#/GridPanel/ColumnModel/Column_Variations/)
40. [GridPanel > ColumnModel > Reconfigure](https://examples5.ext.net/#/GridPanel/ColumnModel/Reconfigure/)
41. [GridPanel > Commands > Group_Command](https://examples5.ext.net/#/GridPanel/Commands/Group_Command/)
42. [GridPanel > Commands > Image_Command](https://examples5.ext.net/#/GridPanel/Commands/Image_Command/)
43. [GridPanel > Commands > Menu_Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Menu_Row_Command/)
44. [GridPanel > Commands > Over_Commands](https://examples5.ext.net/#/GridPanel/Commands/Over_Commands/)
45. [GridPanel > Commands > Prepare_Commands](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Commands/)
46. [GridPanel > Commands > Prepare_Toolbar](https://examples5.ext.net/#/GridPanel/Commands/Prepare_Toolbar/)
47. [GridPanel > Commands > Row_Command](https://examples5.ext.net/#/GridPanel/Commands/Row_Command/)
48. [GridPanel > ComponentColumn > Editor](https://examples5.ext.net/#/GridPanel/ComponentColumn/Editor/)
49. [GridPanel > ComponentColumn > Over_Editor](https://examples5.ext.net/#/GridPanel/ComponentColumn/Over_Editor/)
50. [GridPanel > ComponentColumn > Pin_Editor](https://examples5.ext.net/#/GridPanel/ComponentColumn/Pin_Editor/)
51. [GridPanel > DataSource_Controls > LinqDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/LinqDataSource/)
52. [GridPanel > DataSource_Controls > ObjectDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/ObjectDataSource/)
53. [GridPanel > DataSource_Controls > SqlDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/SqlDataSource/)
54. [GridPanel > DataSource_Controls > XmlDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/XmlDataSource/)
55. [GridPanel > Editable > Editor_with_DirectMethod](https://examples5.ext.net/#/GridPanel/Editable/Editor_with_DirectMethod/)
56. [GridPanel > FilterHeader > Overview](https://examples5.ext.net/#/GridPanel/FilterHeader/Overview/)
57. [GridPanel > FilterHeader > Remote](https://examples5.ext.net/#/GridPanel/FilterHeader/Remote/)
58. [GridPanel > Infinite_Scrolling > Forum_topics](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Forum_topics/)
59. [GridPanel > Infinite_Scrolling > Remote_Filter](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Remote_Filter/)
60. [GridPanel > Layout > FitLayout](https://examples5.ext.net/#/GridPanel/Layout/FitLayout/)
61. [GridPanel > List_View > Overview](https://examples5.ext.net/#/GridPanel/List_View/Overview/)
62. [GridPanel > Locking_Grid > Cell_Editing](https://examples5.ext.net/#/GridPanel/Locking_Grid/Cell_Editing/)
63. [GridPanel > Locking_Grid > GroupingSummary](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary/)
64. [GridPanel > Locking_Grid > GroupingSummary_with_group_headers](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary_with_group_headers/)
65. [GridPanel > Locking_Grid > Simple](https://examples5.ext.net/#/GridPanel/Locking_Grid/Simple/)
66. [GridPanel > Miscellaneous > ColumnHeaderGroup](https://examples5.ext.net/#/GridPanel/Miscellaneous/ColumnHeaderGroup/)
67. [GridPanel > Miscellaneous > Custom_Column](https://examples5.ext.net/#/GridPanel/Miscellaneous/Custom_Column/)
68. [GridPanel > Miscellaneous > Custom_UI](https://examples5.ext.net/#/GridPanel/Miscellaneous/Custom_UI/)
69. [GridPanel > Miscellaneous > Details_Window](https://examples5.ext.net/#/GridPanel/Miscellaneous/Details_Window/)
70. [GridPanel > Miscellaneous > Details_Window_Remote](https://examples5.ext.net/#/GridPanel/Miscellaneous/Details_Window_Remote/)
71. [GridPanel > Miscellaneous > Export_Data_Ajax](https://examples5.ext.net/#/GridPanel/Miscellaneous/Export_Data_Ajax/)
72. [GridPanel > Miscellaneous > Export_Data_PostBack](https://examples5.ext.net/#/GridPanel/Miscellaneous/Export_Data_PostBack/)
73. [GridPanel > Miscellaneous > FilterQuery](https://examples5.ext.net/#/GridPanel/Miscellaneous/FilterQuery/)
74. [GridPanel > Miscellaneous > Grouping](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping/)
75. [GridPanel > Miscellaneous > Grouping_TotalRow](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping_TotalRow/)
76. [GridPanel > Miscellaneous > JSONP_Proxy](https://examples5.ext.net/#/GridPanel/Miscellaneous/JSONP_Proxy/)
77. [GridPanel > Miscellaneous > Json_Reader](https://examples5.ext.net/#/GridPanel/Miscellaneous/Json_Reader/)
78. [GridPanel > Miscellaneous > Numbered_Rows](https://examples5.ext.net/#/GridPanel/Miscellaneous/Numbered_Rows/)
79. [GridPanel > Miscellaneous > Save_Filter](https://examples5.ext.net/#/GridPanel/Miscellaneous/Save_Filter/)
80. [GridPanel > Miscellaneous > XML_File_Loading](https://examples5.ext.net/#/GridPanel/Miscellaneous/XML_File_Loading/)
81. [GridPanel > MultiHeader > Filter](https://examples5.ext.net/#/GridPanel/MultiHeader/Filter/)
82. [GridPanel > Paging_and_Sorting > DirectMethod](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/DirectMethod/)
83. [GridPanel > Paging_and_Sorting > Handler](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Handler/)
84. [GridPanel > Paging_and_Sorting > JSON_WebService](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/JSON_WebService/)
85. [GridPanel > Paging_and_Sorting > Local_Data_Paging](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Local_Data_Paging/)
86. [GridPanel > Paging_and_Sorting > Page](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Page/)
87. [GridPanel > Paging_and_Sorting > XML_WebService](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/XML_WebService/)
88. [GridPanel > Plugins > CellEditing](https://examples5.ext.net/#/GridPanel/Plugins/CellEditing/)
89. [GridPanel > Plugins > GridFilters_Local](https://examples5.ext.net/#/GridPanel/Plugins/GridFilters_Local/)
90. [GridPanel > Plugins > GridFilters_Remote](https://examples5.ext.net/#/GridPanel/Plugins/GridFilters_Remote/)
91. [GridPanel > Plugins > GroupingSummary](https://examples5.ext.net/#/GridPanel/Plugins/GroupingSummary/)
92. [GridPanel > Plugins > GroupPaging](https://examples5.ext.net/#/GridPanel/Plugins/GroupPaging/)
93. [GridPanel > Plugins > LiveSearch](https://examples5.ext.net/#/GridPanel/Plugins/LiveSearch/)
94. [GridPanel > Plugins > Remote_GroupSummary](https://examples5.ext.net/#/GridPanel/Plugins/Remote_GroupSummary/)
95. [GridPanel > Plugins > RowEditor](https://examples5.ext.net/#/GridPanel/Plugins/RowEditor/)
96. [GridPanel > Plugins > RowEditor_Remote](https://examples5.ext.net/#/GridPanel/Plugins/RowEditor_Remote/)
97. [GridPanel > Plugins > SlidingPager](https://examples5.ext.net/#/GridPanel/Plugins/SlidingPager/)
98. [GridPanel > Plugins > Summary](https://examples5.ext.net/#/GridPanel/Plugins/Summary/)
99. [GridPanel > RowExpander > Local_Mode](https://examples5.ext.net/#/GridPanel/RowExpander/Local_Mode/)
100. [GridPanel > RowExpander > Remote_Mode](https://examples5.ext.net/#/GridPanel/RowExpander/Remote_Mode/)
101. [GridPanel > RowExpander > Shared_Component](https://examples5.ext.net/#/GridPanel/RowExpander/Shared_Component/)
102. [GridPanel > Spreadsheet > Clipboard](https://examples5.ext.net/#/GridPanel/Spreadsheet/Clipboard/)
103. [GridPanel > System.Data > DataTable](https://examples5.ext.net/#/GridPanel/System.Data/DataTable/)
104. [Keys > Panel_Keys > Grid_Rows_Delete](https://examples5.ext.net/#/Keys/Panel_Keys/Grid_Rows_Delete/)
105. [Kitchen_Sink > GridPanels > Grouped_Header_GridPanel](https://examples5.ext.net/#/Kitchen_Sink/GridPanels/Grouped_Header_GridPanel/)
106. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://examples5.ext.net/#/Miscellaneous/Mouse_Distance_Sensor/Basic/)
107. [Miscellaneous > Store > ClientStore](https://examples5.ext.net/#/Miscellaneous/Store/ClientStore/)
108. [Miscellaneous > ToolTips > GridPanel_Cell_Tooltip](https://examples5.ext.net/#/Miscellaneous/ToolTips/GridPanel_Cell_Tooltip/)
109. [Miscellaneous > ToolTips > GridPanel_Row_Tooltip](https://examples5.ext.net/#/Miscellaneous/ToolTips/GridPanel_Row_Tooltip/)
110. [TabPanel > Basic > Move_Component](https://examples5.ext.net/#/TabPanel/Basic/Move_Component/)
111. [Toolbar > Plugins > ToolbarDroppable](https://examples5.ext.net/#/Toolbar/Plugins/ToolbarDroppable/)
112. [TreePanel > Advanced > Buffer_Rendered_TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/Buffer_Rendered_TreeGrid/)
113. [TreePanel > Advanced > Locking_Buffer_Rendered_TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/Locking_Buffer_Rendered_TreeGrid/)
114. [TreePanel > Advanced > Remote_Mode](https://examples5.ext.net/#/TreePanel/Advanced/Remote_Mode/)

#### MVC examples matching `ModelField *\(.*ModelFieldType\.Date`

1. [Actions > Grid](https://mvc5.ext.net/#/Actions/Grid/)
2. [DataView > Basic > Overview](https://mvc5.ext.net/#/DataView_Basic/Overview/)
3. [DataView > Basic > Paging](https://mvc5.ext.net/#/DataView_Basic/Paging/)
4. [DragDrop > Grid > Cell_to_Cell](https://mvc5.ext.net/#/DragDrop_Grid/Cell_to_Cell/)
5. [DragDrop > Grid > Field_to_Grid](https://mvc5.ext.net/#/DragDrop_Grid/Field_to_Grid/)
6. [Form > FormPanel > Basic](https://mvc5.ext.net/#/Form_FormPanel/Basic/)
7. [Getting > Started > Component_Overview](https://mvc5.ext.net/#/Getting_Started/Component_Overview/)
8. [GridPanel > ArrayGrid > ArrayWithPaging](https://mvc5.ext.net/#/GridPanel_ArrayGrid/ArrayWithPaging/)
9. [GridPanel > ArrayGrid > Remote_Load](https://mvc5.ext.net/#/GridPanel_ArrayGrid/Remote_Load/)
10. [GridPanel > ArrayGrid > Simple](https://mvc5.ext.net/#/GridPanel_ArrayGrid/Simple/)
11. [GridPanel > ColumnModel > Ajax_Configuration](https://mvc5.ext.net/#/GridPanel_ColumnModel/Ajax_Configuration/)
12. [GridPanel > ColumnModel > Column_Variations](https://mvc5.ext.net/#/GridPanel_ColumnModel/Column_Variations/)
13. [GridPanel > Commands > Group_Command](https://mvc5.ext.net/#/GridPanel_Commands/Group_Command/)
14. [GridPanel > Commands > Image_Command](https://mvc5.ext.net/#/GridPanel_Commands/Image_Command/)
15. [GridPanel > Commands > Menu_Row_Command](https://mvc5.ext.net/#/GridPanel_Commands/Menu_Row_Command/)
16. [GridPanel > Commands > Over_Commands](https://mvc5.ext.net/#/GridPanel_Commands/Over_Commands/)
17. [GridPanel > Commands > Prepare_Commands](https://mvc5.ext.net/#/GridPanel_Commands/Prepare_Commands/)
18. [GridPanel > Commands > Prepare_Toolbar](https://mvc5.ext.net/#/GridPanel_Commands/Prepare_Toolbar/)
19. [GridPanel > Commands > Row_Command](https://mvc5.ext.net/#/GridPanel_Commands/Row_Command/)
20. [GridPanel > ComponentColumn > Editor](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Editor/)
21. [GridPanel > ComponentColumn > Over_Editor](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Over_Editor/)
22. [GridPanel > ComponentColumn > Pin_Editor](https://mvc5.ext.net/#/GridPanel_ComponentColumn/Pin_Editor/)
23. [GridPanel > Editable > Editor_with_DirectMethod](https://mvc5.ext.net/#/GridPanel_Editable/Editor_with_DirectMethod/)
24. [GridPanel > FilterHeader > Overview](https://mvc5.ext.net/#/GridPanel_FilterHeader/Overview/)
25. [GridPanel > Infinite_Scrolling > Forum_topics](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Forum_topics/)
26. [GridPanel > Infinite_Scrolling > Remote_Filter](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Remote_Filter/)
27. [GridPanel > Miscellaneous > FilterQuery](https://mvc5.ext.net/#/GridPanel_Miscellaneous/FilterQuery/)
28. [GridPanel > MultiHeader > Filter](https://mvc5.ext.net/#/GridPanel_MultiHeader/Filter/)
29. [GridPanel > Paging_and_Sorting > Local](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Local/)
30. [GridPanel > Plugins > CellEditing](https://mvc5.ext.net/#/GridPanel_Plugins/CellEditing/)
31. [GridPanel > Plugins > GridFilters_Local](https://mvc5.ext.net/#/GridPanel_Plugins/GridFilters_Local/)
32. [GridPanel > Plugins > GridFilters_Remote](https://mvc5.ext.net/#/GridPanel_Plugins/GridFilters_Remote/)
33. [GridPanel > Plugins > GroupingSummary](https://mvc5.ext.net/#/GridPanel_Plugins/GroupingSummary/)
34. [GridPanel > RowExpander > Component](https://mvc5.ext.net/#/GridPanel_RowExpander/Component/)
35. [GridPanel > RowExpander > Local_Mode](https://mvc5.ext.net/#/GridPanel_RowExpander/Local_Mode/)
36. [GridPanel > RowExpander > Remote_Mode](https://mvc5.ext.net/#/GridPanel_RowExpander/Remote_Mode/)
37. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://mvc5.ext.net/#/Miscellaneous_Mouse_Distance_Sensor/Basic/)
38. [Miscellaneous > Store > ClientStore](https://mvc5.ext.net/#/Miscellaneous_Store/ClientStore/)

**Comment by geoffreymcgill** [comment]
Thanks, this is a priority to fix.

**Comment by geoffreymcgill** [comment]
Date formatting should be working now.
