### ISSUE TITLE
absent: Charts support

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1739]
There is currently no support to the charts module in Ext.NET Core.

Once this is implemented, chart-related samples can begin being tested.

#### WebForms examples matching `<ext:(Polar|Cartesian)Chart`

1. [Chart > Area > Basic](https://examples5.ext.net/#/Chart/Area/Basic/)
2. [Chart > Area > Stacked](https://examples5.ext.net/#/Chart/Area/Stacked/)
3. [Chart > Area > Stacked_100](https://examples5.ext.net/#/Chart/Area/Stacked_100/)
4. [Chart > Bar > 3D](https://examples5.ext.net/#/Chart/Bar/3D/)
5. [Chart > Bar > Basic](https://examples5.ext.net/#/Chart/Bar/Basic/)
6. [Chart > Bar > Grouped](https://examples5.ext.net/#/Chart/Bar/Grouped/)
7. [Chart > Bar > Mixed](https://examples5.ext.net/#/Chart/Bar/Mixed/)
8. [Chart > Bar > Renderer](https://examples5.ext.net/#/Chart/Bar/Renderer/)
9. [Chart > Bar > Stacked](https://examples5.ext.net/#/Chart/Bar/Stacked/)
10. [Chart > Bar > Stacked_100](https://examples5.ext.net/#/Chart/Bar/Stacked_100/)
11. [Chart > Column > 3D](https://examples5.ext.net/#/Chart/Column/3D/)
12. [Chart > Column > Basic](https://examples5.ext.net/#/Chart/Column/Basic/)
13. [Chart > Column > Gradients](https://examples5.ext.net/#/Chart/Column/Gradients/)
14. [Chart > Column > Limit](https://examples5.ext.net/#/Chart/Column/Limit/)
15. [Chart > Column > MultiAxis](https://examples5.ext.net/#/Chart/Column/MultiAxis/)
16. [Chart > Column > Renderer](https://examples5.ext.net/#/Chart/Column/Renderer/)
17. [Chart > Column > Stacked](https://examples5.ext.net/#/Chart/Column/Stacked/)
18. [Chart > Column > Stacked_100](https://examples5.ext.net/#/Chart/Column/Stacked_100/)
19. [Chart > Combination > Binding_Tabs](https://examples5.ext.net/#/Chart/Combination/Binding_Tabs/)
20. [Chart > Combination > Custom_Theme](https://examples5.ext.net/#/Chart/Combination/Custom_Theme/)
21. [Chart > Combination > Dashboard](https://examples5.ext.net/#/Chart/Combination/Dashboard/)
22. [Chart > Combination > Infographic](https://examples5.ext.net/#/Chart/Combination/Infographic/)
23. [Chart > Combination > Infographic](https://examples5.ext.net/#/Chart/Combination/Infographic/)
24. [Chart > Combination > Infographic](https://examples5.ext.net/#/Chart/Combination/Infographic/)
25. [Chart > Combination > Pareto](https://examples5.ext.net/#/Chart/Combination/Pareto/)
26. [Chart > Financial > Candlestick](https://examples5.ext.net/#/Chart/Financial/Candlestick/)
27. [Chart > Financial > OHLC](https://examples5.ext.net/#/Chart/Financial/OHLC/)
28. [Chart > Gauge > Basic_1](https://examples5.ext.net/#/Chart/Gauge/Basic_1/)
29. [Chart > Gauge > Basic_2](https://examples5.ext.net/#/Chart/Gauge/Basic_2/)
30. [Chart > Line > Basic](https://examples5.ext.net/#/Chart/Line/Basic/)
31. [Chart > Line > CrossZoom](https://examples5.ext.net/#/Chart/Line/CrossZoom/)
32. [Chart > Line > Image_Markers](https://examples5.ext.net/#/Chart/Line/Image_Markers/)
33. [Chart > Line > Marked_Spline](https://examples5.ext.net/#/Chart/Line/Marked_Spline/)
34. [Chart > Line > Markers](https://examples5.ext.net/#/Chart/Line/Markers/)
35. [Chart > Line > Mixed](https://examples5.ext.net/#/Chart/Line/Mixed/)
36. [Chart > Line > Multiple_Axes](https://examples5.ext.net/#/Chart/Line/Multiple_Axes/)
37. [Chart > Line > Plot](https://examples5.ext.net/#/Chart/Line/Plot/)
38. [Chart > Line > Renderer](https://examples5.ext.net/#/Chart/Line/Renderer/)
39. [Chart > Line > Spline](https://examples5.ext.net/#/Chart/Line/Spline/)
40. [Chart > Live > Animated](https://examples5.ext.net/#/Chart/Live/Animated/)
41. [Chart > Live > Updates](https://examples5.ext.net/#/Chart/Live/Updates/)
42. [Chart > Misc > Captions](https://examples5.ext.net/#/Chart/Misc/Captions/)
43. [Chart > Misc > Download](https://examples5.ext.net/#/Chart/Misc/Download/)
44. [Chart > Misc > Merge_Two_Charts](https://examples5.ext.net/#/Chart/Misc/Merge_Two_Charts/)
45. [Chart > Misc > Reload](https://examples5.ext.net/#/Chart/Misc/Reload/)
46. [Chart > Misc > Theme](https://examples5.ext.net/#/Chart/Misc/Theme/)
47. [Chart > Misc > ToolTips](https://examples5.ext.net/#/Chart/Misc/ToolTips/)
48. [Chart > Misc > VerticalMarker](https://examples5.ext.net/#/Chart/Misc/VerticalMarker/)
49. [Chart > Pie > 3D](https://examples5.ext.net/#/Chart/Pie/3D/)
50. [Chart > Pie > Basic](https://examples5.ext.net/#/Chart/Pie/Basic/)
51. [Chart > Pie > Renderer](https://examples5.ext.net/#/Chart/Pie/Renderer/)
52. [Chart > Radar > Basic](https://examples5.ext.net/#/Chart/Radar/Basic/)
53. [Chart > Radar > Fill](https://examples5.ext.net/#/Chart/Radar/Fill/)
54. [Chart > Radar > Marked](https://examples5.ext.net/#/Chart/Radar/Marked/)
55. [Chart > Radar > MultiAxis](https://examples5.ext.net/#/Chart/Radar/MultiAxis/)
56. [Chart > Scatter > Basic](https://examples5.ext.net/#/Chart/Scatter/Basic/)
57. [Chart > Scatter > Bubble](https://examples5.ext.net/#/Chart/Scatter/Bubble/)
58. [Chart > Scatter > Custom_Icons](https://examples5.ext.net/#/Chart/Scatter/Custom_Icons/)
59. [Chart > Scatter > Renderer](https://examples5.ext.net/#/Chart/Scatter/Renderer/)
60. [Combination_Samples > Applications > Word_Wrench](https://examples5.ext.net/#/Combination_Samples/Applications/Word_Wrench/)
61. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)

#### MVC examples matching `\.(Polar|Cartesian)Chart\(`

1. [Chart > Area > Basic](https://mvc5.ext.net/#/Chart_Area/Basic/)
2. [Chart > Bar > Basic](https://mvc5.ext.net/#/Chart_Bar/Basic/)
3. [Chart > Bar > Basic_3D](https://mvc5.ext.net/#/Chart_Bar/Basic_3D/)
4. [Chart > Column > Basic](https://mvc5.ext.net/#/Chart_Column/Basic/)
5. [Chart > Dashboard > Basic](https://mvc5.ext.net/#/Chart_Dashboard/Basic/)
6. [Chart > Gauge > Basic](https://mvc5.ext.net/#/Chart_Gauge/Basic/)
7. [Chart > Line > Basic](https://mvc5.ext.net/#/Chart_Line/Basic/)
8. [Chart > Misc > Captions](https://mvc5.ext.net/#/Chart_Misc/Captions/)
9. [Chart > Pie > Basic](https://mvc5.ext.net/#/Chart_Pie/Basic/)
10. [Chart > Radar > Basic](https://mvc5.ext.net/#/Chart_Radar/Basic/)
11. [Chart > Scatter > Basic](https://mvc5.ext.net/#/Chart_Scatter/Basic/)
12. [Desktop > Overview](https://mvc5.ext.net/#/Desktop/Overview/)
13. [Portal > Complex](https://mvc5.ext.net/#/Portal/Complex/)

**Comment by geoffreymcgill** [comment]
Chart components are now supported in `7.0.0-preview4`. 

#### cshtml

```cshtml
<ext-cartesianChart height="500">
    <store>
        <ext-store data="Model.ChartData">
            <fields>
                <ext-datafield name="name" />
                <ext-dataField name="value" />
            </fields>
        </ext-store>
    </store>
    <axes>
        <ext-numericAxis
            position="Left"
            fields='"value"'
            grid="true"
            title='"Number of Hits"'
            minimum="0"
            />
        <ext-categoryAxis
            position="Bottom"
            fields='"name"'
            title='"Month of the Year"'
            />
    </axes>
    <series>
        <ext-barSeries
            highlight="true"
            xField="name"
            yField='"value"'
            />
    </series>
</ext-cartesianChart>
```

#### cshtml.cs

```csharp
public object[] ChartData { get; set; }

public void OnGet()
{
    ChartData = new[]
    {
        new { Name = "Jan", Value = 10 },
        new { Name = "Feb", Value = 20 },
        new { Name = "Mar", Value = 30 },
        new { Name = "Apr", Value = 40 },
        new { Name = "May", Value = 50 },
        new { Name = "Jun", Value = 60 },
        new { Name = "Jul", Value = 70 },
        new { Name = "Aug", Value = 80 },
        new { Name = "Sep", Value = 90 },
        new { Name = "Oct", Value = 100 },
        new { Name = "Nov", Value = 110 },
        new { Name = "Dec", Value = 120 }
    };
}
```

Two new lines are required in your projects **Startup.cs**:

```csharp
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddExtNet();
            services.AddExtNetCharts(); // <-- Add this line
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseExtNetResources(config =>
            {
                config.UseCharts();  // <-- Add this line
                config.UseEmbedded();
                config.UseThemeTriton();
            });
        }
```
