### ISSUE TITLE
absent: Draw support

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1740]
There is currently no support to the draw module in Ext.NET Core.

Once this is implemented, draw-related samples can begin being tested.

This module is a pre-requisite (client-side, at least) to have the Charts module working (#1739).

#### WebForms examples matching `<ext:DrawContainer`

1. [Draw > Basic > Actions](https://examples5.ext.net/#/Draw/Basic/Actions/)
2. [Draw > Basic > Analytics](https://examples5.ext.net/#/Draw/Basic/Analytics/)
3. [Draw > Basic > Animation](https://examples5.ext.net/#/Draw/Basic/Animation/)
4. [Draw > Basic > Animation_Playground](https://examples5.ext.net/#/Draw/Basic/Animation_Playground/)
5. [Draw > Basic > Australia](https://examples5.ext.net/#/Draw/Basic/Australia/)
6. [Draw > Basic > Logos](https://examples5.ext.net/#/Draw/Basic/Logos/)
7. [Draw > Basic > Pie_Chart](https://examples5.ext.net/#/Draw/Basic/Pie_Chart/)
8. [Draw > Basic > Punch_Chart](https://examples5.ext.net/#/Draw/Basic/Punch_Chart/)
9. [Draw > Basic > Reflection](https://examples5.ext.net/#/Draw/Basic/Reflection/)
10. [Draw > Basic > Rotate_Image](https://examples5.ext.net/#/Draw/Basic/Rotate_Image/)
11. [Draw > Basic > Rotate_Text](https://examples5.ext.net/#/Draw/Basic/Rotate_Text/)
12. [Draw > Basic > Tiger](https://examples5.ext.net/#/Draw/Basic/Tiger/)

#### MVC examples matching `\.DrawContainer\(`

1. [Draw > Basic > Actions](https://mvc5.ext.net/#/Draw_Basic/Actions/)
2. [Draw > Basic > Animation](https://mvc5.ext.net/#/Draw_Basic/Animation/)
3. [Draw > Basic > Animation_Playground](https://mvc5.ext.net/#/Draw_Basic/Animation_Playground/)
4. [Draw > Basic > Australia](https://mvc5.ext.net/#/Draw_Basic/Australia/)
5. [Draw > Basic > Logos](https://mvc5.ext.net/#/Draw_Basic/Logos/)
6. [Draw > Basic > Reflection](https://mvc5.ext.net/#/Draw_Basic/Reflection/)
7. [Draw > Basic > Rotate_Image](https://mvc5.ext.net/#/Draw_Basic/Rotate_Image/)
8. [Draw > Basic > Rotate_Text](https://mvc5.ext.net/#/Draw_Basic/Rotate_Text/)

**Comment by geoffreymcgill** [comment]
Supported in the `7.0.0-preview4` build.
