### ISSUE TITLE
broken: ext-panel's Content inner property

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1755]
This block is a nice approach to allow HTML and Ext.NET code within a component that's derived from an [Ext.container.Container class](https://docs.sencha.com/extjs/7.1.0/classic/Ext.container.Container.html).

Historically though, this has an issue with layouts, where layouts are compromised when using the `Content` block with mixed HTML and Ext.NET components. There are several Ext.NET forum threads discussing in this same subject.
- Google search: [site:forums.ext.net content layout](https://www.google.com/search?q=site%3Aforums.ext.net+content+layout&oq=site%3Aforums.ext.net+content+layout)
- Forum thread: What is the 4.2 version of the fix for this Old Forum Post](

Code having a `Content` block won't prevent the page from rendering at all. Adding any Ext.Net Core tag/component to the block will completely prevent the page from rendering, following the report at #1757.

Reproduced at [editor/basic/overview/index.cshtml#L120-L130](https://github.com/objectdotnet/ext7-sandbox/blob/1e6994ea47e7aed4bd7e57b0e5e9a132dd5538b9/ExtNetCore7-20200325/Pages/examples/editor/basic/overview/index.cshtml#L120-L130)

#### WebForms examples matching `<Content>`

1. [Calendar > Overview > Basic](https://examples5.ext.net/#/Calendar/Overview/Basic/)
2. [Calendar > Overview > Remote_Data](https://examples5.ext.net/#/Calendar/Overview/Remote_Data/)
3. [Chart > Combination > Pareto](https://examples5.ext.net/#/Chart/Combination/Pareto/)
4. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
5. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
6. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
7. [DragDrop > Advanced > Checkbox_Selector](https://examples5.ext.net/#/DragDrop/Advanced/Checkbox_Selector/)
8. [DragDrop > Advanced > DragTracker](https://examples5.ext.net/#/DragDrop/Advanced/DragTracker/)
9. [DragDrop > Tree > Tree_to_Div](https://examples5.ext.net/#/DragDrop/Tree/Tree_to_Div/)
10. [Editor > Basic > Overview](https://examples5.ext.net/#/Editor/Basic/Overview/)
11. [Form > Miscellaneous > Contact_Form](https://examples5.ext.net/#/Form/Miscellaneous/Contact_Form/)
12. [GridPanel > Data_with_Details > Form_Details](https://examples5.ext.net/#/GridPanel/Data_with_Details/Form_Details/)
13. [GridPanel > Data_with_Details > One-to-Many](https://examples5.ext.net/#/GridPanel/Data_with_Details/One-to-Many/)
14. [GridPanel > Saving_Variations > HttpHandler](https://examples5.ext.net/#/GridPanel/Saving_Variations/HttpHandler/)
15. [GridPanel > Saving_Variations > StoreCustomLogic](https://examples5.ext.net/#/GridPanel/Saving_Variations/StoreCustomLogic/)
16. [GridPanel > Saving_Variations > StoreEvents](https://examples5.ext.net/#/GridPanel/Saving_Variations/StoreEvents/)
17. [GridPanel > Saving_Variations > WebService](https://examples5.ext.net/#/GridPanel/Saving_Variations/WebService/)
18. [GridPanel > Update > SqlDataSource](https://examples5.ext.net/#/GridPanel/Update/SqlDataSource/)
19. [Keys > KeyMap > BorderLayout_Regions_Toggle](https://examples5.ext.net/#/Keys/KeyMap/BorderLayout_Regions_Toggle/)
20. [Keys > KeyMap > Map_Inside_Component](https://examples5.ext.net/#/Keys/KeyMap/Map_Inside_Component/)
21. [Keys > KeyNav > Basic](https://examples5.ext.net/#/Keys/KeyNav/Basic/)
22. [Keys > Panel_Keys > _Window_Size](https://examples5.ext.net/#/Keys/Panel_Keys/_Window_Size/)
23. [Layout > Accordion > Original_Header](https://examples5.ext.net/#/Layout/Accordion/Original_Header/)
24. [Layout > FormLayout > With_UserControls](https://examples5.ext.net/#/Layout/FormLayout/With_UserControls/)
25. [Layout > HBoxLayout > Basic](https://examples5.ext.net/#/Layout/HBoxLayout/Basic/)
26. [Layout > VBoxLayout > Basic](https://examples5.ext.net/#/Layout/VBoxLayout/Basic/)
27. [MessageBox > Callout > Custom_Appearance](https://examples5.ext.net/#/MessageBox/Callout/Custom_Appearance/)
28. [MessageBox > Notification > Overview](https://examples5.ext.net/#/MessageBox/Notification/Overview/)
29. [Miscellaneous > Bin_HtmlBin > UserControl](https://examples5.ext.net/#/Miscellaneous/Bin_HtmlBin/UserControl/)
30. [Miscellaneous > Image > Resizable](https://examples5.ext.net/#/Miscellaneous/Image/Resizable/)
31. [Miscellaneous > Mouse_Distance_Sensor > Basic](https://examples5.ext.net/#/Miscellaneous/Mouse_Distance_Sensor/Basic/)
32. [Miscellaneous > Responsive > Basic](https://examples5.ext.net/#/Miscellaneous/Responsive/Basic/)
33. [Miscellaneous > ToolTips > Overview](https://examples5.ext.net/#/Miscellaneous/ToolTips/Overview/)
34. [Panel > Basic > Loader](https://examples5.ext.net/#/Panel/Basic/Loader/)
35. [Portal > Basic > Deluxe](https://examples5.ext.net/#/Portal/Basic/Deluxe/)
36. [TabPanel > Basic > Auto_Height](https://examples5.ext.net/#/TabPanel/Basic/Auto_Height/)
37. [TabPanel > Basic > Show_Hide](https://examples5.ext.net/#/TabPanel/Basic/Show_Hide/)
38. [Toolbar > Menu > Toolbar_Overflow](https://examples5.ext.net/#/Toolbar/Menu/Toolbar_Overflow/)
39. [Window > Basic > Hello_World](https://examples5.ext.net/#/Window/Basic/Hello_World/)
40. [Window > Toast > Overview](https://examples5.ext.net/#/Window/Toast/Overview/)
41. [Window > Toast > Playground](https://examples5.ext.net/#/Window/Toast/Playground/)
42. [XRender > UserControl > Lazy_Load](https://examples5.ext.net/#/XRender/UserControl/Lazy_Load/)

#### MVC examples matching `\.Content\(`

1. [Associations > HasMany > Nested_Loading](https://mvc5.ext.net/#/Associations_HasMany/Nested_Loading/)
2. [Buttons > Basic > ImageButton](https://mvc5.ext.net/#/Buttons_Basic/ImageButton/)
3. [Buttons > Basic > Overview](https://mvc5.ext.net/#/Buttons_Basic/Overview/)
4. [Buttons > Basic > Variations](https://mvc5.ext.net/#/Buttons_Basic/Variations/)
5. [Buttons > ButtonGroup > Overview](https://mvc5.ext.net/#/Buttons_ButtonGroup/Overview/)
6. [Calendar > Overview > Basic](https://mvc5.ext.net/#/Calendar_Overview/Basic/)
7. [Calendar > Overview > Remote_Data](https://mvc5.ext.net/#/Calendar_Overview/Remote_Data/)
8. [DataView > Advanced > Animated](https://mvc5.ext.net/#/DataView_Advanced/Animated/)
9. [DataView > Advanced > Chooser](https://mvc5.ext.net/#/DataView_Advanced/Chooser/)
10. [DataView > Advanced > Grouping](https://mvc5.ext.net/#/DataView_Advanced/Grouping/)
11. [DataView > Advanced > Report](https://mvc5.ext.net/#/DataView_Advanced/Report/)
12. [DataView > Basic > Overview](https://mvc5.ext.net/#/DataView_Basic/Overview/)
13. [DataView > Basic > Paging](https://mvc5.ext.net/#/DataView_Basic/Paging/)
14. [Desktop > Overview](https://mvc5.ext.net/#/Desktop/Overview/)
15. [Desktop > Overview](https://mvc5.ext.net/#/Desktop/Overview/)
16. [DragDrop > Basic > Dom](https://mvc5.ext.net/#/DragDrop_Basic/Dom/)
17. [DragDrop > Basic > Dom](https://mvc5.ext.net/#/DragDrop_Basic/Dom/)
18. [Draw > Basic > Reflection](https://mvc5.ext.net/#/Draw_Basic/Reflection/)
19. [Draw > Basic > Rotate_Image](https://mvc5.ext.net/#/Draw_Basic/Rotate_Image/)
20. [Dynamic > Partial_Rendering > Add_Tab](https://mvc5.ext.net/#/Dynamic_Partial_Rendering/Add_Tab/)
21. [Editor > Basic > Overview](https://mvc5.ext.net/#/Editor_Basic/Overview/)
22. [GridPanel > ColumnModel > RatingColumn](https://mvc5.ext.net/#/GridPanel_ColumnModel/RatingColumn/)
23. [GridPanel > Data_with_Details > Binding](https://mvc5.ext.net/#/GridPanel_Data_with_Details/Binding/)
24. [Keys > KeyMap > BorderLayout_Regions_Toggle](https://mvc5.ext.net/#/Keys_KeyMap/BorderLayout_Regions_Toggle/)
25. [Keys > KeyMap > Map_Inside_Component](https://mvc5.ext.net/#/Keys_KeyMap/Map_Inside_Component/)
26. [Keys > KeyNav > Basic](https://mvc5.ext.net/#/Keys_KeyNav/Basic/)
27. [Layout > HBoxLayout > Basic](https://mvc5.ext.net/#/Layout_HBoxLayout/Basic/)
28. [Layout > VBoxLayout > Basic](https://mvc5.ext.net/#/Layout_VBoxLayout/Basic/)
29. [MessageBox > Basic > Overview](https://mvc5.ext.net/#/MessageBox_Basic/Overview/)
30. [MessageBus > Basic > Shared](https://mvc5.ext.net/#/MessageBus_Basic/Shared/)
31. [Miscellaneous > History > Basic](https://mvc5.ext.net/#/Miscellaneous_History/Basic/)
32. [Miscellaneous > Resizable > Basic](https://mvc5.ext.net/#/Miscellaneous_Resizable/Basic/)
33. [Miscellaneous > Responsive > Basic](https://mvc5.ext.net/#/Miscellaneous_Responsive/Basic/)
34. [Models > Shared](https://mvc5.ext.net/#/Models/Shared/)
35. [Panel > Basic > Loader](https://mvc5.ext.net/#/Panel_Basic/Loader/)
36. [Panel > BodyMask > Custom_Mask](https://mvc5.ext.net/#/Panel_BodyMask/Custom_Mask/)
37. [Panel > Miscellaneous > Bubble_Panel](https://mvc5.ext.net/#/Panel_Miscellaneous/Bubble_Panel/)
38. [Window > Basic > Hello_World](https://mvc5.ext.net/#/Window_Basic/Hello_World/)
39. [Window > Toast > Overview](https://mvc5.ext.net/#/Window_Toast/Overview/)

**Comment by AndreyChechel** [comment]
The issue has been fixed. Now component tags support inner `<content>` tag with any content including Ext.NET components.

For example, for the following markup:
```cshtml
<ext-panel title="Panel 1">
    <content>
        <div>
            <input value="Raw Content Input" />
        </div>
        <div>
            <ext-button text="Raw Content Button" />
        </div>
    </content>

    <items>
        <ext-button text="Panel.Items Button" />
    </items>
</ext-panel>
```

the following output will be generated:
```html
    <script type="text/javascript">
        Ext.onReady(function() {
            // ...
            Ext.create("Ext.button.Button",{id:"ctl01",renderTo:"App.ctl01_Container",text:"Raw Content Button"});
            Ext.create("Ext.panel.Panel",{id:"ctl02",renderTo:"App.ctl02_Container",items:[{xtype:"button",text:"Panel.Items Button"}],title:"Panel 1"});
        });
    </script>

    <!-- ... -->

    <div id="App.ctl02_Container">
            <div>
                <input value="Raw Content Input" />
            </div>
            <div>
                <div id="App.ctl01_Container"></div>
            </div>
        </div>
```

which will be rendered as shown below:
![image](https://user-images.githubusercontent.com/16582701/83563434-ce315780-a523-11ea-98bd-1fdbf5c75264.png)
