### ISSUE TITLE
setTitle of non-rendered panel hides its tools

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#176]
http://forums.ext.net/showthread.php?23949
http://www.sencha.com/forum/showthread.php?258841

**Update:** Sencha issue _EXTJS-9159_ allegedly fixed in ExtJS 4.2.1.744 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9159_ allegedly fixed in ExtJS 4.2.1.744 release.
