### ISSUE TITLE
syntax: ext-editor's shadow boolean property case-sensitive

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1760]
The `ext-editor` component's `Shadow` boolean property does not accept an `False` at its taghelper property.

This used to be supported in Ext.NET down to v5, so that `false`, `False`, `FalSE`, `True`, `true`, and so on, would all be accepted as true/false values.

Interestingly enough, as the component references, properties and inner blocks are allowed case-insensitive, the false/true values are not, as they used to in WebForms version of Ext.NET.

This probably is an issue pertaining any boolean property in Ext.NET Core.

Reproduced at [editor/basic/overview/index.cshtml#L206](https://github.com/objectdotnet/ext7-sandbox/blob/1e6994ea47e7aed4bd7e57b0e5e9a132dd5538b9/ExtNetCore7-20200325/Pages/examples/editor/basic/overview/index.cshtml#L206)

#### WebForms examples matching `="(False|True)"` (or, `="False"` or `="True"`)

1. [Editor > Basic > Overview](https://examples5.ext.net/#/Editor/Basic/Overview/)
2. [Form > DropDownField > Overview](https://examples5.ext.net/#/Form/DropDownField/Overview/)
3. [Form > DropDownField > ValueText_Mode](https://examples5.ext.net/#/Form/DropDownField/ValueText_Mode/)
4. [GridPanel > Data_Presentation > MultiCombo_Map](https://examples5.ext.net/#/GridPanel/Data_Presentation/MultiCombo_Map/)
5. [GridPanel > Data_with_Details > One-to-Many](https://examples5.ext.net/#/GridPanel/Data_with_Details/One-to-Many/)
6. [GridPanel > FilterHeader > Overview](https://examples5.ext.net/#/GridPanel/FilterHeader/Overview/)
7. [GridPanel > FilterHeader > Remote](https://examples5.ext.net/#/GridPanel/FilterHeader/Remote/)
8. [GridPanel > Plugins > GridFilters_Local](https://examples5.ext.net/#/GridPanel/Plugins/GridFilters_Local/)
9. [Layout > Accordion > Basic_in_Markup](https://examples5.ext.net/#/Layout/Accordion/Basic_in_Markup/)
10. [Layout > BorderLayout > Complex_in_Markup](https://examples5.ext.net/#/Layout/BorderLayout/Complex_in_Markup/)
11. [Panel > Miscellaneous > Bubble_Panel](https://examples5.ext.net/#/Panel/Miscellaneous/Bubble_Panel/)
12. [TreePanel > Basic > Checkbox_Nodes](https://examples5.ext.net/#/TreePanel/Basic/Checkbox_Nodes/)
13. [TreePanel > Basic > Editors](https://examples5.ext.net/#/TreePanel/Basic/Editors/)
14. [TreePanel > List > Overview](https://examples5.ext.net/#/TreePanel/List/Overview/)

**Comment by AndreyChechel** [comment]
According to the [docs](https://docs.sencha.com/extjs/7.0.0/classic/Ext.Editor.html#cfg-shadow):
> shadow : Boolean / String 
>
> "sides" for sides/bottom only, "frame" for 4-way shadow, and "drop" for bottom-right shadow.
> Defaults to: 'frame'

Since the actual type of `Editor.shadow` is `Union<bool, string>`, the tag helper property was split to:
- `bool shadow` - this one will accept only a legal C# boolean value (`true`/`false`)
- `string shadowAsString` - this one will accept possible string values (`sides`/`frame`/`drop`)
