### ISSUE TITLE
absent: TreePanel` DirectEvents such as ItemClick

### ISSUE THREAD

**Issue by zgcgwin** [extnet/Ext.NET#1770]
Some direct events / listeners of TreePanel are missing.

**Comment by geoffreymcgill** [comment]
Confirmed. The issue related to the missing DirectEvents and Listeners has been fixed and will be available in the `7.0.0-preview3` release, which is being released later today. 

<img width="316" alt="Screenshot 2020-05-11 13 48 24" src="https://user-images.githubusercontent.com/62210/81605124-3d38e780-938e-11ea-8e78-5333054e8293.png">
