### ISSUE TITLE
Broken: ext-gridpanel's Features block

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1781]
Found: 7.0.0-preview4
Ext.NET forum thread: [GridPanel - DirectEvents <RowBodyClic> does not work, please help.](https://forums.ext.net/showthread.php?62920-GridPanel-DirectEvents-lt-RowBodyClic-gt-does-not-work-please-help)

There is no `Features` block to GridPanel, and the exported property allows strange input. Intellisense suggests a RowBody interface and several RowBody event listeners and direct events (instead of the feature itself). This setting will probably need manual review.

#### WebForms examples matching `GridPanel` and `Features`

1. [DragDrop > Advanced > Example3](https://examples5.ext.net/#/DragDrop/Advanced/Example3/)
2. [Form > DropDownField > Overview](https://examples5.ext.net/#/Form/DropDownField/Overview/)
3. [GridPanel > Commands > Group_Command](https://examples5.ext.net/#/GridPanel/Commands/Group_Command/)
4. [GridPanel > Commands > Image_Command](https://examples5.ext.net/#/GridPanel/Commands/Image_Command/)
5. [GridPanel > DataSource_Controls > LinqDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/LinqDataSource/)
6. [GridPanel > DataSource_Controls > ObjectDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/ObjectDataSource/)
7. [GridPanel > DataSource_Controls > SqlDataSource](https://examples5.ext.net/#/GridPanel/DataSource_Controls/SqlDataSource/)
8. [GridPanel > Infinite_Scrolling > Forum_topics](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Forum_topics/)
9. [GridPanel > Locking_Grid > GroupingSummary](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary/)
10. [GridPanel > Locking_Grid > GroupingSummary_with_group_headers](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary_with_group_headers/)
11. [GridPanel > Miscellaneous > Grouping](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping/)
12. [GridPanel > Miscellaneous > Grouping_TotalRow](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping_TotalRow/)
13. [GridPanel > Miscellaneous > JSONP_Proxy](https://examples5.ext.net/#/GridPanel/Miscellaneous/JSONP_Proxy/)
14. [GridPanel > Paging_and_Sorting > DirectMethod](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/DirectMethod/)
15. [GridPanel > Paging_and_Sorting > Page](https://examples5.ext.net/#/GridPanel/Paging_and_Sorting/Page/)
16. [GridPanel > Plugins > GroupingSummary](https://examples5.ext.net/#/GridPanel/Plugins/GroupingSummary/)
17. [GridPanel > Plugins > GroupPaging](https://examples5.ext.net/#/GridPanel/Plugins/GroupPaging/)
18. [GridPanel > Plugins > Remote_GroupSummary](https://examples5.ext.net/#/GridPanel/Plugins/Remote_GroupSummary/)
19. [GridPanel > Plugins > Summary](https://examples5.ext.net/#/GridPanel/Plugins/Summary/)
20. [Kitchen_Sink > GridPanels > Grouped_GridPanel](https://examples5.ext.net/#/Kitchen_Sink/GridPanels/Grouped_GridPanel/)

#### MVC examples matching `GridPanel` and `Features`

1. [DragDrop > Advanced > Example3](https://mvc5.ext.net/#/DragDrop_Advanced/Example3/)
2. [GridPanel > Commands > Group_Command](https://mvc5.ext.net/#/GridPanel_Commands/Group_Command/)
3. [GridPanel > Commands > Image_Command](https://mvc5.ext.net/#/GridPanel_Commands/Image_Command/)
4. [GridPanel > Infinite_Scrolling > Forum_topics](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Forum_topics/)
5. [GridPanel > Plugins > GroupingSummary](https://mvc5.ext.net/#/GridPanel_Plugins/GroupingSummary/)
6. [Kitchen > Sink_GridPanels > Grouped](https://mvc5.ext.net/#/Kitchen_Sink_GridPanels/Grouped/)

**Comment by AndreyChechel** [comment]
The `<features>` inner tag has been supported in `7.0.0-preview4`.

Also confirming Ext JS issue with the following way of configuration:
```
features="new FeatureType[] { FeatureType.RowBody }"
```

**Comment by geoffreymcgill** [comment]
We are investigating why Ext JS does not support the string array configuration option.

**Comment by fabriciomurta** [comment]
The following override maps the string values into corresponding `ftype` objects for any string specified in the array of features.

```js
Ext.define('gh1781', {
    override: 'Ext.view.Table',
    constructFeatures: function () {
        var me = this,
            features = me.features;

        if (Ext.isArray(features)) {
            for (var i = 0; i < features.length; i++) {
                if (Ext.isString(features[i])) {
                    features[i] = { ftype: features[i] };
                }
            }
        }

        return me.callParent(arguments);
    }
})
```

This issue can't be explored in Ext.NET 5 unless you specify the features as a custom config or straight from javascript. There's no mechanism in Ext.NET 5 that emits the list as a list of strings. So there's not much sense in fixing the issue for Ext.NET 5.x.

Vanilla Ext JS fails according to this Ext JS Fiddle: [ISSUE WITH GRID FEATURES AS EXT.ENUM.FEATURE](https://fiddle.sencha.com/#view/editor&fiddle/36ph).

**Comment by fabriciomurta** [comment]
Sencha has implemented support for the string array configuration as of ExtJS 7.3.1, released Oct 21st.

**Comment by fabriciomurta** [comment]
Added the **sencha** label as part of the issue was due to unsupported documented features from sencha that was fixed (and what's on the documentation became functional, documentation didn't change).
