### ISSUE TITLE
absent: TreeStore's Node object

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1784]
Found: Ext.NET 7.0.0-preview3

In Ext.NET we have the `Ext.Net.Node` class to allow nicely creating nodes and assigning them to a TreePanel.

Ext.NET 7 misses the implementation (probably because Ext JS documentation does not clearly define one). Using this instead allows filling a tree panel:

```csharp
public class ExampleTreeNode
{
    public ExampleTreeNode()
    {
        Children = new List<ExampleTreeNode>();
    }

    public string Text { get; set; }
    public List<ExampleTreeNode> Children { get; set; }
    public bool Leaf { get; set; }
}
```

In code behind (model), an structure containing the tree nodes could be built with something like this:
```csharp
public TreeStore ExamplesTree;

public void OnGet()
{
    ExamplesTree = new TreeStore();

    var recipes = new List<ExampleTreeNode>();

    for (var i = 1; i <= 4; i++)
    {
        var recipe = new ExampleTreeNode()
        {
            Text = "Recipe " + i + " ingredients",
            Leaf = false,
        };

        foreach (var ingredient in new string[] { "Flour", "Wheat", "Sugar", "Eggs" })
        {
            recipe.Children.Add(new ExampleTreeNode()
            {
                Text = ingredient,
                Leaf = true
            });
        }
        recipes.Add(recipe);
    }

    ExamplesTree.Root = new ExampleTreeNode()
    {
        Text = "Recipes",
        Children = recipes,
        Leaf = false
    };
}
```

Then in the view, having the tree store saved as `ExamplesTree` in the model, a Tree Panel could be built like this:

```xml
<ext-treePanel width="500" height="600" rootVisible="false">
    <store>
        <ext-treeStore model="Model.ExamplesTree" />
    </store>
</ext-treePanel>
```

But having the right field names in the class required to reference to Ext JS documentation. Such a class or struct would be handy to have in Ext.NET 7.

#### WebForms examples matching `TreeStore`

1. [Desktop > Introduction > Overview](https://examples5.ext.net/#/Desktop/Introduction/Overview/)
2. [DragDrop > Tree > Tree_to_Div](https://examples5.ext.net/#/DragDrop/Tree/Tree_to_Div/)
3. [Kitchen_Sink > TreePanels > Basic_TreePanel](https://examples5.ext.net/#/Kitchen_Sink/TreePanels/Basic_TreePanel/)
4. [Toolbar > Breadcrumb > Overview](https://examples5.ext.net/#/Toolbar/Breadcrumb/Overview/)
5. [TreePanel > Advanced > Buffer_Rendered_TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/Buffer_Rendered_TreeGrid/)
6. [TreePanel > Advanced > Image_Organizer](https://examples5.ext.net/#/TreePanel/Advanced/Image_Organizer/)
7. [TreePanel > Advanced > Locking_Buffer_Rendered_TreeGrid](https://examples5.ext.net/#/TreePanel/Advanced/Locking_Buffer_Rendered_TreeGrid/)
8. [TreePanel > Advanced > Remote_Mode_with_Service](https://examples5.ext.net/#/TreePanel/Advanced/Remote_Mode_with_Service/)
9. [TreePanel > Basic > Custom_Drop_Logic](https://examples5.ext.net/#/TreePanel/Basic/Custom_Drop_Logic/)
10. [TreePanel > Basic > DragDrop_Between_Trees](https://examples5.ext.net/#/TreePanel/Basic/DragDrop_Between_Trees/)
11. [TreePanel > Basic > SiteMap](https://examples5.ext.net/#/TreePanel/Basic/SiteMap/)
12. [TreePanel > List > Built_in_CodeBehind](https://examples5.ext.net/#/TreePanel/List/Built_in_CodeBehind/)
13. [TreePanel > List > Built_in_Markup](https://examples5.ext.net/#/TreePanel/List/Built_in_Markup/)
14. [TreePanel > List > Overview](https://examples5.ext.net/#/TreePanel/List/Overview/)
15. [TreePanel > List > Simple](https://examples5.ext.net/#/TreePanel/List/Simple/)
16. [TreePanel > Loaders > Page](https://examples5.ext.net/#/TreePanel/Loaders/Page/)
17. [TreePanel > Loaders > Using_Handler](https://examples5.ext.net/#/TreePanel/Loaders/Using_Handler/)
18. [TreePanel > Loaders > WebService](https://examples5.ext.net/#/TreePanel/Loaders/WebService/)
19. [TreePanel > Loaders > Xml_File_Loading](https://examples5.ext.net/#/TreePanel/Loaders/Xml_File_Loading/)

**Comment by AndreyChechel** [comment]
@fabriciomurta - based on Ext JS documentation for [TreeStore.root](https://docs.sencha.com/extjs/7.2.0/classic/Ext.data.TreeStore.html#cfg-root), it can accept an object of [NodeInterface](https://docs.sencha.com/extjs/7.2.0/classic/Ext.data.NodeInterface.html) type.
Will it work for your scenarios?

The following sample demonstrates how it can be used:

```cshtml
<ext-treePanel width="500"
                height="600"
                rootVisible="false"
                storeModel="Model.ExamplesTree" />
```

```cs
public TreeStore ExamplesTree;

public void OnGet()
{
    ExamplesTree = new TreeStore();

    var recipes = new List<NodeInterface>();

    for (var i = 1; i <= 4; i++)
    {
        var recipe = new NodeInterface()
        {
            Text = "Recipe " + i + " ingredients",
            Leaf = false,
        };

        foreach (var ingredient in new string[] { "Flour", "Wheat", "Sugar", "Eggs" })
        {
            recipe.Children.Add(new NodeInterface()
            {
                Text = ingredient,
                Leaf = true
            });
        }
        recipes.Add(recipe);
    }

    ExamplesTree.Root = new NodeInterface()
    {
        Text = "Recipes",
        Children = recipes,
        Leaf = false
    };
}
```
