### ISSUE TITLE
absent: ext-gridpanel's group* listeners (and direct events)

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1785]
Found: 7.0.0-preview3
Ext.NET forum thread: [Grouping in the GridPanel and Icon Summary (Material)](https://forums.ext.net/showthread.php?62926)

There are no `group*` events to the `ext-gridpanel` component, even though they should be available when using the grouping feature.

According to Ext.NET 5, the [listeners in Ext.grid.feature.Grouping.events](https://docs.sencha.com/extjs/7.2.0/classic/Ext.grid.feature.Grouping.html#events) should be available to both the grid panel and its view.

*Note:* Adding the listener block to the feature definition does not work, the feature just enables the events in the grid and view.

#### WebForms examples matching `ext:Grouping`

1. [Form > DropDownField > Overview](https://examples5.ext.net/#/Form/DropDownField/Overview/)
2. [GridPanel > Commands > Group_Command](https://examples5.ext.net/#/GridPanel/Commands/Group_Command/)
3. [GridPanel > Commands > Image_Command](https://examples5.ext.net/#/GridPanel/Commands/Image_Command/)
4. [GridPanel > Infinite_Scrolling > Forum_topics](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Forum_topics/)
5. [GridPanel > Locking_Grid > GroupingSummary](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary/)
6. [GridPanel > Locking_Grid > GroupingSummary_with_group_headers](https://examples5.ext.net/#/GridPanel/Locking_Grid/GroupingSummary_with_group_headers/)
7. [GridPanel > Miscellaneous > Grouping](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping/)
8. [GridPanel > Miscellaneous > Grouping_TotalRow](https://examples5.ext.net/#/GridPanel/Miscellaneous/Grouping_TotalRow/)
9. [GridPanel > Plugins > GroupingSummary](https://examples5.ext.net/#/GridPanel/Plugins/GroupingSummary/)
10. [GridPanel > Plugins > GroupPaging](https://examples5.ext.net/#/GridPanel/Plugins/GroupPaging/)
11. [GridPanel > Plugins > Remote_GroupSummary](https://examples5.ext.net/#/GridPanel/Plugins/Remote_GroupSummary/)
12. [Kitchen_Sink > GridPanels > Grouped_GridPanel](https://examples5.ext.net/#/Kitchen_Sink/GridPanels/Grouped_GridPanel/)

**Comment by AndreyChechel** [comment]
The missing listeners and direct events have been added.
