### ISSUE TITLE
absent: ext-store's Listeners block

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1787]
Found: 7.0.0-preview3 (and 7.0.0-preview4-2020-06-19)

The `Ext.data.Store` component representation in Ext.NET 7 is missing the `Listeners` block. It should, somehow, support [the events listed in Ext JS documentation for Ext.data.Store](https://docs.sencha.com/extjs/7.2.0/classic/Ext.data.Store.html#events).

The following example uses the store's `GroupChange` event (which, in turn, requires the grid Grouping feature to be triggered from user interaction -- when the user ungroups the grid or groups by another column).

**Comment by AndreyChechel** [comment]
Implemented in `7.0.0`
