### ISSUE TITLE
Broken: ext-window items doesn't accept an ext-panel component

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1789]
Found: Ext.NET.7.0.0-preview4_2020-07-03
This code:

```xml
<ext-window id="WindowBrowser" hidden="false" width="650" height="400">
    <items>
        <ext-panel title="myPanel" width="500" height="250">
        </ext-panel>
    </items>
</ext-window>
```

Results in the following exception triggered on render: `LayoutException: Unexpected element 'PanelTagHelper' nested into 'WindowTagHelper'.`

**Comment by AndreyChechel** [comment]
Fixed in `Ext.NET.7.0.0-preview4`
