### ISSUE TITLE
Loader loadMask doesn't appear if container is collapsed initially

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#179]
http://forums.ext.net/showthread.php?24030
http://www.sencha.com/forum/showthread.php?259383

**Update:** Sencha issue _EXTJS-9218_ allegedly fixed in ExtJS 4.2.1.744 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9218_ allegedly fixed in ExtJS 4.2.1.744 release.
