### ISSUE TITLE
broken: ext-cartesianChart cannot be added in ext-panel's Items

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1798]
Found: Ext.NET 7.0.0-preview4_2020-07-18.

The `ext-cartesianChart` component is not being accepted within an `ext-panel`'s `items` block. The issue is as simple as:

```
<ext-panel />
  <items>
    <ext-cartesianChart />
  </items>
</ext-panel>
```

It was pointed by @AndreyChechel during our Monday meeting that just using `ext-container` instead of `ext-panel` works around the issue.

**Comment by AndreyChechel** [comment]
Fixed in `7.0.0-preview4`
