### ISSUE TITLE
CSS issue in IE if wrap grid column header text

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#180]
http://forums.ext.net/showthread.php?24039
http://www.sencha.com/forum/showthread.php?259426

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-9227.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-9227_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.3 release. Issue is acknowledged by Sencha under ID _EXTJS-9227_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-9227_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-9227_.
