### ISSUE TITLE
absent: customConfig inner block

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1800]
Found: Ext.NET 7.0.0-preview4_2020-07-18.

There is no equivalent to Ext.NET 5's `<CustomConfig>` block in Ext.NET 7. Whenever code that is not feasible to be expressed via Ext.NET API is necessary, this tag can be used in legacy.

This is an specialization of issue #1712, which handles the output of unknown properties as Ext.NET custom config items with limited output control. CustomConfig blocks enhance the feature by allowing different ways to specify the custom config items, with even value nesting support.

#### WebForms examples matching `CustomConfig`

1. [Associations > HasMany > Lazy_Load](https://examples5.ext.net/#/Associations/HasMany/Lazy_Load/)
2. [Calendar > Overview > Basic](https://examples5.ext.net/#/Calendar/Overview/Basic/)
3. [Calendar > Overview > Remote_Data](https://examples5.ext.net/#/Calendar/Overview/Remote_Data/)
4. [ColorPicker > Advanced > Components](https://examples5.ext.net/#/ColorPicker/Advanced/Components/)
5. [Combination_Samples > Applications > Feed_Viewer](https://examples5.ext.net/#/Combination_Samples/Applications/Feed_Viewer/)
6. [DataView > Advanced > Chooser](https://examples5.ext.net/#/DataView/Advanced/Chooser/)
7. [DragDrop > Basic > Example3](https://examples5.ext.net/#/DragDrop/Basic/Example3/)
8. [DragDrop > Grid > Field_to_Grid](https://examples5.ext.net/#/DragDrop/Grid/Field_to_Grid/)
9. [Draw > Basic > Tiger](https://examples5.ext.net/#/Draw/Basic/Tiger/)
10. [Editor > Basic > Overview](https://examples5.ext.net/#/Editor/Basic/Overview/)
11. [Element > Basic > Layer](https://examples5.ext.net/#/Element/Basic/Layer/)
12. [Element > Basic > Overview](https://examples5.ext.net/#/Element/Basic/Overview/)
13. [Form > ComboBox > Linked_Combos_In_Grid](https://examples5.ext.net/#/Form/ComboBox/Linked_Combos_In_Grid/)
14. [Form > DateField > From-To_Range](https://examples5.ext.net/#/Form/DateField/From-To_Range/)
15. [Form > TextField > Password_Validation](https://examples5.ext.net/#/Form/TextField/Password_Validation/)
16. [Form > Triggers > Trigger_with_Dialog_Editor](https://examples5.ext.net/#/Form/Triggers/Trigger_with_Dialog_Editor/)
17. [GridPanel > FilterHeader > Custom_Field](https://examples5.ext.net/#/GridPanel/FilterHeader/Custom_Field/)
18. [GridPanel > Infinite_Scrolling > Remote_Filter](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Remote_Filter/)
19. [GridPanel > Infinite_Scrolling > Tuner](https://examples5.ext.net/#/GridPanel/Infinite_Scrolling/Tuner/)
20. [Layout > FormLayout > Overview](https://examples5.ext.net/#/Layout/FormLayout/Overview/)
21. [MessageBox > Callout > Delegation](https://examples5.ext.net/#/MessageBox/Callout/Delegation/)
22. [MessageBus > Basic > Simple](https://examples5.ext.net/#/MessageBus/Basic/Simple/)
23. [Miscellaneous > Responsive > Basic](https://examples5.ext.net/#/Miscellaneous/Responsive/Basic/)
24. [Panel > Miscellaneous > Bubble_Panel](https://examples5.ext.net/#/Panel/Miscellaneous/Bubble_Panel/)
25. [Toolbar > Plugins > ToolbarDroppable](https://examples5.ext.net/#/Toolbar/Plugins/ToolbarDroppable/)
26. [TreePanel > Loaders > WebService](https://examples5.ext.net/#/TreePanel/Loaders/WebService/)

#### MVC examples matching `CustomConfig`

1. [Calendar > Overview > Basic](https://mvc5.ext.net/#/Calendar_Overview/Basic/)
2. [Calendar > Overview > Remote_Data](https://mvc5.ext.net/#/Calendar_Overview/Remote_Data/)
3. [DragDrop > Advanced > Example3](https://mvc5.ext.net/#/DragDrop_Advanced/Example3/)
4. [DragDrop > Basic > Example3](https://mvc5.ext.net/#/DragDrop_Basic/Example3/)
5. [DragDrop > Grid > Field_to_Grid](https://mvc5.ext.net/#/DragDrop_Grid/Field_to_Grid/)
6. [Editor > Basic > Overview](https://mvc5.ext.net/#/Editor_Basic/Overview/)
7. [Element > Basic > Layer](https://mvc5.ext.net/#/Element_Basic/Layer/)
8. [Element > Basic > Overview](https://mvc5.ext.net/#/Element_Basic/Overview/)
9. [Form > ComboBox > Linked_Combos_In_Grid](https://mvc5.ext.net/#/Form_ComboBox/Linked_Combos_In_Grid/)
10. [Form > Login > Auto_Complete](https://mvc5.ext.net/#/Form_Login/Auto_Complete/)
11. [Form > MultiSelect > Overview](https://mvc5.ext.net/#/Form_MultiSelect/Overview/)
12. [Getting > Started > Component_Overview](https://mvc5.ext.net/#/Getting_Started/Component_Overview/)
13. [GridPanel > Infinite_Scrolling > Remote_Filter](https://mvc5.ext.net/#/GridPanel_Infinite_Scrolling/Remote_Filter/)
14. [GridPanel > Paging_and_Sorting > Multiple_Sorting_Local](https://mvc5.ext.net/#/GridPanel_Paging_and_Sorting/Multiple_Sorting_Local/)
15. [MessageBus > Basic > Simple](https://mvc5.ext.net/#/MessageBus_Basic/Simple/)
16. [Miscellaneous > Responsive > Basic](https://mvc5.ext.net/#/Miscellaneous_Responsive/Basic/)
17. [Panel > Miscellaneous > Bubble_Panel](https://mvc5.ext.net/#/Panel_Miscellaneous/Bubble_Panel/)

**Comment by AndreyChechel** [comment]
The `<customConfig>` inner element has been implemented, see sample below:

```cshtml
<ext-button text="Test">
    <customConfig>
        <ext-parameter name="width" value="220px" />
        <ext-parameter name="height" value="50" mode="Raw" />
        <ext-parameter name="disabled" valueModel="true" />
    </customConfig>
</ext-button>
```

output:
```js
{id:"ctl01",renderTo:"App.ctl01_Container",text:"Test",width:"220px",height:50,disabled:true}
```

In addition to the `<customConfig>` element, support of custom `x-` prefixed attributes have been introduced. See the configuration equivalent to the above one, but implemented using new attributes:

```cshtml
<ext-button text="Test" x-width="220px" x:raw-height="50" x:model-disabled="true" />
```

The `x-` prefixed attributes are forcibly emitted without processing and running through the Ext.NET Core pipeline. There are the following `x-` attributes kinds:
- `x-custom` - accepts a `string` value, emits `custom: "stringVvalue"`
- `x:raw-custom` - accepts a `string` value, emits `custom: stringValue` (no quotes)
- `x:model-custom` - accepts an `object`, emits `custom: <serialized_object>`
