### ISSUE TITLE
Page rendering is silently inhibited when a component's required value is missing

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1824]
The following code:

```cshtml
<ext-container
        Layout="VBox"
        Height="900">
        <defaults>
            <ext-parameter Name="margin" Mode="Value" />
        </defaults>
</ext-container>
```

Will prevent the whole page body to be rendered (including the closing HTML tag) in a page due to the missing required `Value` (or `valueAsString`, etc) parameter. But no message or error output/exception is thrown at all. The page simply stops rendering at the point it starts processing tag helpers.

To address the issue, add the missing property:

```cshtml
<ext-container
        Layout="VBox"
        Height="900">
        <defaults>
            <ext-parameter Name="margin" valueAsString="0 0 24 0" Mode="Value" />
        </defaults>
</ext-container>
```

**Comment by AndreyChechel** [comment]
Fixed in `7.0.0`
