### ISSUE TITLE
absent: ext-*axis Position property's "gauge" value

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1826]
Found: 7.0.0-rc-202009-14

In the following sample: [Charts > Gauge > Basic 1](https://examples5.ext.net/#/Chart/Gauge/Basic_1/)

The `Position="Gauge"` bit in lines 81, 114 and 148 are not supported by Ext.NET 7 when converting the sample.

We'll probably need to shim it, as the documentation in Ext JS does not state is a valid setting (while it is -- when the chart is a gauge type).

Documentation entry: [Ext.chart.axis.Axis.position](https://docs.sencha.com/extjs/7.2.0/classic/Ext.chart.axis.Axis.html#cfg-position)

The `gauge` value is valid when the `position` config is used under `Ext.chart.axis.sprite.Axis.renderTicks()`, which is not easily accessbile thru Ext JS documentation but if the related class is searched you can find [Ext.chart.axis.sprite.Axis.position](https://docs.sencha.com/extjs/7.2.0/classic/Ext.chart.axis.sprite.Axis.html#cfg-position).

The `Ext.chart.axis.sprite.Axis` class is marked private in Ext JS docs and the setting relation is not easily correlated to the `Ext.chart.axis.Axis` class.

**Comment by AndreyChechel** [comment]
Implemented in `7.0.0`
