### ISSUE TITLE
absent: customConfig support on events and events' ext-eventMask

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1837]
The following Ext.NET markup:

```cshtml
<ext-button Text="Run" Width="75" x-thisWorks="yes">
    <DirectEvents>
        <Click pageHandler="DoSomething" method="POST" x-thisWorksEvent="no (event)">
            <EventMask>
                <ext-eventMask showMask="true" x:raw-thisWorksEventMask="no (event's eventMask)" />
            </EventMask>
        </Click>
    </DirectEvents>
</ext-button>

```

Results in:

```js
{
    directEvents: {
        click: {
            fn: function (item, e) {
                Ext.net.directRequest({
                    action: "click",
                    cleanRequest: true,
                    eventMask: {
                        showMask: true
                    },
                    method: "POST",
                    url: "/samples/events/directevents/duration_messages/DoSomething"
                });
            }
        }
    },
    width: 75,
    xtype: "button",
    text: "Run",
    thisWorks: "yes"
}
```

Notice only the `thisWorks` custom config associated with the button component itself is output to the js configuration object. The ones in the event and event mask are ignored.

In fact, by looking at intellisense from Visual Studio, it suggests the inner componets do not support the `x-custpom` syntax:

![image](https://user-images.githubusercontent.com/10730372/97908580-a853ed00-1d25-11eb-9029-197fb9db9f58.png)

This applies also to the `x:raw-`, `x:model-` prefixes and also the inner `customConfig` blocks.

**Comment by AndreyChechel** [comment]
It was decided to add `x-*` attributes (but not an inner `<customConfig>` element) for the mentioned tags, plus a few more.
Implemented in `7.2.0`.
