### ISSUE TITLE
Examples For  Classic V7.2.0 

### ISSUE THREAD

**Issue by SerdarHelli** [extnet/Ext.NET#1849]
Hey , I am new in Ext.Net . I want to learn Ext.Net. But I cant find enough examples. So can someone share with me Model Binding for registery in ext.net mvc classsic v7.2.0 ? I need examples .

**Comment by fabriciomurta** [comment]
Hello! Have you browsed our [Examples Explorer](https://examples.ext.net/)?

I'm not really sure what you mean with model binding, can you elaborate on that? Is it anything you see in any of our [WebForms v5 examples explorer](https://examples5.ext.net/) or maybe [MVC v5 examples explorer](https://mvc5.ext.net/)?

**Comment by SerdarHelli** [comment]
Thanks, I handled it.
