### ISSUE TITLE
Theme Spotless + MenuItem Icon Topped

### ISSUE THREAD

**Issue by AleBros** [extnet/Ext.NET#1851]
I noticed there is a problem in the spotless theme when using menutiems.
Menuitem's icons are all positioned on top (6px).
It seems that menuitem does not act as container for the icon and the icon will be positioned in the containing panel.

**_Sidebar.cshtml**
```
<ext-container region="West"
               cls="sidebar"
               width="240"
               scrollable="true"
               layout="Accordion"
               paddingAsString="20">
 
    <items>
        @{
            foreach (var item in NavData.Items)
            {
                <ext-panel title="@item.Name">
                    <items>
                                @if (item.Items != null && item.Items.Count > 0)
                                {
                                    foreach (var i in item.Items)
                                    {
                                        <ext-menuItem text="@i.Name" href="@i.Path" iconCls = "x-md @i.IconCls" />
                                    }
                                }
                    </items>
                </ext-panel>
            }
        }
    </items>        
</ext-container>
```

Overriding the forllowing style it is acceptable, even if it is (6px) higher.

 ```
- .x-menu-item-icon-default
 -  top:6px
```

Is this the correct use of menuitem, right?

**Comment by geoffreymcgill** [comment]
Thanks for letting us know about this Spotless issue and the sample demonstrating how to reproduce. 

We will investigate and try to fix right away as well as provide a temp work around.

**Comment by AleBros** [comment]
I suggest to change 
`top: 6px `
with 
`padding-top: 6px `

for this specific purpose.

**Comment by AleBros** [comment]
I tryed to handle it with this custom css
`.x-menu-item-icon-default {
    top: unset !important;
    padding-top: 6px;
}
`

Sadly this impacts over the GridPanel's Field Chooser checkboxes which become invisible

**Comment by fabriciomurta** [comment]
It seems we shouldn't have allowed `ext-menuItem` within ordinary panels. They are meant to be sub items of containers supporting the display of menus, like [Ext.NET 5's MenuPanel](https://examples5.ext.net/#/MessageBox/Notification/Client-Side_Notification/). In fact, even in triton theme, I tried the same set up you did in Ext.NET 5 (nesting `menuItems` as a `Panel` items without a specific `Menu` block), and the same icon superposition result happened even in Triton theme.

As Ext.NET 7 still has no support to the Ext.NET 5 `MenuPanel` UX (#1741), the way to go here, is either envelope the `ext-menuItem` components around a menu, or build the menu items as side-by side labels with the icons.

If you want to discuss alternatives about this, I suggest we move the discussion to [the Ext.NET forums](https://forums.ext.net/) where we have a comprehensive archive of discussions on questions and solutions to scenarios with Ext.NET.

**Comment by fabriciomurta** [comment]
I'm closing this but feel free to continue discussion if you have reasons to support that this scenario should work. We'd love to hear from you in the forums!
