### ISSUE TITLE
Request Failure Status Code 200 Status Text BADRESPONSE: Unexpected token '<'

### ISSUE THREAD

**Issue by viveknuna** [extnet/Ext.NET#1855]
I get the below error when I click on the ImageButton. It works without error when I run the application using visual studio. It also works without error in one machine. But it is giving this error only in another machine.

[https://stackoverflow.com/questions/66898634/request-failure-status-code-200-status-text-badresponse-unexpected-token](url)

I have deployed the same code on both machines. I have added logs in the button click event also, so it is failing before the button click event only.

**ASPX:**

```
<tr>
    <td class="formtdlt">
        <span class="mandatorystar">*</span>Company
    </td>
    <td class="formtdrt" style="width: 40%">
        <ext:Store ID="clstrCompany" runat="server">
            <Reader>
                <ext:JsonReader>
                    <Fields>
                        <ext:RecordField Name="Text" Type="String" />
                        <ext:RecordField Name="Value" Type="Int" />
                    </Fields>
                </ext:JsonReader>
            </Reader>
        </ext:Store>
        <ext:ComboBox ID="clcmbCompany" runat="server" StoreID="clstrCompany" AllowBlank="false" Resizable="true"
            DisplayField="Text" ValueField="Value" SelectOnFocus="true" EmptyText="Select" Width="300" ListWidth="700"
            TypeAhead="true" Mode="Local" ForceSelection="true" InvalidText="Please choose a company">
            <Listeners>
                <Change Handler="CloseCall(#{clcmbCompany});" />
                <Select Handler="ValidateControl(new Array(#{clcmbCompany}));" />
            </Listeners>
            <CustomConfig>
                <ext:ConfigItem Name="preventMark" Value="true" Mode="Raw" />
            </CustomConfig>
        </ext:ComboBox>
    </td>
    <td>
        <ext:ImageButton ID="climbSearch" SkinID="Search" runat="server">
            <Listeners>
                <Click Handler="window.showMessage=true;return ValidateControl(new Array(#{clcmbCompany}));return ValCall(); " />
            </Listeners>
            <DirectEvents>
                <Click OnEvent="Search_Click">
                </Click>
            </DirectEvents>
        </ext:ImageButton>
    </td>
</tr>

<tr>
    <td align="center" colspan="4">
        <ext:ImageButton ID="climbConfirm" runat="server" SkinID="Submit">
            <DirectEvents>
                <Click OnEvent="Confirm_Click">
                    <ExtraParams>
                        <ext:Parameter Name="Values" Value="Ext.encode(#{grvpnlInflow}.getRowsValues({selectedOnly : true}))" Mode="Raw" />
                    </ExtraParams>
                    <EventMask ShowMask="true" />
                </Click>
            </DirectEvents>
        </ext:ImageButton>
    </td>
</tr>
```
Target .net framework: 4.5

Ext.Net
{
  .ver 1:0:4228:30692
}
  
  Ext.Net.Factory
{
  .ver 1:0:0:0
}
  
Ext.Net.Utilities
{
  .ver 1:0:0:30681
}

**Comment by fabriciomurta** [comment]
Hello @viveknuna!

Your server is not returning the Ext.NET expected response, this must be an issue with Web.config or the IISExpress instance config that is not registering Ext.NET AXD resources correctly. The `<` token suggests it is getting HTML as the response where it expects a json string, so check network traffic, you'll see that in one you are getting the response as a json text and in the other some kind of HTML (maybe with error 500 response when some runtime error triggers, or simply the actual page HTML when the request endpoint is not properly wired up).

This does not look like a bug and Ext.NET 1 is no longer under development, being superceded by several releases now (currently versions 5 and 7 are being maintained), so I am going ahead and closing this issue. If you need help with Ext.NET config we still have [the Ext.NET v1 community forums](https://forums.ext.net/forumdisplay.php?4-1-x-Help) for user-to-user discussions on the product.
