### ISSUE TITLE
Chart Legend doesn't work with ScatterSeries

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#187]
Chart/Scatter/Basic/
http://www.sencha.com/forum/showthread.php?259933

**Update:** Sencha issue _EXTJS-9280_ allegedly fixed in ExtJS 5.0.0.970 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9280_ allegedly fixed in ExtJS 5.0.0.970 release.
