### ISSUE TITLE
Websites of example.ext.net for V4 and V5 not working

### ISSUE THREAD

**Issue by sparkcontext** [extnet/Ext.NET#1876]
https://examples4.ext.net/

Browser: Chrome
Broswer's Develop Tool
![image](https://user-images.githubusercontent.com/59037690/193959776-1f527872-32eb-4b6b-aad8-d5e6c5538bc0.png)

https://examples5.ext.net/

Browser: Chrome
Broswer's Develop Tool
![image](https://user-images.githubusercontent.com/59037690/193959776-1f527872-32eb-4b6b-aad8-d5e6c5538bc0.png)

**Comment by DaveShopCtrl** [comment]
Yesterday the Examples for 4.8 redirect me to examples5 and shortly after the website stopped working at all.
On the extjs website, ext.net is also not listed anymore as bindings for the project. Seems Sencha dropped it as a project...

**Comment by geoffreymcgill** [comment]
There are some issues with the Examples Explorer hosting. Hopefully it will get straightened out soon.

You can run the Examples Explorer v4 project locally using the source from https://github.com/extnet/examples5.ext.net/tree/4. Each version of the Examples Explorer is stored in a branch within that repo. 

Hope this helps.
