### ISSUE TITLE
ToolTips are narrow in Chrome and IE10

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#189]
Committed the temporary fix. Needs to review/remove it after Sencha fix.

Here is a bug report to Sencha.
https://www.sencha.com/forum/showthread.php?257201

Involved:
http://forums.ext.net/showthread.php?24421

Related to #232.

**Comment by fabriciomurta** [comment]
This has been fixed on commit extnet/Premium@8f86f43b2b1a40ffa0ae35692132a8eb33a83087

**Comment by fabriciomurta** [comment]
This has been fixed on commit extnet/Premium@8f86f43b2b1a40ffa0ae35692132a8eb33a83087

**Comment by fabriciomurta** [comment]
Pointing to the correct issue (not dup) thread: https://www.sencha.com/forum/showthread.php?257201

The original sencha threads were:
Here is a related Sencha thread.
http://www.sencha.com/forum/showthread.php?260106

Here is a bug report to Sencha.
http://www.sencha.com/forum/showthread.php?260683

**Comment by fabriciomurta** [comment]
Double-checked Ext.NET, the override is no longer there. Removing `override-removal-pending` tag.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8824_ allegedly fixed by the time ExtJS 6.5.1 was released.
