### ISSUE TITLE
Grid performance with many columns and editing

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#190]
http://forums.ext.net/showthread.php?24123
http://www.sencha.com/forum/showthread.php?260539

**Update:** Sencha issue allegedly fixed by the time ExtJS 6.0.1 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9379_ allegedly fixed by the time ExtJS 6.0.2 was released.
