### ISSUE TITLE
A Surface's getGroup method doesn't extract a group

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#199]
#182

[15] Draw/Basic/Animation
- Nothing happens after clicking on Buttons

@vladsch: [FIXED] Fixed by overriding createGroup method of Surface, it is ExtJS bug (groups are not added to collection)

**Comment by fabriciomurta** [comment]
Reported to Sencha:
http://www.sencha.com/forum/showthread.php?260831
