### ISSUE TITLE
Multiselect in Window - shift-click not captured correctly

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#20]
http://forums.ext.net/showthread.php?21908-OPEN-Multiselect-in-Window-shift-click-not-captured-correctly

http://www.sencha.com/forum/showthread.php?248030

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
Hello!

Just tested this issue, although it is left open, it has been fixed at some point and not updated here. The issue is currently not reproducible in Ext.NET 4.4.0 at least.

Let us know if you still can reproduce this issue and we'll review it!
