### ISSUE TITLE
Infinite Scrolling Tuner example

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#200]
#182

[FIXED] Partially
[24] GridPanel/Infinite_Scrolling/Tuner/
- Click the Reload button => Uncaught TypeError: Object [object Object] has no method 'removeRange'

**Comment by fabriciomurta** [comment]
Here is a related bug report to Sencha. (marked as duplicate)
http://www.sencha.com/forum/showthread.php?260792
