### ISSUE TITLE
Button's click event is not being fired and the tooltip is not shown when it is overflowed in Toolbar

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#21]
http://forums.ext.net/showthread.php?21851
http://www.sencha.com/forum/showthread.php?247684

Review this thread after Sencha fix.
http://forums.ext.net/showthread.php?25860

A related problem here:
http://forums.ext.net/showthread.php?28173

Duplicate:
http://forums.ext.net/showthread.php?37751

**UPDATE:**
* A Button's Click listener issue has been fixed in v3.
* A ToolTip in a Button's ToolTips is still an issue. Reproducible with 3.2.0 with [this test case](http://forums.ext.net/showthread.php?25860&p=114454&viewfull=1#post114454).

**Update:** Sencha issue _EXTJS-7651_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-7651_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
The tooltip issue should be split. The sencha attached issue is specific to the click event and is fixed.
