### ISSUE TITLE
pt-PT and pt-BR  (Portuguese/Brazilian) locals issues

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#231]
http://forums.ext.net/showthread.php?24501
http://www.sencha.com/forum/showthread.php?262869

**Update:** Sencha issue _EXTJS-9700_ allegedly fixed in ExtJS 4.2.1.883 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9700_ allegedly fixed in ExtJS 4.2.1.883 release.
