### ISSUE TITLE
Stateful issue with a locking grid and filters

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#247]
http://forums.ext.net/showthread.php?24175
http://www.sencha.com/forum/showthread.php?264142

**Update:** Sencha issue _EXTJS-9915_ allegedly fixed in ExtJS 5.0.0.970 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9915_ allegedly fixed in ExtJS 5.0.0.970 release.
