### ISSUE TITLE
VBox align: "stretch" prevents horizontal scrolling even if there is minWidth

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#255]
http://forums.ext.net/showthread.php?25044
http://www.sencha.com/forum/showthread.php?264755

**Update:** Sencha issue _EXTJS-9982_ allegedly fixed in ExtJS 5.1.0.47 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9982_ allegedly fixed in ExtJS 5.1.0.47 release.
