### ISSUE TITLE
ToolbarDroppable have to have a destroy method

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#258]
http://forums.ext.net/showthread.php?25021
http://www.sencha.com/forum/showthread.php?264717

Fixed in revision 5157.
Remove the fix after a fix by Sencha.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
This issue is no longer reproducible in ExtJS 6.2.1, but not sure in what point it were actually fixed.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.2 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.3 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.6.0.258 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.7.0.161 was released. Sencha allegation: unable to reproduce the issue.
