### ISSUE TITLE
Multiple Grouping Issues in Grid

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#264]
http://forums.ext.net/showthread.php?25125
http://www.sencha.com/forum/showthread.php?264961

Thread posted by @vladsch (url moved below)

DUPs: 
http://forums.ext.net/showthread.php?25183
http://forums.ext.net/showthread.php?25442

**Comment by fabriciomurta** [comment]
(moved from initial comment to ensure we're checking the right sencha thread against the issue's status)
Thread posted by @vladsch http://www.sencha.com/forum/showthread.php?265204

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10027_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
Couldn't reproduce the issue in current Ext.NET versions.
