### ISSUE TITLE
Ext.grid.RowEditor onFieldChanged() No Longer Called

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#267]
http://forums.ext.net/showthread.php?25157
http://www.sencha.com/forum/showthread.php?264529

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9957_ allegedly fixed by the time ExtJS 6.0.2 was released.

**Comment by DaniilVeriga** [comment]
The original fix-override was removed in [this commit](https://github.com/extnet/Premium/commit/d5507b0a047ad41787a05f7d2417572ea68ae0cf) in 3.0.0-beta.
