### ISSUE TITLE
RTL QuickTipManager.init throws an error if call it outside Ext.onReady 

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#268]
http://www.sencha.com/forum/showthread.php?265232

Fixed in revision 5190. Remove after Sencha fix.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10066_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by DaniilVeriga** [comment]
The original fix has been removed. It is not required anymore.
