### ISSUE TITLE
Store reload call causes JavaScript error with a buffered grid

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#270]
http://forums.ext.net/showthread.php?25153

http://www.sencha.com/forum/showthread.php?265513
http://www.sencha.com/forum/showthread.php?264733

Duplicate:
http://forums.ext.net/showthread.php?27080

**Update:** Sencha issue _EXTJS-9991_ allegedly fixed in ExtJS 4.2.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9991_ allegedly fixed in ExtJS 4.2.2 release.
