### ISSUE TITLE
Menu item icon shifts on mouse over in Chrome

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#275]
http://forums.ext.net/showthread.php?25235
http://www.sencha.com/forum/showthread.php?265681

**Update:** Sencha issue _EXTJS-10181_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10181_ allegedly fixed in ExtJS 4.2.2.1144 release.
