### ISSUE TITLE
Column layout can crash if vertical scrolling

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#280]
http://forums.ext.net/showthread.php?25289
http://www.sencha.com/forum/showthread.php?266284

**Update:** Sencha issue _EXTJS-10312_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10312_ allegedly fixed in ExtJS 4.2.2.1144 release.
