### ISSUE TITLE
Ext.data.Field.sortDir is not implemented

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#289]
http://forums.ext.net/showthread.php?25431
http://www.sencha.com/forum/showthread.php?266641

**Update:** Sencha issue _EXTJS-10388_ allegedly fixed in ExtJS 5.1.0.47 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10388_ allegedly fixed in ExtJS 5.1.0.47 release.
