### ISSUE TITLE
Summary RemoteRoot doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#295]
http://forums.ext.net/showthread.php?25576
http://www.sencha.com/forum/showthread.php?261179

After fixing, define a RemoteRoot property for AbstractSummary.

**Update:** Sencha issue _EXTJS-9546_ allegedly fixed in ExtJS 5.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9546_ allegedly fixed in ExtJS 5.0.2 release.

**Comment by fabriciomurta** [comment]
I don't see any reference to SVN revisions here or in Ext.NET thread but seems a change is expected in `Ext.Net.GroupingSummary` / `Ext.Net.AbstractSummary` before marking this as fixed and closing!

**Comment by DaniilVeriga** [comment]
Exactly. There was no commit to SVN regarding this issue. A solution was suggested in the forum thread only, but not committed to SVN.

The RemoteRoot property has been added to Ext.Net.AbstractSummary.
