### ISSUE TITLE
Grid column setEditor in beforeEdit handler of RowEditing causes error

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#298]
http://forums.ext.net/showthread.php?25589
http://www.sencha.com/forum/showthread.php?267788

**Update:** Sencha issue allegedly fixed by the time ExtJS 6.0.1 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue allegedly fixed by the time ExtJS 6.0.2 was released.
