### ISSUE TITLE
Container with "frame: true" causes "Layout run failed" in IE8

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#299]
http://forums.ext.net/showthread.php?25563
http://www.sencha.com/forum/showthread.php?267623

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.2.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10622_ allegedly fixed in ExtJS 6.5.1.345 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10622_ allegedly fixed in ExtJS 6.5.1.345 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10622_ allegedly fixed in ExtJS 6.5.1.345 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10622_ allegedly fixed in ExtJS 6.5.1.345 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10622_ allegedly fixed in ExtJS 6.5.1.345 release.

**Comment by fabriciomurta** [comment]
There's no reproducible test case for this issue, it is not feasible to track it like this, as Sencha claims they fixed the issue. If anybody still can reproduce this, just let us know and we'll reopen the issue.
