### ISSUE TITLE
Dynamically Freeze Grid Column

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#30]
http://forums.ext.net/showthread.php?21300-OPEN-Dynamically-Freeze-Grid-Column

http://www.sencha.com/forum/showthread.php?244774

**Update:** Sencha issue _EXTJS-7424_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-7424_ allegedly fixed in ExtJS 4.2.3 release.
