### ISSUE TITLE
Checkbox does not fire "change" event on the first change after setRawValue

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#302]
http://forums.ext.net/showthread.php?25605
http://www.sencha.com/forum/showthread.php?263404

**Update:** Sencha issue _EXTJS-10684_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10684_ allegedly fixed in ExtJS 4.2.3 release.
