### ISSUE TITLE
RowEditing breaks after grid reconfigure

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#303]
Discovered due to #294.
http://www.sencha.com/forum/showthread.php?268231

**Update:** Sencha issue _EXTJS-10709_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10709_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
I don't see any reference here for forum thread nor SVN ref, so I am assuming there's no override to undo on this issue. As Sencha claims it's been fixed for some time already, I'll be closing this issue for now.

Also, it has no 'review' tag, another suggestion that there's no override at all. :)
