### ISSUE TITLE
Pre Gantt and Scheduler issues

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#309]
Tested in Chrome unless noted

[3] Gantt/Advanced/Column_Filtering/
- Type "FireFox" in the Tasks filter => the tree and timeline schedule look inconsistent
- Collapse "FireFox Stable" => it gets expanded with duplicated nodes
  - _@Vladimir:_ In Bryntum example filtering doesn't work at all
  - _@Daniil:_ I don't see that example online. Probably, they excluded it because of it is not working. I guess we should do the same. Also the example in the distributive throws JavaScript with 2.2.7.

[8] Scheduler/Basic/Grouping/
- Collapse "Consultants"
- Create an event in "Research" (click, hold and drag) => Uncaught TypeError: Cannot read property 'internalId' of undefined 
  - _@Vladimir_: Grouping functionality is broken in ExtJS 4.2.1. Note from Scheduler change log: A few bugs exist in the Ext 4.2.1 grouping view which might affect your application.
    More information here: http://www.sencha.com/forum/showthread.php?265078-Broken-contracts-of-getAt-indexOf-methods-of-the-Ext.grid.feature.Grouping
  - _@Daniil_: Maybe exclude this example?

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10043_ allegedly fixed in ExtJS 4.2.3 release.
