### ISSUE TITLE
TextArea rows doesn't work in IE7 because of isBorderBox

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#311]
http://forums.ext.net/showthread.php?25339
http://www.sencha.com/forum/showthread.php?269162

Duplicate:
http://forums.ext.net/showthread.php?49721

**Update:** Sencha issue _EXTJS-10844_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10844_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
IE7 is not even supported anymore, is it?
