### ISSUE TITLE
TabConfig doesn't support TextAlign config

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#317]
http://forums.ext.net/showthread.php?25957
http://www.sencha.com/forum/showthread.php?180657

**Update:** Sencha issue _EXTJS-5353_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-5353_ allegedly fixed in ExtJS 4.2.3 release.
