### ISSUE TITLE
ComboBox lose value with remote paging

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#318]
http://forums.ext.net/showthread.php?25948
http://www.sencha.com/forum/showthread.php?269445

Reported a similar problem with v3, but could not reproduce so far.
http://forums.ext.net/showthread.php?59704

**Update:** Allegedly fixed in latest (6.0.1) ExtJS release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10874_ allegedly fixed by the time ExtJS 6.0.2 was released.
