### ISSUE TITLE
GridFilters StringFilter breaks if define it with listeners

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#324]
http://forums.ext.net/showthread.php?26003
http://www.sencha.com/forum/showthread.php?269915

Fixed in trunk, revision 5332. Review after Sencha fix.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.2 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.3 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
For the same reason as #321, this issue is no longer actual. Issue #1594 fixes what's really wrong with the current implementation of the feature.
