### ISSUE TITLE
Button Href doesn't work in IE < 9

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#326]
http://forums.ext.net/showthread.php?26127
http://www.sencha.com/forum/showthread.php?266596

**Update:** Sencha issue _EXTJS-10376_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10376_ allegedly fixed in ExtJS 4.2.2.1144 release.
