### ISSUE TITLE
GridViewDragDrop/TreeViewDragDrop ContainerScroll doesn't work well

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#334]
http://forums.ext.net/showthread.php?26289
http://www.sencha.com/forum/showthread.php?271070

Duplicate
http://forums.ext.net/showthread.php?39901

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10316_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10316_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10316_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
The code introduced by svn 5919 (github 3111d21f5d51200b30a6b3e5ff7a495acc086719) is no longer present, so the override has already been removed for a while.
