### ISSUE TITLE
TreePanel TreeColumn: ellipsis doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#346]
http://forums.ext.net/showthread.php?26490
http://www.sencha.com/forum/showthread.php?269637

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10880_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10880_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10880_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10880_ allegedly fixed in ExtJS 4.2.2.1144 release.
