### ISSUE TITLE
Override BorderLayout Behavior to Float Rather than Expand and icon click

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#35]
http://forums.ext.net/showthread.php?21346-OPEN-Override-BorderLayout-Behavior-to-Float-Rather-than-Expand-and-icon-click

http://www.sencha.com/forum/showthread.php?245265

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.
