### ISSUE TITLE
Grid with BufferedRenderer throws JS error on record insertion

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#350]
http://forums.ext.net/showthread.php?26533
http://www.sencha.com/forum/showthread.php?272367

**Update:** Issue still open after 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11358_ allegedly fixed by the time ExtJS 6.2.1 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11358_ allegedly fixed by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11358_ allegedly fixed by the time ExtJS 6.5.1 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11358_ allegedly fixed by the time ExtJS 6.5.2 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11358_ allegedly fixed by the time ExtJS 6.5.3 was released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11358_ allegedly fixed by the time ExtJS 6.6.0.258 was released.

**Comment by fabriciomurta** [comment]
This is indeed no longer reproducible in Ext JS 6.6.0 (Ext.NET 4.7.0).
