### ISSUE TITLE
GridPanel BufferedRenderer + RowWrap or RowExpander breaks rendering

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#353]
http://forums.ext.net/showthread.php?26597
http://www.sencha.com/forum/showthread.php?272634

**Update:** This is allegedly fixed for ExtJS 4.2.2 onwards.

**Comment by DaniilVeriga** [comment]
The issue causes the following undesired effect in this example.
http://examples.ext.net/#/GridPanel/RowExpander/Dynamic_GridPanels

If expand any row and then sort - the expanded row's content disappears. I will add `BufferedRenderer="false"` for the GridPanel as a workaround.

**Comment by fabriciomurta** [comment]
This issue no longer happens on latest Ext.NET versions, although a very similar one does. Will open a new issue to track the newly discovered one and close this.

**Comment by fabriciomurta** [comment]
The original sencha thread (http://www.sencha.com/forum/showthread.php?272634) is marked as duplicate and there's no reference to any forum thread related to the duplicating issue, so it is not useful to track the state of the sencha issue anymore. Removed from original comment.
