### ISSUE TITLE
Narrow tooltips in Safari Mac

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#391]
http://forums.ext.net/showthread.php?27393
http://www.sencha.com/forum/showthread.php?276966

Said that it is fixed in 4.2.2. Review after upgrading to the next public ExtJS release.

A workaround for now is using a non-breakable space instead of white spaces.

**Update:** This issue has been allegedly fixed in ExtJS as of 5.0.1.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-12511_ allegedly fixed in ExtJS 5.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-12511_ allegedly fixed in ExtJS 5.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-12511_ allegedly fixed in ExtJS 5.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-12511_ allegedly fixed in ExtJS 5.0.1 release.

**Comment by fabriciomurta** [comment]
Forums has the fixed state and a fixed message feedback, and no follow-up from the reporting user nor anybody, so there's no point in keeping this open.
