### ISSUE TITLE
CellEditing Plugin shows the wrong value in a locked column

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#408]
http://forums.ext.net/showthread.php?27633

http://www.sencha.com/forum/showthread.php?278913

Reported to Sencha another issue but related to this.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue has not been reviewed by Sencha.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue has not been reviewed by Sencha.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.3 release. Issue has not been reviewed by Sencha.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue has not been reviewed by Sencha.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue has not been reviewed by Sencha.
