### ISSUE TITLE
Removing a record from a grouped store does not remove it from groups

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#429]
http://forums.ext.net/showthread.php?28004
http://www.sencha.com/forum/showthread.php?278916

**Update:** This issue is allegedly fixed in ExtJS since 4.2.3.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11901_ allegedly fixed in ExtJS 4.2.3 release.
