### ISSUE TITLE
DateField StartDay is not localized

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#45]
http://forums.ext.net/showthread.php?20791-OPEN-DateField-Localization-Issue

http://www.sencha.com/forum/showthread.php?240168

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly unreproducible by the time ExtJS 6.0.2 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
Issue still reproducible albeit disclaimed by Sencha.
