### ISSUE TITLE
MonthPicker is rendered too small to show all the options

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#453]
http://forums.ext.net/showthread.php?29341
http://www.sencha.com/forum/showthread.php?264688

It should be fixed in ExtJS 4.2.2. Review after next ExtJS update.

Duplicate:
http://forums.ext.net/showthread.php?32271

**Update:** Allegedly [fixed since 5.0.0](http://docs.sencha.com/extjs/5.0/whats_new/release_notes.html) (look for ExtJS-9974 issue).

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue allegedly fixed by the time ExtJS 6.0.2 was released.

**Comment by fabriciomurta** [comment]
Forum thread was already on Bugs forum and didn't have a version tag. As this issue has just the '2.x' tag, assumed this issue pertains to Ext.NET 2.x and added this information to the forum thread's title.
