### ISSUE TITLE
TimeAxis has wrong labels with a Month Step

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#454]
http://forums.ext.net/showthread.php?29351
http://www.sencha.com/forum/showthread.php?267174

**Update:** This has been allegedly fixed since ExtJS 4.2.2

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10654_ allegedly fixed in ExtJS 4.2.2.1144 release.
