### ISSUE TITLE
BorderLayout CollapseMode Mini: a collapse/expand tool is being hidden on collapse

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#503]
http://www.sencha.com/forum/showthread.php?261444
http://www.sencha.com/forum/showthread.php?285728

**UPDATE**: marked as fixed in ExtJS 6.0.0.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-9505_ allegedly fixed in ExtJS 6.0.0 release.

**Comment by fabriciomurta** [comment]
Both related sencha issues have been marked as fixed!
