### ISSUE TITLE
GroupTabPanel doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#548]
There is something wrong with the GroupTabRenderer plugin. It doesn't render a tree.
http://www.sencha.com/forum/showthread.php?295943

Reports:
http://forums.ext.net/showthread.php?51151
http://forums.ext.net/showthread.php?59439

**UPDATE**: still not fixed in ExtJS 5.1.1.

**Update**: Issue still open after 6.0.1 release.

**Update**: the GroupTabPanel example has been hidden from Examples Explorers (since v3.3 and v4.0).

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.2.1 release.

**Comment by fabriciomurta** [comment]
Issue points as fixed in ExtJS 5.1.5 (non-released) and the component has been completely removed from ExtJS 6.5.0, so I don't see this ever being really fixed to the current version.
