### ISSUE TITLE
AnimCollapseDuration doesn't work without a BorderLayout

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#557]
http://forums.ext.net/showthread.php?43561
http://www.sencha.com/forum/showthread.php?252158

**Update:** Allegedly fixed since ExtJS 4.2.3 (v4!) so it probably does not happen on either Ext.NET 3.2.1 nor 4.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-8095_ allegedly fixed in ExtJS 4.2.3 release.

**Comment by fabriciomurta** [comment]
Blame me for mistakenly adding the 'review' tag here. There's no reference to any SVN commit (nor git hash here in github issue), so there's no override to reverse.

As sencha claimed the issue as fixed, we should follow.
