### ISSUE TITLE
StringFilter should not have a separator

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#56]
http://forums.ext.net/showthread.php?22205&p=96176&viewfull=1#post96176

http://www.sencha.com/forum/showthread.php?249529

Sencha fixed it. Needs to review after incorporating a release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.
