### ISSUE TITLE
A GridPanel's reconfigure doesn't work with a Grouping feature

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#561]
http://forums.ext.net/showthread.php?44421

http://www.sencha.com/forum/showthread.php?265674
http://www.sencha.com/forum/showthread.php?271099
http://www.sencha.com/forum/showthread.php?288221

**Update:** Not reproduceable in both ExtJS 5.1.1 nor 6.0.1. This has been fixed since Ext.NET 3.2.1 at least.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by DaniilVeriga** [comment]
The original issue with `.reconfigure()` and a Grouping feature has been fixed as of 3.2.1, at least.
