### ISSUE TITLE
RowEditing startEdit does not focus a column's editor

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#576]
http://forums.ext.net/showthread.php?45231
http://www.sencha.com/forum/showthread.php?268229

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10707_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment]
This does not apply to Ext.NET 4. The override introduced by 6060 (git's b4ecfdffd3bdcd8e962f9f408ab81016d9104f6c) is no longer present in Ext.NET.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-10707_ allegedly fixed in ExtJS 4.2.2.1144 release.
