### ISSUE TITLE
Stateful GridPanel might distort on restoring of moved columns that are initially hidden

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#589]
http://www.sencha.com/forum/showthread.php?266069

Review if ever upgrade to ExtJS 4.2.2 or higher.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-10262.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-10262_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.3 release. Issue is acknowledged by Sencha under ID _EXTJS-10262_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-10262_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-10262_.
