### ISSUE TITLE
No record.raw on a Store's .add() call. Is it still supported?

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#606]
http://forums.ext.net/showthread.php?48281
http://forums.ext.net/showthread.php?48201
http://forums.ext.net/showthread.php?49352

**Update:** Still not working on 6.0.1 but, as stated in forums, this is not a documented/supported feature so maybe it is not a good idea to try and treat this as a bug. It was a change from ExtJS 4.x to 5.x that did not need to be documented as the .raw property was private and not documented. There's no 'raw' field in [the documentation](http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.data.Model), even enabling deprecated, private and removed fields view.

I believe `store.data.items[id].data` should be used instead of `.raw`.

**Comment by fabriciomurta** [comment]
This issue maybe is related to changes that originated [keepRawData](http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.data.reader.Reader-cfg-keepRawData) on Ext.data.reader.Reader, so there may be another way to retrieve the raw data from a reader.
