### ISSUE TITLE
ASP.NET Core support

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#620]
http://forums.ext.net/showthread.php?48391
http://forums.ext.net/showthread.php?60317
http://forums.ext.net/showthread.php?60410

ASP.NET MVC 6 - #855

**Comment by piyey** [comment]
We already have ASP.NET 5, please take a look at this.
Regards!

**Comment by fabriciomurta** [comment]
The related forum post also suggests using Ext.NET from Linux so... not sure this should be closed or reviewed.

Thanks for the bump! :)

**Comment by fabriciomurta** [comment]
Another request at [Support .Net Core](https://forums.ext.net/showthread.php?62349-Support-Net-Core)

**Comment by geoffreymcgill** [comment]
Ext.NET for ASP.NET Core 3.1 is now available.

https://ext.net/v7-0-preview-for-asp-net-core/

Going forward, there will be three separate editions of Ext.NET, **Legacy**, **Modern**, and **Classic**.

![image](https://user-images.githubusercontent.com/62210/78862957-bb077d00-79f5-11ea-93a6-1a663ba511d0.png)
