### ISSUE TITLE
Decrease Ext.Net.dll size

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#640]
Remove all embedded resources that are not required to be embedded.

The size of dll might be a reason of System.OutOfMemoryException - #641

**Comment by DaniilVeriga** [comment]
Revision 6256 (trunk). Removed all the embedded resources that are not required to be embedded. 

Before Ext.Net.dll was ~126 MB (built in the default Debug mode), now it is ~ 58 MB.

There is also [a related commit](https://github.com/objectdotnet/Ext.NET.ERB/commit/bf555a756494dd52b2023066400398a5c9493d3d) in the Ext.NET.ERB project

**Comment by DaniilVeriga** [comment]
We are closing this Issue, but we continue thinking about how to re-organize the things to get the dll size even smaller. In particular, we think/investigate a possibility to move out the Themes and UI pack to separate assemblies.

**Comment by geoffreymcgill** [comment]
What about the option of gzipping the .js files by default, instead of real-time gzipping upon the request. That could provide an approximate 70% reduction in .js file size.

In fact this could potentially be done for all embedded files, such as .css and images.

**Comment by DaniilVeriga** [comment]
I just found that we already have the "Pre-gzipped resources" issue - #356.
