### ISSUE TITLE
Modal window background does not resize with browser window

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#643]
http://forums.ext.net/showthread.php?51691
http://www.sencha.com/forum/showthread.php?295917

**Update:** Allegedly fixed for ExtJS 5.1.3. The issue entry (16184) was not found in [6.x changelog](http://docs.sencha.com/extjs/6.0/whats_new/release_notes.html). Probably will be coming to 6.0.2 as well.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16184_ allegedly fixed in ExtJS 5.1.3 release.

**Comment by fabriciomurta** [comment]
ExtJS-16184 reads on [ExtJS 6.0.2 changelog](https://github.com/extnet/Ext.NET/issues/618)!
