### ISSUE TITLE
TreePanel/GridPanel view becomes empty when its store is loaded while the panel is hidden

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#664]
http://www.sencha.com/forum/showthread.php?295129
http://forums.ext.net/showthread.php?52081

Duplicate:
http://forums.ext.net/showthread.php?59221

**UPDATE**: The issue is still reproducible with ExtJS 5.1.1 and Ext.NET 3.2.0.

**Update:** This is allegedly fixed in a recent ExtJS build, after 6.0.1 has been released.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue allegedly fixed by the time ExtJS 6.0.2 was released.

**Comment by fabriciomurta** [comment]
I have mis-marked 'review' label here again. Just removed it, there's no SVN/git commit directly related to this issue on Ext.NET.
