### ISSUE TITLE
Spotlight show and hide method callback isn't used

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#665]
http://forums.ext.net/showthread.php?52592
http://www.sencha.com/forum/showthread.php?297605

Fixed in 3.1.0 beta.

Review if Sencha fixes that.

**Comment by DaniilVeriga** [comment]
Fixed in the revision 6288 (trunk). It goes to 3.1.0 beta.

**Comment by DaniilVeriga** [comment]
The fix has been improved in the revision 6295 (trunk). It goes to 3.1.0 beta. 

Also Anup reported to Sencha and they opened a bug.
http://www.sencha.com/forum/showthread.php?297605

So, review if Sencha fixes that.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.2.1 release.

**Comment by fabriciomurta** [comment]
Considering this a defect as it removed a formerly supported feature.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-16670.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-16670_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-16670_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-16670_.
