### ISSUE TITLE
MVC Examples Explorer issues in Ext.NET v3.1.0

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#673]
## Ext.Net.MVC

Item | State | Description
-------- | -------- | -------- 
1. | OPEN | [http://localhost:64682/#](http://localhost:64682/#)
 | | No icons on the examples tree (all are ordinary folder icons)
 | | @DaniilVeriga: We always don't have a chance to set up icons:)
 | FIXED | Two (x) icons on search field: one from the browser, other from the interface (to reset the field)> **IE only**
2. | OPEN | [http://localhost:64682/#/Buttons_Basic/Overview/](http://localhost:64682/#/Buttons_Basic/Overview/)
 | | Flat button (11th) does not seem to obey theme.
 | | 
4. | OPEN | [http://localhost:64682/#/Desktop/ASPX/](http://localhost:64682/#/Desktop/ASPX/)
 | FIXED | After login: `Deprecated: Ext.EventManager [ext.axd?v=31872:5663]`
 | | **Desktop:** 
 | FIXED | Clock's _am/pm_ does not fit clock area. 3.0.0 also has this glitch.
 | FIXED | Tooltip _orphan shadow_ shown on icons without tooltip. Shadow appears in place of last tooltip displayed.
 | FIXED | Quick launch pop-up entries have no text
 | FIXED | Accordion Window: `undefined is not a function` upon clicking _refresh_ icon on _online users_ tab
 | | **Notepad:**
 | FIXED | Icons on toolbar are not correctly fit (3.0.0 has this too)
 | FIXED | On activating _Source edit_ toolbar item (last) several errors occur. Deactivating it also triggers more errors.
 | | You can get colored bullets/numbers if you have your font in a color different than black, select either numbering or bulleting, write something on the line, and switch from one to another. The bullet/number will keep the color of the font. Kind of useful :)
 | | Switching between bullet/numbered lists does not affect rest of list (just current line). On 3.0.0 all list is affected.
 | | @DaniilVeriga: the two issues above are quite specific to HtmlEditor. Due to the design of HtmlEditor it has such issues. There is some explanation in [this post](http://forums.ext.net/showthread.php?20425&p=88270&viewfull=1#post88270).
 | | **System Status:** 
 | | Chart end gradually stretches as you let it advance. Happens with CPU Core charts, not the others, apparently. 3.0.0 affected as well.
 | | @DaniilVeriga: not sure what is meant or just cannot reproduce.
 | |
5. | OPEN | [http://localhost:64682/#/Desktop/Overview/](http://localhost:64682/#/Desktop/Overview/)
 | | _Not all errors on the example above happens here!_
 | | **Desktop:**
 | FIXED | Clock's _am/pm_ does not fit clock area. 3.0.0 also has this glitch.
 | FIXED | Tooltip _orphan shadow_ shown on icons without tooltip. Shadow appears in place of last tooltip displayed.
 | FIXED | Language button (next to clock): `Cannot read property 'setText' of undefined window.App.Desktop1.Ext.create.....`
 | | **Notepad:**
 | FIXED | Icons on toolbar are not correctly fit (3.0.0 has this too)
 | FIXED | On activating _Source edit_ toolbar item (last) several errors occur. Deactivating it also triggers more errors.
 | | You can get colored bullets/numbers if you have your font in a color different than black, select either numbering or bulleting, write something on the line, and switch from one to another. The bullet/number will keep the color of the font. Kind of useful :)
 | | Switching between bullet/numbered lists does not affect rest of list (just current line). On 3.0.0 all list is affected.
 | | **System Status:**
 | | Chart end gradually stretches as you let it advance. Happens with CPU Core charts, not the others, apparently. 3.0.0 affected as well.
 | | 
6. | OPEN | [http://localhost:64682/#/DragDrop_Basic/Dom/](http://localhost:64682/#/DragDrop_Basic/Dom/)
 | | Drop area erratically interpreted for some items dragged
 | | After some drags and drops, the frame stops being draggable in some situations and browser dragging of the image happens
 | | Eventually javascript errors are triggered when closing the tab (once the dragging is completely screwed)
 | | Error is triggered once you start dragging pictures (browser-side) instead of frames (ext.NET side)
 | | **Triggers:**
 | | `Ext.dom.Fly.removeListeners(): Cannot use removeListener() on Ext.dom.Fly instances. Please use Ext.get() to retrieve an Ext.dom.Element instance instead [ext.axd?v=31872:5663]`
 | | 
12. | OPEN | [http://localhost:64682/#/Editor_Basic/Overview/](http://localhost:64682/#/Editor_Basic/Overview/)
 | | JS error on load: `Syntax error, unrecognized expression: unsupported pseudo: label [browserLink:37]`
 | | @DaniilVeriga cannot reproduce.
20. | OPEN | [http://localhost:64682/#/GridPanel_ComponentColumn/Editor/](http://localhost:64682/#/GridPanel_ComponentColumn/Editor/)
 | | [http://localhost:64682/#/GridPanel_ComponentColumn/Over_Editor/](http://localhost:64682/#/GridPanel_ComponentColumn/Over_Editor/)
 | | [http://localhost:64682/#/GridPanel_ComponentColumn/Pin_Editor/](http://localhost:64682/#/GridPanel_ComponentColumn/Pin_Editor/)
 | | When editing a value and pressing _enter_, triggers `Cannot read property 'store' of undefined`
 | | 
22. | OPEN | [http://localhost:64682/#/GridPanel_FilterHeader/Overview/](http://localhost:64682/#/GridPanel_FilterHeader/Overview/)
 | | _Visible_ column does not filter by **Yes/No** but **1/0**.
 | | Happens since 2.5 examples!
 | | @DaniilVeriga: There is a note in the description that a Boolean columns deals with "1, 0, true, false".
24. | OPEN | [http://localhost:64682/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/](http://localhost:64682/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/)
 | | [http://localhost:64682/#/GridPanel_Infinite_Scrolling/Forum_topics/](http://localhost:64682/#/GridPanel_Infinite_Scrolling/Forum_topics/)
 | | [http://localhost:64682/#/GridPanel_Infinite_Scrolling/Remote_Filter/](http://localhost:64682/#/GridPanel_Infinite_Scrolling/Remote_Filter/)
 | | Its description says _"Ext.NET 2's (...)"_
 | | Also affects Ext.NET 3.0 production examples
 | | @DaniilVeriga: Well, this functionality appeared with Ext.NET v2. Do you think we should remove that reference?
25. | OPEN | [http://localhost:64682/#/GridPanel_Infinite_Scrolling/Overview/](http://localhost:64682/#/GridPanel_Infinite_Scrolling/Overview/)
 | | Loading sample triggers `Setting 'XMLHttpRequest.withCredentials' for synchronous requests is deprecated.`
 | | @DaniilVeriga cannot reproduce.
 | | Its description says _"Ext.NET 2's (...)"_
 | | 
34. | OPEN | [http://localhost:64682/#/Panel_Basic/Deferred_Loading/](http://localhost:64682/#/Panel_Basic/Deferred_Loading/)
 | | When loading, error is triggered: `Syntax error, unrecognized expression: unsupported pseudo: Label`
 | | Despite the error, the page seems to demonstrate well its functionalities.
 | | @DaniilVeriga cannot reproduce.
35. | OPEN | [http://localhost:64682/#/TabPanel_Basic/TabMenu/](http://localhost:64682/#/TabPanel_Basic/TabMenu/)
 | | Dropdown menus do not hide when clicked out.
 | | Specially the _Menu 2_ dropdown. 
 | | The other dropdowns are hid once you click other menu.
 | | 
36. | OPEN | [http://localhost:64682/#/TreePanel_Advanced/Filter/](http://localhost:64682/#/TreePanel_Advanced/Filter/)
 | | Unchecking _Tree_ checkbox always gives no results once filtering -- unless empty
 | | Version 2.x didn't have the _Tree_ checkbox.
 | | 
37. | OPEN | [http://localhost:64682/#/TreePanel_Advanced/Image_Organizer/](http://localhost:64682/#/TreePanel_Advanced/Image_Organizer/)
 | | The drag and drop is not actually working.
 | | Works on 2.5 and 3.0
 | | 
38. | OPEN | [http://localhost:64682/#/Form_ComboBox/Custom_Search/](http://localhost:64682/#/Form_ComboBox/Custom_Search/)
 | #702 | When filter results have more than one page, switching to next page closes the results.
 | | @DaniilVeriga: It appears to be related (or just same) as #702.

## FIXED

Item | State | Description
-------- | -------- | -------- 
3. | FIXED | [http://localhost:64682/#/DataView_Advanced/Multi_sort/](http://localhost:64682/#/DataView_Advanced/Multi_sort/)
 | #707 | Errors during load: 
 | | `initConfig should not be called by subclasses, it will be called by Ext.Component [ext.axd?v=31872:1937]`
 | | `cannot read property **'getY'** of undefined reDraw [ext.axd?v=31872:88]`
7. | FIXED | [http://localhost:64682/#/Draw_Basic/Actions/](http://localhost:64682/#/Draw_Basic/Actions/)
 | #708 | The _Rotate -45_ button does not rotate -45 degrees.
8. | FIXED | [http://localhost:64682/#/Draw_Basic/Analytics/](http://localhost:64682/#/Draw_Basic/Analytics/)
 | #709 | [http://localhost:64682/#/Draw_Basic/Pie_Chart/](http://localhost:64682/#/Draw_Basic/Pie_Chart/)
 | #709 | [http://localhost:64682/#/Draw_Basic/Punch_Chart/](http://localhost:64682/#/Draw_Basic/Punch_Chart/)
 | | 404 error on window: `GET http://localhost:64682/WebResource.axd?d=wRbonRbYl9T... 404 (Not Found)`
 | | in short: Missing resource /WebResource.axd
9. | FIXED | [http://localhost:64682/#/Draw_Basic/Logos/](http://localhost:64682/#/Draw_Basic/Logos/)
 | r6388 | Logos are not centered and does not fit the draw area. Happens on 3.0.0 and 3.1.0. Works on 2.5.3.
 | | Set SVG paths as fixed scale/position and locked window from resizing.
10. | FIXED | [http://localhost:64682/#/Draw_Basic/Reflection/](http://localhost:64682/#/Draw_Basic/Reflection/)
 | #713 | No reflection at all. Bugged since 3.0.0.
10.1 | FIXED | [http://localhost:64682/#/Draw_Basic/Rotate_Image/](http://localhost:64682/#/Draw_Basic/Rotate_Image/)
 | #714 | Does not rotate anything. Bugged since 3.0.0.
 | | Hover effect over rotation arrows does not happen as well
11. | FIXED | [http://localhost:64682/#/Dynamic_Partial_Rendering/Add_Tab/](http://localhost:64682/#/Dynamic_Partial_Rendering/Add_Tab/)
 | | Numbers are shifted up from their boxes (as if anchor=top and anchorText=middle)
 | | 3.0.0 does not have this sample (nor this sample tab)
13. | FIXED | [http://localhost:64682/#/Element_Basic/Layer/](http://localhost:64682/#/Element_Basic/Layer/)
 | | Mysterious orphan shadow is displayed once _Show Bottom_ is clicked.
 | | Clicking randomly, switching browser tabs and windows shown (from the panel's bottom buttons) eventually hide the shadow.
 | | Once the shadow is hidden, `Cannot read property 'isSynchronized' of undefined` will happen when _Show Bottom_ is clicked.
14. | FIXED | [http://localhost:64682/#/Form_ComboBox/Linked_Combos_In_Grid/](http://localhost:64682/#/Form_ComboBox/Linked_Combos_In_Grid/)
 | | Throws `Cannot read property '_incr_' of undefined` during load
15. | FIXED | [http://localhost:64682/#/Form_FormPanel/Basic/](http://localhost:64682/#/Form_FormPanel/Basic/)
 | | Details window does not fit the form fields (probably due to the default theme)
 | | v3.0 also affected
 | | _Save To Grid_ button has `debugger` JS call on its `OnClientClick` event
16. | FIXED | [http://localhost:64682/#/Form_Groups/Basic/](http://localhost:64682/#/Form_Groups/Basic/)
 | | Frame overflows _Checked Items_ once _Save_ is clicked.
 | | Applies to v3.0
17. | FIXED | [http://localhost:64682/#/Form_Hyperlink/Basic/](http://localhost:64682/#/Form_Hyperlink/Basic/)
 | | Image link points to non existing image
 | | points to: http://speed.ext.net/identity/extnet-poweredby-small.png
 | | v3.0 points to (valid): http://speed.ext.net/identity/extnet-logo-small.png
18. | FIXED | [http://localhost:64682/#/GridPanel_ColumnModel/RatingColumn/](http://localhost:64682/#/GridPanel_ColumnModel/RatingColumn/)
 | | Column _Editable_ is written as _Edaitable_ (ugh)
19. | FIXED | [http://localhost:64682/#/GridPanel_Commands/Cell_Command/](http://localhost:64682/#/GridPanel_Commands/Cell_Command/)
 | | Column _Change_ is too narrow to table contents and breaks line on a single row
21. | FIXED | [http://localhost:64682/#/GridPanel_Editable/Editor_with_DirectMethod/](http://localhost:64682/#/GridPanel_Editable/Editor_with_DirectMethod/)
 | | Notification window does not fit text (specially while changing company names)
23. | FIXED | [http://localhost:64682/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/](http://localhost:64682/#/GridPanel_Infinite_Scrolling/Buffered_Scrolling/)
 | | Trying to jump to a specific row triggers `Cannot read property 'scrollTo' of undefined`
26. | FIXED | [http://localhost:64682/#/GridPanel_Paging_and_Sorting/Local/](http://localhost:64682/#/GridPanel_Paging_and_Sorting/Local/)
 | | Width is too narrow: hides the _Save_ button.
 | | By manually stretching the grid to show the hidden contents, the _Save_ button works!.
27. | FIXED | [http://localhost:64682/#/GridPanel_RowExpander/Dynamic_GridPanels/](http://localhost:64682/#/GridPanel_RowExpander/Dynamic_GridPanels/)
 | | [http://localhost:64682/#/GridPanel_RowExpander/Dynamic_View/](http://localhost:64682/#/GridPanel_RowExpander/Dynamic_View/)
 | | Tight columns truncates _product's name_ column titles.
28. | FIXED | [http://localhost:64682/#/GridPanel_Selection_Models/Checkbox_Selection/](http://localhost:64682/#/GridPanel_Selection_Models/Checkbox_Selection/)
 | | Request failure triggered by clicking the _refresh_ button on grid's bottom toolbar.
 | | Also affects v2.5 production sample
29. | FIXED | [http://localhost:64682/#/GridPanel_Update/AutoSave/](http://localhost:64682/#/GridPanel_Update/AutoSave/)
 | | [http://localhost:64682/#/GridPanel_Update/Batch/](http://localhost:64682/#/GridPanel_Update/Batch/)
 | | Razor view parse error on load: `Expected "}"`
 | | Respectively:
 | | `**Source File:** /Areas/GridPanel_Update/Views/AutoSave/Index.cshtml    **Line:** 198`
 | | `**Source File:** /Areas/GridPanel_Update/Views/Batch/Index.cshtml    **Line:** 175`
30. | FIXED | [http://localhost:64682/#/GridPanel_Update/Restful/](http://localhost:64682/#/GridPanel_Update/Restful/)
 | | Popup title (when adding/removing items) is not displayed correctly
31. | FIXED | [http://localhost:64682/#/Layout_CardLayout/Basic/](http://localhost:64682/#/Layout_CardLayout/Basic/)
 | | Wizard text is cut due to theme.
32. | FIXED | [http://localhost:64682/#/Miscellaneous_Mouse_Distance_Sensor/Basic/](http://localhost:64682/#/Miscellaneous_Mouse_Distance_Sensor/Basic/)
 | | Bottom-right dialog does not fit its fields
 | | Mysterious partially hidden _"Mouse Sensor Distance"_ phrase on bottom of the screen.
33. | FIXED | [http://localhost:64682/#/Models/Editor_Template/](http://localhost:64682/#/Models/Editor_Template/)
 | | The theme again, hid a button on the window's bottom.

**Comment by fabriciomurta** [comment]
Issue #710 requires reviewing the example [Dynamic Form, Grid and Charts](http://localhost:64682/Chart_Dashboard/Basic/Index), not on the list above.

**Comment by fabriciomurta** [comment]
All issues here were transcribed into #816 and several of them have been fixed, so this issue is no longer actual and may be closed.
