### ISSUE TITLE
Mysterious Listeners.cs file

### ISSUE THREAD

**Issue by geoffreymcgill** [extnet/Ext.NET#679]
I'm not entirely sure what the purpose of the `\Ext.Net\Events\Listeners\Listeners.cs` file is? It appears to be auto-generated, and renders an `ErrorGeneratingOutput` message to the file. 

    /********
     * @version   : 3.1.0 - Ext.NET License
     * @author    : Object.NET, Inc. http://object.net/
     * @date      : 2015-02-17
     * @copyright : Copyright (c) 2008-2015, Object.NET, Inc. (http://object.net/). All rights reserved.
     * @license   : See license.txt and http://ext.net/license/. 
     ********/ErrorGeneratingOutput

I'm sure we can remove this file, although it would be interesting to determine what is generating the file, and why? Maybe there is a defect in the ERB somewhere.

**Comment by DaniilVeriga** [comment]
The files are not used anywhere and in SVN by mistake.

Removed:
v2: revision 6327 (branches/2).
v3: revision 6328 (trunk).
