### ISSUE TITLE
GridPanel in Firefox: cell right click fires a CellClick event instead of CellContextMenu

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#680]
http://forums.ext.net/showthread.php?53191&p=245061&viewfull=1#post245061
http://www.sencha.com/forum/showthread.php?296729

Fixed in the revision #6314 (trunk). It goes to 3.1.0 beta.

Review if Sencha fixes.

This issue might be related:
http://forums.ext.net/showthread.php?53511-TabClose-on-FireFox

**UPDATE**: Removed the fix in v4, because it is fixed in ExtJS 6.0.1.

Review if upgrade to ExtJS 5.1.2. It is stated as fixed there as well.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16385_ allegedly fixed in ExtJS 6.0.1 release.

**Comment by DaniilVeriga** [comment]
The initial fix has been removed from v3.
From v4 it was removed before.
