### ISSUE TITLE
GridPanel with ListFilter with store causes error when grid is destroyed

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#689]
http://forums.ext.net/showthread.php?53211

Fixed in the revision 6320 (trunk). It goes to 3.1.0.

Revise if Sencha fixes it in ExtJS 5.1.1 or later.

**UPDATE**: still reproducible with ExtJS 5.1.1
**UPDATE**: still reproducible with ExtJS 6.0.1
**UPDATE**: no longer reproducible with ExtJS 6.0.2

**Comment by fabriciomurta** [comment]
This was no longer necessary after ExtJS 6.0.2 upgrade.
