### ISSUE TITLE
Store once configured with RemoteSort does not perform local sorting of client-side added data

### ISSUE THREAD

**Issue by Mimisss** [extnet/Ext.NET#699]
**Relevant forum thread:**
http://forums.ext.net/showthread.php?53731-Disable-remote-sort-and-sort-locally&p=249191#post249191

Works with version 2.x. (the example code presented in the relevant form thread works with version 2.x.).

Does not work with both nuget and latest svn version 3.x.

**Comment by DaniilVeriga** [comment]
Agreed that it is not a bug:
http://forums.ext.net/showthread.php?53731&p=249661&viewfull=1#post249661
