### ISSUE TITLE
TextArea enforceMaxLenght does't work with selection

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#70]
http://forums.ext.net/showthread.php?22483

http://www.sencha.com/forum/showthread.php?250536

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
Both the Sencha team and the Ext.NET team can no longer reproduce this issue as of Ext.NET 4.x.

Please let us know if you run into the same problem with Ext.NET 4.x (or higher) and we will reopen this Issue for investigation. Going forward, support for this issue can only be provided for Ext.NET 4.x (or higher).
