### ISSUE TITLE
On Chrome, dropdown being dismissed if GridPanel with paging inside and page limits reached

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#702]
**Related forum post:** [On Chrome, PagingToolbar is blured when last page is reached](http://forums.ext.net/showthread.php?54081)

**Overview:** If you make a dropDown (and possibly any pop-up or tooltip that is dismissed on focus out or click out) and add inside it a GridPanel with pager, every time you reach either the start or the end of the page list, the dropdown will be dismissed -- only and only if using google Chrome.

This happens because, once you click the navigation buttons, the button gains focus. If it becomes unavailable/disabled afterwards, the focus is transferred to somewhere else. In chrome, the focus is transferred somewhere outside the dropdown, thus the dropdown is dismissed.

Probably, related or same - #682, item 28.

Duplicates:
http://forums.ext.net/showthread.php?58492
http://forums.ext.net/showthread.php?59350

**Comment by fabriciomurta** [comment]
No milestone: we expect to see this resolved on ExtJS 5.1.1. This might come after 3.1.0 release.
Fix suggestion on forum post mentioned above.

**Comment by DaniilVeriga** [comment]
Fixed with ExtJS 5.1.1.
