### ISSUE TITLE
GridPanel with a PagingToolbar doesn't scroll top on page change

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#703]
http://forums.ext.net/showthread.php?53371
http://www.sencha.com/forum/showthread.php?295605

**Update:** Allegedly fixed in ExtJS 5.1.2.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16084_ allegedly fixed in ExtJS 5.1.2 release.
