### ISSUE TITLE
LiveSearchGridPanel doesn't work with a buffered GridPanel

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#715]
http://forums.ext.net/showthread.php?54351
http://www.sencha.com/forum/showthread.php?295452

**Update:** This is allegedly fixed since 6.0.0.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16022_ allegedly fixed in ExtJS 6.0.0 release.

**Comment by fabriciomurta** [comment]
Leave a comment
