### ISSUE TITLE
TabPanel, IE8 + zoom: "ellipsis" appears in tabs buttons

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#72]
http://forums.ext.net/showthread.php?20131

http://www.sencha.com/forum/showthread.php?231526

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-6825.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-6825_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.3 release. Issue is acknowledged by Sencha under ID _EXTJS-6825_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-6825_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-6825_.
