### ISSUE TITLE
ComboBox's list or DropDownField's component doesn't collapse on scroll in Firefox

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#720]
http://forums.ext.net/showthread.php?53671

**UPDATE**: still reproducible with ExtJS 5.1.1.

**Update:** Sencha issue identified and still open after 6.0.1 release.
Sencha issue: [Combobox boundlist does not collapse when in scrolling container - Firefox Only](https://www.sencha.com/forum/showthread.php?300678)

**Update:** Sencha pointed to a new issue, which has been fixed since 6.0.0: [5.1.1 Nightly: Mouse scroller on Firefox just move some millimeters the grid](https://www.sencha.com/forum/showthread.php?296278)

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
Sencha pointed to a new issue, which has been fixed since 6.0.0: 5.1.1 Nightly: Mouse scroller on Firefox just move some millimeters the grid

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-15892_ allegedly fixed in ExtJS 6.0.0.415 release.
