### ISSUE TITLE
GridView's DisableSelection="false" doesn't disable selection

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#723]
http://forums.ext.net/showthread.php?53651
http://www.sencha.com/forum/showthread.php?298197

**Update:** This is allegedly fixed since ExtJS 5.1.2.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16800_ allegedly fixed in ExtJS 5.1.2 release.
