### ISSUE TITLE
LineSeries Fill="true" doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#725]
Reported in #682, item 7.

Here is an open bug report to Sencha.
http://www.sencha.com/forum/showthread.php?297109

**Update:** This is allegedly fixed since ExtJS 5.1.2.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-16478_ allegedly fixed in ExtJS 5.1.2 release.

**Comment by fabriciomurta** [comment]
Sencha says they fixed the bug report since 5.1.2 so, if not already, this will be going into Ext.NET 4.1.0! :)
