### ISSUE TITLE
ComboBox's ForceSelection just clears value when invalid entry is chosen

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#738]
On ExtJS (5.1) version, ComboBox's ForceSelection feature is just clearing the selected value instead of selecting either previous valid or first valid in the combo box entries list.

Although this behavior might be wanted in some scenarios (to allow a blank combo box), it is not always the case, as in example [PropertyGrid with Button DirectEvent](http://examples.ext.net/#/PropertyGrid/Basic/Overview/).

Also, previous versions of ExtJS had the behavior of choosing one valid entry in the combo instead of clearing it.

This error has been spotted in this post: [PropertyGrid >Basic > Overview example is broken #7](http://forums.ext.net/showthread.php?54911#post255561) from Raphael Saldanha.

**UPDATE by @DaniilVeriga**: I have found a couple of related threads in the Sencha forums. It looks like they are about the same problem.
http://www.sencha.com/forum/showthread.php?298183
http://www.sencha.com/forum/showthread.php?298524

It is stated as fixed in ExtJS 5.1.1. I would say we wait ExtJS 5.1.1. If it is not fixed wit 5.1.1, then we might revisit it.

**Comment by fabriciomurta** [comment]
This case is not the same as #136.

**Comment by fabriciomurta** [comment]
Additionally, `combobox.lastSelection` is not being updated every time one item is selected, so it is needed to have a listener bound to the `Select` event to update the information.

**Comment by fabriciomurta** [comment]
A working revision is available at [this gist](https://gist.github.com/fabriciomurta/5f1360513f947c4412bd/revisions). Evaluate if we fix only the example or review solution to apply the fix system-wide.

**Comment by DaniilVeriga** [comment]
Appears to be fixed with ExtJS 5.1.1.
