### ISSUE TITLE
Callout appears behind the Window

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#770]
http://forums.ext.net/showthread.php?57441

**Update:** Still reproducible in 6.0.1.

**Comment by fabriciomurta** [comment]
This is an Ext.NET-specific component, thus removing the "sencha" tags from issue.

**Comment by fabriciomurta** [comment]
I have just tested this against Ext JS 7.2.0 (Ext.NET 5.2.0) and giving the callout the `AlwaysOnTop="True"` setting, it stays on top of the window both in the original report and the recent one by @Z!.,
