### ISSUE TITLE
Enabling a disabled container leaves a mask on child component

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#776]
http://forums.ext.net/showthread.php?57891
http://www.sencha.com/forum/showthread.php?295910
http://www.sencha.com/forum/showthread.php?297235

Duplicate:
http://forums.ext.net/showthread.php?58411

Fixed in ExtJS 5.1.1 and Ext.NET 3.2.0.

**Comment by fabriciomurta** [comment]
This Sencha thread was marked as duplicate and moved out of the main comment:
http://www.sencha.com/forum/showthread.php?297235
