### ISSUE TITLE
Window doesn't update its layout on a browser resize if width/height are set in percents

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#794]
https://www.sencha.com/forum/showthread.php?295343

It is probably fixed in ExtJS 5.1.1. Review after upgrade.

A possible workaround is here:
http://forums.ext.net/showthread.php?59379

**UPDATE**: Still reproducible with ExtJS 5.1.1 and Ext.NET 3.2.0.
**Update:** This reads as **fixed** in forums. Adding the *review* tag.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue allegedly fixed by the time ExtJS 6.5.0 was released.
