### ISSUE TITLE
Locking a GridPanel's Column might cause a JavaScript error if there is a specific number of rows

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#797]
http://forums.ext.net/showthread.php?59436

This Sencha forum thread is about the same JavaScript error - `Cannot read property 'els' of undefined`. Probably, related.
https://www.sencha.com/forum/showthread.php?300539

**Update:** This issue was NOT reproducible in Ext.NET 4 (using ExtJS 6.0.1).

**Comment by fabriciomurta** [comment]
The Sencha thread says it is a duplicate of an ExtJS issue ID, but it does not point to any other public Sencha forums' thread, so I'm moving the link out as we can't rely on that forum thread to query the issue. Anyway, as noted before, it is not reproducible by current Ext.NET versions running under ExtJS 6.x.

Original (dup) Sencha link: https://www.sencha.com/forum/showthread.php?300539
