### ISSUE TITLE
.setDisabled() is not working on RadioGroup, CheckBoxGroup, FieldSet (and maybe others)

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#801]
This is based on this forum thread: [setDisabled(false) not working for RadioGroup](http://forums.ext.net/showthread.php?59522-setDisabled(false)-not-working-for-RadioGroup)

**Comment by DaniilVeriga** [comment]
`.setDisabled()` started to work with ExtJS 5.1.1 and Ext.NET 3.2.0.
