### ISSUE TITLE
SVN log in examples explorer does not work.

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#810]
It is broken since v2.x.
These links are not working:
[SVN Log for examples 3.x](http://examples.ext.net/#/Getting_Started/Release_Documents/SVN_Log/) (currently with 3.1 version)
[SVN Log for examples 2.x](http://examples.ext.net/#/Getting_Started/Release_Documents/SVN_Log/)

It is also broken on current 3.2 branch.

**Comment by geoffreymcgill** [comment]
Fixed
