### ISSUE TITLE
Checkbox should ignore inputWidth

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#82]
http://forums.ext.net/showthread.php?22773

http://www.sencha.com/forum/showthread.php?252354

This has been fixed in SVN. Needs to review it in the future and remove our fix if Sencha will fix it itself.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
WebForms test case:

```
<%@ Page Language="C#" %>

<!DOCTYPE html>

<html>
<head runat="server">
    <title></title>
</head>
<body>
    <form runat="server">
        <ext:ResourceManager runat="server" />

        <ext:FormPanel runat="server" ID="myForm" BodyPadding="10">
            <FieldDefaults LabelWidth="105" InputWidth="90" LabelAlign="Right" />
            <Items>
                <ext:FieldContainer runat="server">
                    <Items>
                        <ext:TextField runat="server" />
                        <ext:TextField runat="server" />
                        <ext:Checkbox runat="server" />
                    </Items>
                </ext:FieldContainer>
            </Items>
        </ext:FormPanel>
    </form>
</body>
</html>
```

**Comment by fabriciomurta** [comment]
Both the Sencha team and the Ext.NET team can no longer reproduce this issue as of Ext.NET 4.x.

Please let us know if you run into the same problem with Ext.NET 4.x (or higher) and we will reopen this Issue for investigation. Going forward, support for this issue can only be provided for Ext.NET 4.x (or higher).
