### ISSUE TITLE
"Cannot read property 'focus' of undefined" JavaScript error

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#827]
Caught in #809, item 44.

A related Sencha bug report.
https://www.sencha.com/forum/showthread.php?301306

**UPDATE**: 

Fixed in the revision 6458 (trunk). It goes to 3.2.0.

Marked as fixed in ExtJS 5.1.2. Review after upgrade.

*UPDATE*;

Removed our fix from v4, because it is fixed in ExtJS 6.0.1.

Still needs to review if upgrade v3 to ExtJS 5.1.2.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-17886_ allegedly fixed in ExtJS 5.1.2 release.

**Comment by DaniilVeriga** [comment]
Removed the initial fix from v3.
From v4 it was removed before.
