### ISSUE TITLE
"Plants" data service from examples may trigger Date Format Exception in some situations

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#830]
In example [Form -> DropDown Field -> Overview](http://examples.ext.net/#/Form/DropDownField/Overview/), in some situations, expanding the last dropdown may result in a 500 error from `Examples\GridPanel\Shared\Plan.cs`, function `TestData`.

Likely, it depends on culture Info on the server/development machine. On the line that reads:
`IFormatProvider culture = new CultureInfo("en-US", true);`

Leaving the second parameter of the class instantiation as `true` results in a date format conversion error later on, where it reads `03/15/2006` and can't interpret as a valid date.

Setting the class's second parameter to `false` (ignore user overrides) allows the code to work correctly.

This might be happening cause, while english date format might be MM/DD/YYYY, I am using DD/MM/YYYY on my development machine.

Probably, setting useUserOverrides in CultureInfo() is desired only to displaying data to the user, and might be false while writing/reading data files, which is the case here.

**Comment by DaniilVeriga** [comment]
Changed `true` to `false` in the revision 6472 (trunk).

@fabriciomurta, I completely agree that there has to be `false`, because the data is hardcoded in the .xml file and it nohow depends on a user's date format.
