### ISSUE TITLE
Page can become unresponsive if store with AutoLoad="false" receives a "reload()" call

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#847]
Reported here: [Layout stops updating after reloading store with AutoLoad = false](http://forums.ext.net/showthread.php?59831)

Run the sample provided on the first post.

### Reproduce the bug: 

If you click the 'Reload' button, the panel below will lose its interactivity (expand/collapse).

### Circumvent the bug:
Reload the page.
If you (via console) call `App.TestStore.load()`, no data will be loaded, but then following clicks to the 'Reload' button will not break the layout interactivity. (until page refresh/reload).

**Comment by DaniilVeriga** [comment]
Fixed in the revision 6507 (trunk).
