### ISSUE TITLE
Ext.NET MVC4 .NET 4.5.1 DLLs on website zip package are wrong

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#850]
Reported on this issue: [Ext DLL and MVC References](http://forums.ext.net/showthread.php?59854)

Ext.NET zip packages for the MVC version (with and without Examples Explorer) has the wrong DLL files inside the `lib/MVC4/net451` directory. The DLLs there are requiring MVC v5.2.2.0 in order to run.

Rebuilding Ext.NET on the corresponding configuration (`MVC4 NET451 Debug` tested) correctly builds it for MVC4.

The `MVC4 NET451 Release` setting though is set to MVC 5.2.2.0. This must be fixed and then the packages (including NuGet) updated.

**Comment by fabriciomurta** [comment]
The Solution's `MVC4 NET451 Release` and `MVC5 NET451 Release` configurations were all mapping to the `Debug` configuration in each project.

Also WebForms configurations were selecting the Ext.NET.Examples.MVC project to build.
One configuration (webforms 35) was not selecting Ext.Net (main project) to build.

**Comment by fabriciomurta** [comment]
VS2012, VS2013 and VS2015 solution files reviewed to:
- Build the corresponding configurations for MVC4 NET451 Release mode
- Build the corresponding configurations for MVC5 NET451 Release mode
- Build the Ext.Net project on WebForms NET451 Release mode
- Not build Ext.Net.Examples.MVC on any of the WebForms configurations.

The fixes were send in SVN revision 6505.

**Now it is necessary to rebuild the packages to the .zip files.**

**Comment by DaniilVeriga** [comment]
Just an update - the 451 build modes have been removed in favor of 452 ones. Related revisions are 6541, 6542, 6543 (trunk).
