### ISSUE TITLE
GridPanel with locking grid and summary plugin is broken

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#851]
Reported here: [grid Locked and Summary](http://forums.ext.net/showthread.php?59848)

## Overview
If you enable one or more locked columns on a gridpanel with the summary feature/plugin, a JavaScript error will be thrown from `Ext.Dom.Element.query()` as the `selector` variable will be null.

## Bug history
Up to **r6427** this bug didn't happen. On **r6429** this bug was already reproducible. The commits for 6428 and 6429 are the extjs 5.1.1 initial merge, before reviewing fixes on 3.1 that were fixed on 5.1.1. The bug is the same since then so, no review after ExtJS 5.1.1 merge affected this bug.

## How to reproduce
The forum report has a reproduction example. Also if you get the following example on Examples Explorer: [GridPanel with Locking Columns](http://examples.ext.net/#/GridPanel/Locking_Grid/Simple/) and add the following code to the Page_Load() function (~line 40):
`this.GridPanel1.Features.Add(new Summary());`
The bug will be reproduced on page load.

## Bug analysis
The bug can be tracked back to `Ext.View.Table.SyncRowHeightBegin()`, where it uses `this.all`.
The way ExtJS 5.1.1 loads the collection of elements in `Ext.View.Table.all` is different.
On ExtJS 5.1.0 for the **example provided in the forum thread**, this variable will return 72 entries, all with class 'x-grid-item'.
On ExtJS 5.1.1, the same would return just 76 entries, and they always alternate between `x-grid-item` and `x-grid-item x-grid-item-alt` (suggests row alternating styles).

Additionally, for ExtJS 5.1.1 (ext.net 3.2+) `Ext.View.Table.rowTpl` has a depth 2 `beginRowSync` defined function, i.e. `me.rowTpl.nextTpl.nextTpl.beginRowSync`. The former version does not define this at the time of the breakdown.

### Helpful breakpoints
`Table.View.Table.syncRowHeightBegin()` (5.1.0: 964765; 5.1.1: 97624)
`Ext.Dom.Element.query()` (5.1.0:21806; 5.1.1: 22009)
All breakpoints in original extjs-all-debug.js embedded script.

**UPDATE**: 
Removed our fix in 4.0 beta, because it has been fixed in ExtJS 6.0.1.
Leaving the issue open to review if upgrade to ExtJS 5.1.2.

**Comment by DaniilVeriga** [comment]
I've found a [bug report](https://www.sencha.com/forum/showthread.php?301389) on the Sencha forums with, unfortunately, no fix. Nevertheless, fixed in the revision 6508 (trunk). It goes to 3.2.1.

The fix should be reviewed and most likely removed after upgrade to 5.1.2.

**Comment by DaniilVeriga** [comment]
Removed our fix in 4.0 beta, because it has been fixed in ExtJS 6.0.1.
Leaving the issue open to review if upgrade to ExtJS 5.1.2.

**Comment by DaniilVeriga** [comment]
Removed the fix after upgrade to ExtJS 5.1.2.
