### ISSUE TITLE
Implement support for .NET 4.6

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#854]
Microsoft recently launched .NET framework 4.6 and MVC 6. This issue will track the implementation of .NET Framework v4.6 to Ext.NET 3.

This request was made on this forum thread [Ext.Net and ASP.NET 5 (vNext)](http://forums.ext.net/showthread.php?59789).

**Comment by DaniilVeriga** [comment]
Added .NET v4.6 build configurations in the revision 6526 (trunk).
