### ISSUE TITLE
Implement support for .NET 4.5.2.

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#856]
With Visual Studio 2015, Microsoft also released .NET Framework v4.5.2. Support for it should be implemented on EXT.NET.

**Comment by fabriciomurta** [comment]
SVN revision **6509** implements this functionality. Works on VS2013 and **VS2015**.

A typo in the commit message suppressed the gitHub issue number, the following command should be performed in order to fix the commit message (no support on SVN server):
```
svn propset -r 6509 --revprop svn:log "[NEW] [#856] .NET Framework v4.5.2 config bindings for Ext.Net + Examples + MVC."
```

**Comment by fabriciomurta** [comment]
@DaniilVeriga: can  you check if the changes on the VS2012 solution are working? If so, you can close this issue.

**Comment by DaniilVeriga** [comment]
Checked all the `* NET452` configurations. All was built flawlessly. Just in case checked target .NET of dlls via ILSpy - all dlls are targeted as 4.5.2.
