### ISSUE TITLE
Tooltips are not shown on mouseover on Touch devices (but with mouse)

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#857]
http://forums.ext.net/showthread.php?59602
https://www.sencha.com/forum/showthread.php?294714
https://www.sencha.com/forum/showthread.php?301258

Fixed in the revision 6512 (trunk).

**UPDATE**: fixed in ExtJS 5.1.3
**UPDATE**: still not fixed in ExtJS 6.0.1.

**Comment by fabriciomurta** [comment]
This issue has [allegedly been fixed in ExtJS 6.0.2](http://docs.sencha.com/extjs/6.0/whats_new/release_notes.html) (sencha issue id: EXTJS-17892)

Issue #671 has changes on the same override so it should be checked as well.

**Comment by fabriciomurta** [comment]
After testing, without the override (but keeping #671 fix!) I could successfully show the tooltip from a touch device (android phone using chrome browser).

**Comment by fabriciomurta** [comment]
Reopen: this issue should be reviewed once 3.x version is upgraded to ExtJS 5.1.3 if it gets released!

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-17892_ allegedly fixed in ExtJS 5.1.3 release.

**Comment by DaniilVeriga** [comment]
v3: remove the fix if upgrade to 5.1.3
v4: not fixed in ExtJS 6.0.1. Review if upgrade to 6.0.2, because there is a note that [it is fixed partially only in ExtJS 6.0.2](https://www.sencha.com/forum/showthread.php?301258-Tooltip-should-not-ignore-mouseover-event-on-touch-devices&p=1132564&viewfull=1#post1132564).
