### ISSUE TITLE
ComponentLoader TabPanel Problem

### ISSUE THREAD

**Issue by ismailkocacan** [extnet/Ext.NET#862]
I'm testing that release https://www.nuget.org/packages/Ext.NET/3.2.0

1 - I have create TabPanel below like
<pre><code class='language-cs'>
                    X.TabPanel()
                        .ID("tabContainer")
                        .SetTitle("tab1")
                        .Region(Region.Center)
                        .Frame(true)
                        .Items
                        (
                            X.Panel()
                                .Title("Main")
                                .ID("tabMain")
                                .Border(false)
                                .Icon(Icon.Application)
                                .Html("Main Content")
                        )
</code></pre>

2- I'm adding tabitem as dynamically below like
reference : http://forums.ext.net/showthread.php?59896-Checking-TabPanel-Items-In-Server-Side-(Example)&p=273925#post273925

<pre><code class='language-cs'>
public class MenuController : Controller
{
   public ActionResult TreePanelClickHandler(string param1,string param2,string param3,bool tabIsExist)
   {
    TabPanel tabPanel = X.GetCmp<TabPanel>("tabContainer");
      if (!tabIsExist)
      {
	           Panel tabItem = new Panel();
                    tabItem.Closable = true;
                    tabItem.ID = "Id" + param3;
                    tabItem.Title = param2;
                    tabItem.Tag = "Tag" + param3;
                    tabItem.Border = false;
                    tabItem.Icon = Icon.ApplicationForm;

                    ComponentLoader componentLoader = new ComponentLoader();
                    componentLoader.ID = "CmpId" + param3;
                    componentLoader.Url = "/Test/Form1";
                    componentLoader.Mode = LoadMode.Script;
                    componentLoader.Params.Add(new { containerId = tabItem.ID });
                    tabItem.Loader = componentLoader;
                    tabItem.AddTo(tabPanel);
       }
      tabPanel.SetActiveTab("Id" + param3);
      AjaxResult r = new AjaxResult();
      return r;
   }
}
</code></pre>

3- Controller class below like.
<pre><code class='language-cs'>
   public class TestController : Controller
    {
        public Ext.Net.MVC.PartialViewResult Form1(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult
            {
                RenderMode = RenderMode.AddTo,
                ClearContainer = false,
                ContainerId = containerId,
                WrapByScriptTag = false 
            };
        }
    }
</code></pre>

4- Form1.cshtml content below like.
<pre><code class='language-cs'>
@{

    var X = Html.X();
}

@(X.Panel()
     .Title("Form1")
     .ID("dasdsa")
     .Icon(Icon.Application)
     .Border(false)
     .BodyPadding(6)
     .BodyStyle("background-color:#F5F5F5;")
     .Frame(true)
     .Html(DateTime.Now.ToString()+" Form1")
)
</code></pre>

-There is no problem creating tabs.
-We can loading partialview in a Panel by using ComponentLoader class.
-When open one or more tabs,before opening tabs,content of panel inside loading partialview deleting.

any idea ?

**Comment by ismailkocacan** [comment]
I also tried

<pre><code class='language-cs'>
        @(Html.X().ResourceManager())

        @(
          X.Panel()
          .Title("Tab1")
          .ID("tab1")
          .Icon(Icon.Application)
          .Closable(true)
          .Border(false)
          .BodyPadding(6)
          .Frame(true)
          .Loader
          (
            Html.X().ComponentLoader()
               .Url("/Test/Form1")
               .Mode(LoadMode.Script)
               .Params(new { containerId = "tab1" })
          )
        )


        @(
          X.Panel()
          .Title("Tab2")
          .ID("tab2")
          .Icon(Icon.Application)
          .Closable(true)
          .Border(false)
          .BodyPadding(6)
          .Frame(true)
          .Loader
          (
            Html.X().ComponentLoader()
               .Url("/Test/Form1")
               .Mode(LoadMode.Script)
               .Params(new { containerId = "tab2" })
          )
        )
</code></pre>

Result View
![ScreenShot](https://lh3.googleusercontent.com/CbjtK7pFy0CrGyqVcFIpUNGnLM62fBMlMkaNwWt3e6M=w817-h326-no)

Why not  visible form1 named partialview in tab1 named panel ?
Is it a bug ?

**Comment by DaniilVeriga** [comment]
I think it is an ID conflict. Each new partial view is rendered with the same IDs. Then a new component is being created, it searches for a component with the same ID. If found, it is removed.

Please try to remove `.ID("dasdsa")`.

A similar problem is discussed in [this forum thread](http://forums.ext.net/showthread.php?25002).

**Comment by ismailkocacan** [comment]
yes you are right :+1: 
Yes true.not a bug. My mistake
You are great man...

**Comment by DaniilVeriga** [comment]
Thank you for confirmation and kind words!
