### ISSUE TITLE
How to Get Field Value From ModelProxy [Feature] ?

### ISSUE THREAD

**Issue by ismailkocacan** [extnet/Ext.NET#875]
I'm testing that release https://www.nuget.org/packages/Ext.NET/3.2.0
I'm testing that sample http://mvc.ext.net/GridPanel_Editable/Editor_with_DirectMethod/

Set record of field value from field name

<pre><code class='language-cs'>
 Store store = X.GetCmp<Store>("store1");
 ModelProxy modelProxy = store.GetById(id);
 modelProxy.Set("price", 50);
</code></pre>

I can't seen "Get" method at ModelProxy class ?
<pre><code class='language-cs'>
object value = modelProxy.Get("price");
</code></pre>

any idea ?

**Comment by DaniilVeriga** [comment]
`ModelProxy` is a proxy helper class to generate JavaScript code that is sent to a client as a response of a DirectEvent/DirectMethod. Even if `.Get()` method exists, you would not be able to get a value on server. It would be only used to generate a JavaScript code like `record.get('price')` and it would be sent back to client. By the way, `.GetCmp<>` is a similar feature that you might want to read details about it In this [forum post](http://forums.ext.net/showthread.php?38701&p=176681&viewfull=1#post176681).

To get a price value, you should grab it from `object customer` parameter of the controller action. Defining a dedicated `price` parameter would be an alternative option.

**Comment by ismailkocacan** [comment]
You're right. Thank you for detail response. I forgot object customer.
I will provide a real world demo now :)

**Comment by DaniilVeriga** [comment]
Thank you. Real word demos of using Ext.NET are very appreciated.

**Comment by ismailkocacan** [comment]
I was post a demo @Daniil
https://github.com/ismailkocacan/GridPanelCalculateField

**Comment by DaniilVeriga** [comment]
Great, thank you very much. I was about to say that you might want to post it in the Examples and Extras forum as well, but found that you already [posted](http://forums.ext.net/showthread.php?59955).
