### ISSUE TITLE
HtmlEdtior's ReadOnlyCls is not applied

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#887]
http://forums.ext.net/showthread.php?59994&p=274471&viewfull=1#post274471

```
<%@ Page Language="C#" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <title>Ext.NET v3 Example</title>
</head>
<body>
    <form runat="server">
        <ext:ResourceManager runat="server" />

        <ext:HtmlEditor runat="server" ReadOnlyCls="readonly-html-editor" ReadOnly="true" />
    </form>
</body>
</html>
```

Fixed in the revision 6554 (trunk).

Review after next ExtJS upgrade (5.1.1 or later).

**UPDATE**: still reproducible with ExtJS 6.0.1.

**Comment by fabriciomurta** [comment]
There's no ReadOnlyCls config option in [ExtJS 6.5.0 documentation on Ext.form.field.HtmlEditor](http://docs.sencha.com/extjs/6.5.0/classic/Ext.form.field.HtmlEditor.html), so this became an Ext.NET-specific feature and we will not expect it from being fixed from Sencha.
