### ISSUE TITLE
Grid column flex doesn't work if that column consists inner columns

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#89]
http://forums.ext.net/showthread.php?22768
http://forums.ext.net/showthread.php?26901
http://forums.ext.net/showthread.php?38631
http://forums.ext.net/showthread.php?38731
http://forums.ext.net/showthread.php?59970&p=274415&viewfull=1#post274415

https://www.sencha.com/forum/showthread.php?252333
https://www.sencha.com/forum/showthread.php?274106

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-11525_ allegedly fixed in ExtJS 6.2.0 release.
