### ISSUE TITLE
TextField's SelectOnFocus doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#890]
http://forums.ext.net/showthread.php?60042
https://www.sencha.com/forum/showthread.php?301725

The bug is marked as fixed in ExtJS 5.1.2.

Fixed in the revision 6558 (trunk). Review after the next ExtJS upgrade (5.1.2 or later).

**UPDATE**: the Sencha forum thread is marked as fixed in 5.1.2, but the issue is still reproducible in IE10 with ExtJS 6.0.1. I guess it is still reproducible in IE10 with ExtJS 5.1.2 as well. Our fix must not be removed.

**UPDATE**: 
v3: review if upgrade to 5.1.3
v4: review if upgrade to 6.0.2

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-18034_ allegedly fixed in ExtJS 5.1.3 release.

**Comment by DaniilVeriga** [comment]
v3: review if upgrade to 5.1.3
v4: review if upgrade to 6.0.2

**Comment by fabriciomurta** [comment]
It has not only been fixed after Ext.Net 4.2.0 upgrade but also is not unavoidable now. It always selects on focus. Issue dealing with that would be #1441.
