### ISSUE TITLE
LineSeries marker Type="Square" appears as a circle in a Chart itself and misaligned in both - Chart and Legend

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#893]
http://forums.ext.net/showthread.php?60065
https://www.sencha.com/forum/showthread.php?143672

Fixed in the revision 6560 (branches/2).

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
The introduced override does not exist in Ext.NET 4 code base, so the issue is no longer actual in ExtJS.
