### ISSUE TITLE
Destroy records in Store causes "Cannot read property 'setErased' of undefined" JavaScript error

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#895]
http://forums.ext.net/showthread.php?60085
https://www.sencha.com/forum/showthread.php?301217
https://www.sencha.com/forum/showthread.php?301669

[A possible fix](https://www.sencha.com/forum/showthread.php?301217&p=1100767&viewfull=1#post1100767)

Marked as fixed in ExtJS 5.1.2.

Fixed in the revision 6552 (trunk). 

**UPDATE**: 
 * The fix has been removed in v4.
 * Remove the fix in v3 as well after upgrade to ExtJS 5.1.2.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-17882_ allegedly fixed in ExtJS 5.1.2 release.

**Comment by DaniilVeriga** [comment]
v3: the initial fix has been removed
v4: the initial fix was removed before
