### ISSUE TITLE
GridPanel.setSelection(0) doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#902]
http://forums.ext.net/showthread.php?60125
https://www.sencha.com/forum/showthread.php?296242

Fixed in the revision 6570 (trunk). 

Review after the next ExtJS upgrade (5.1.2 or later).

**UPDATE**: still an issue in ExtJS 6.0.1.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
ExtJS 6.5.0 introduced a change on the overridden method but it did not address (nor was meant to address) the bug at all. The change was merged in the overridden method.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.0 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.1 release. Issue is acknowledged by Sencha under ID EXTJS-16286.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.2 release. Issue is acknowledged by Sencha under ID _EXTJS-16286_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.5.3 release. Issue is acknowledged by Sencha under ID _EXTJS-16286_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.6.0.258 release. Issue is acknowledged by Sencha under ID _EXTJS-16286_.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.7.0.161 release. Issue is acknowledged by Sencha under ID _EXTJS-16286_.
