### ISSUE TITLE
Component's onAlignToScroll causes issues

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#903]
http://forums.ext.net/showthread.php?60128

Fixed in the SVN trunk revision 6602. It goes to the 3.3 release.

Review after upgrading to 5.1.2 or higher.

**Comment by DaniilVeriga** [comment]
There is another test case that the initial fix doesn't cover.
http://forums.ext.net/showthread.php?60346

**Comment by fabriciomurta** [comment]
This override is no longer necessary for ExtJS as of 6.2.0.
