### ISSUE TITLE
Several issues with grid column with inner columns

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#91]
http://forums.ext.net/showthread.php?19629

Already closed
http://www.sencha.com/forum/showthread.php?252478
http://www.sencha.com/forum/showthread.php?258475

Still opened
http://www.sencha.com/forum/showthread.php?258478

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment]
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment]
The last remaining issue, http://www.sencha.com/forum/showthread.php?258478, is IE7-specific. As it is no longer supported on current ExtJS versions, it is not supposed to be ever fixed, if the error persists.
