### ISSUE TITLE
GridPanel Grouping breaks if a group value is an empty string

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#919]
http://forums.ext.net/showthread.php?60224
https://www.sencha.com/forum/showthread.php?301099

Marked as fixed in ExtJS 5.1.2 and 6.0.0.

Fixed in the SVN trunk revision 6598. The fix goes to the 3.3 release. 

Review after upgrading to ExtJS 5.1.2 or higher.

**Comment by DaniilVeriga** [comment]
Removed our fix, because it has been fixed in ExtJS 6.0.1.
Leaving the issue open to review if upgrade to ExtJS 5.1.2.

**Comment by fabriciomurta** [comment]
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-17776_ allegedly fixed in ExtJS 6.2.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-17776_ allegedly fixed in ExtJS 6.2.2 release.

**Comment by fabriciomurta** [comment]
**Update:** Sencha issue _EXTJS-17776_ allegedly fixed in ExtJS 6.2.2 release.
