### ISSUE TITLE
CheckboxSelectionModel handles a header click even if ShowHeaderCheckbox is false

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#929]
http://forums.ext.net/showthread.php?60274
https://www.sencha.com/forum/showthread.php?304505

It has been fixed in 3.3. 

**UPDATE**:

It was fixed in ExtJS 5.1.2. Our fix has been removed in 3.3.

It is marked as fixed in ExtJS 6.0.2. Review after upgrade to this version or later.

**Comment by fabriciomurta** [comment]
It is indeed fixed in ExtJS 6.0.2. Override no longer necessary.
