### ISSUE TITLE
New Ext.grid.selection.SelectionExtender Class

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#957]

**Comment by DaniilVeriga** [comment]
The SelectionExtender is used by SpreadsheetSelectionModel internally. It is not going to be used explicitly by developer and configurable via a SpreadsheetSelectionModel's [Extensible](https://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.grid.selection.SpreadsheetModel-cfg-extensible) property.

Marking the issue as invalid.
