### ISSUE TITLE
Ext.list.Tree Component

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#958]
http://docs.sencha.com/extjs/6.0/6.0.2-classic/#!/api/Ext.list.Tree

## See Also

* http://forums.ext.net/showthread.php?60806

**Comment by fabriciomurta** [comment]
TreeList support has also been requested here: [TreeList in Ext.NET](https://forums.ext.net/showthread.php?61809)

**Comment by ASchott82** [comment]
Hi, 
we are also very interested in tree list. We bought a Ext.Net license some weeks ago and it would be great to use this in our project.
Thanks!

**Comment by fabriciomurta** [comment]
Sorry for the long delay having this included to Ext.NET. Got good news! This is going to be included in our next release, 4.7.0!
