### ISSUE TITLE
New on PieSeries - HighlightCfg Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#993]
Details:
```
5.1.1
type is Object
6.0.0
type is Ext.chart.series.sprite.PieSlice/Object
```

**Comment by fabriciomurta** [comment]
Found this item is not currently on PieSeries. Changed issue to add it.

**Comment by DaniilVeriga** [comment]
In Ext.NET it is called `HighlightConfig` rather than `HighlightCfg`. I'll remove `HighlightCfg`.
