### ISSUE TITLE
Removed on PieSeries - LengthField Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#996]

**Comment by DaniilVeriga** [comment]
I've merged the commit, but please post what a substitution of LengthField. That is required for our breaking changes document.

**Comment by DaniilVeriga** [comment]
http://docs.sencha.com/extjs/6.0/upgrades_migrations/extjs_upgrade_guide.html

> Polar series.
> Polar series ‘angleField’ and ‘radiusField’ configs have replaced ‘field’/‘xField’ and ‘lengthField’/‘yField’ configs, respectively.
