### ISSUE TITLE
PieSeries', Pie3DSeries' HiddenArray Config has been renamed to Hidden

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#997]
Details:
```
5.1.1
default value is false
type is Boolean|Array
6.0.0
default value is []
type is Array
```

**Comment by fabriciomurta** [comment]
Not found on either `Pie3DSeries` nor `PolarSeries`. It currently accepts only boolean and is inherited from `Series` where, according to [ExtJS 6.0.1 documentation]() it should also accept `Boolean|Array`.

Additionally, on `PolarSeries`, it still types to `Boolean|Array`, not just `Array` and defaulting to `[]`.
According to the documentation, it shouldn't inherit `Hidden` from `PolarSeries` anymore.

**Comment by fabriciomurta** [comment]
Notice this attribute is as Array-only in both PieSeries and Pie3DSeries but it is still valid as boolean (as well as array) on PolarSeries. According to the documentation.

**Comment by fabriciomurta** [comment]
This requires either using `override`, `new` (and fixing meta parser) or break inheritance from `PolarSeries` for the `PieSeries` and `Pie3DSeries` classes.

**Comment by DaniilVeriga** [comment]
There is a HiddenArray property available. It is an approach how Ext.NET deal with such dual-type properties.

**Comment by DaniilVeriga** [comment]
No changes here. PieSeries and Pie3DSeries still use a HiddenArray property.
