### ISSUE TITLE
New on PolarSeries - RadiusField Config

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#999]

**Comment by fabriciomurta** [comment]
This depends on what is decided on #997.

**Comment by DaniilVeriga** [comment]
I think the RadiusField should be added for PolarSeries and removed from PieSeries.

I think it exists in ExtJS docs for PieSeries by mistake or just for a little different comment.

**Comment by DaniilVeriga** [comment]
Okay, changing my mind - Pie3DSeries doesn't support RadiusField:
http://docs.sencha.com/extjs/6.0/6.0.1-classic/#!/api/Ext.chart.series.Pie3D-cfg-radiusField

So, it should not be added for PolarSeries. Otherwise, Pie3DSeries would inherit it. 

I will handle it.

**Comment by DaniilVeriga** [comment]
So, RadiusField has been already added for PieSeries - #991.

The current issue is invalid.
